### ISSUE TITLE
Quidel missing from Indicator Status

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#1004]
**Actual Behavior:**

We used to show Quidel; not sure what happened to it

**Steps to Reproduce the Bug:**

1. go to https://delphi.cmu.edu/covidcast/indicator-status
2. No entry for Quidel

**Expected behavior**

Quidel should appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/1158666/131517946-32109842-c8a4-4484-ba1d-2027aa37a491.png)

**Rating Scale (1 is minor, 7 is severe):** 3 -- it's missing from the interface, and it's hard to monitor while it remains missing, but the quidel source is not part of any mission-critical work

**Context**

- Browser: Chrome on Mac

**Comment by sgratzl** [comment]
see https://docs.google.com/spreadsheets/d/1zb7ItJzY5oq1n-2xtvnPBiJu2L3AqmCKubrLkKJZVHs/edit#gid=0 and https://api.covidcast.cmu.edu/epidata/covidcast/meta?signal=quidel-covid-ag:* -> there was a space after defining the reference signal which let the UI not find it

**Comment by krivard** [comment]
thank you, on it

**Comment by krivard** [comment]
Fixed!
