### ISSUE TITLE
Link from indicator to data export doesn't work

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#1007]
**Actual Behavior:**

If I load this indicator page: https://delphi.cmu.edu/covidcast/indicator/?sensor=fb-survey-smoothed_wcovid_vaccinated_appointment_or_accept&date=20210903

Below the beehive is a little arrow button to download the data. If I select "Advanced Data Export" I get taken to this page:

https://delphi.cmu.edu/covidcast/export/?sensor=fb-survey-smoothed_wcovid_vaccinated_appointment_or_accept

I'd expect this to load the data export page with the appropriate data source and signal pre-selected (and I think that used to work), but it doesn't. I have to select the source and signal manually.

**Expected behavior**

Clicking the data export link prepopulates the exporter with the information for that signal.

**Rating Scale (1 is minor, 7 is severe):**

3

**Context**

- Browser: Firefox 91

**Comment by sgratzl** [comment]
should be part of the latest dev
