### ISSUE TITLE
Toggling Show Raw Data creates unwanted movement

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#1018]
**Actual Behavior:**

When toggling on Raw Data, the x-axis labels switch which ticks they render on. This is disorienting.

Additionally, the chart title and subtitle shift to the left, and the x limits increase in both directions, squashing the display and the major gridlines inward horizontally.

**Steps to Reproduce the Bug:**

1. go to https://delphi.cmu.edu/covidcast/survey-results/?date=20210923
2. scroll to the first plot
3. toggle raw data on and off

**Expected behavior**

Render using constant x-axis limits and title positioning, so that the plot fixtures don't move when turning raw data on and off.

**Screenshots**

![image](https://user-images.githubusercontent.com/1158666/134719652-d30bc5bb-c95a-414c-bdec-f531e5b93387.png)
![image](https://user-images.githubusercontent.com/1158666/134719674-60042d97-5527-43e9-8f2e-cf62bffe6a70.png)

**Rating Scale (1 is minor, 7 is severe):** 3 -- doesn't prevent use, but Ryan asked about it

**Context**

- Browser: Chrome
- Width of HTML & BODY components as listed in inspector: 1350

**Comment by ryantibs** [comment]
Thanks @sgratzl.  I haven't looked at the fix yet but wanted to mention that this behavior happens also on the "Raw Data" toggle on the main viz site.

In creating a screenshot (which shows a very slight shift of the x-axis; it's more visible when you're clicking on it interactively), I noticed another bug: the "Show Cumulative" toggle is only visible when "Raw Data" is toggled "on".

<img width="658" alt="Screen Shot 2021-09-25 at 11 19 19 AM" src="https://user-images.githubusercontent.com/732541/134776617-c0a267a1-4683-4ef8-8deb-6bca6a60f796.png">
<img width="660" alt="Screen Shot 2021-09-25 at 11 19 27 AM" src="https://user-images.githubusercontent.com/732541/134776619-7025fe4d-b830-4106-ba2b-b6e46322326b.png">

**Comment by sgratzl** [comment]
>  "Show Cumulative" toggle is only visible when "Raw Data" is toggled "on".
this is on purpose since cumulative doesn't make sense for averaged date. So only the raw data can be shown as cumulative. 

> "Raw Data" toggle on the main viz site.
all the same component so the fix also applies to this one
