### ISSUE TITLE
Automatic Signal Names differ from previously configured ones

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#1022]
**Actual Behavior:**

see comment from different issue:
> The plot titles look off from the live version. For example, I see the word "(Weighted)" in the plot title now in a bunch of places (attached screenshot is an example), where I don't see this in the live version. Is this a bug or just something that will be automatically fixed in the live version?
![image](https://user-images.githubusercontent.com/4129778/134777844-c09074ea-2bca-4314-9b17-4b6b4f02086d.png)

reason: 

which the change to the sheet based metadata all signals got new names and suffixes. While in the previous version the names were explicitly configured, #1012 changed it to use the meta data directly resulting in a name change. 

possible options: 
 * in the remaining google doc, explicitly override the name for signals
 * leave it, since it is more descriptive anyhow
 * change signal name in meta data

**Comment by krivard** [comment]
@capnrefsmmat @RoniRos is this approved? This would mean we use different names for signals when displaying them on the survey dashboard vs in the indicator status pages. Wouldn't it be better to just ... put the names we want in the meta sheet?

**Comment by capnrefsmmat** [comment]
> Wouldn't it be better to just ... put the names we want in the meta sheet?

Yes. But the reason "(Weighted)" is in these signals is because the meta sheet contains both weighted and unweighted versions, and they both appear in the Export Data system. So we need to be able to tell the difference.

I propose we remove "(Weighted)" and add "(Unweighted)" to the unweighted signals, thus better reinforcing that weighted signals should be the default and making the survey dashboard not contain extra gunk.

**Comment by krivard** [comment]
> I propose we remove "(Weighted)" and add "(Unweighted)" to the unweighted signals, thus better reinforcing that weighted signals should be the default and making the survey dashboard not contain extra gunk.

@capnrefsmmat pinged you in the meta sheet
