### ISSUE TITLE
Wrong most recent date in hover tip

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1026]
When I hover over the a signal in the survey dashboard it tells me the most recent data available was from Sept 23 but you can see from the spark line that it's actually available all the way until Sept 25.

<img width="708" alt="Screen Shot 2021-09-26 at 3 58 16 PM" src="https://user-images.githubusercontent.com/732541/134823547-6ea6652c-a842-4270-bed0-980c6a2c68f8.png">

**Rating Scale (1 is minor, 7 is severe):** 1

**Comment by sgratzl** [comment]
https://api.covidcast.cmu.edu/epidata/covidcast/meta?signal=fb-survey:smoothed_wcli

shows: 
```
"max_issue": 20210927,
"max_time": 20210925,
"min_time": 20200406,
"name": "COVID-Like Symptoms (Weighted 7-day average)",
"short_description": "Estimated percentage of people with COVID-like illness ",
"signal": "smoothed_wcli",
```

however, when querying the data 

https://api.covidcast.cmu.edu/epidata/covidcast/?signal=fb-survey:smoothed_wcli&geo=nation:us&time=day:20210924-20211010

the last entry is 
```
{
"geo_value": "us",
"signal": "smoothed_wcli",
"source": "fb-survey",
"geo_type": "nation",
"time_type": "day",
"time_value": 20210926,
"direction": null,
"issue": 20210928,
"lag": 2,
"missing_value": 0,
"missing_stderr": 0,
"missing_sample_size": 0,
"value": 1.4717249,
"stderr": 0.0337678,
"sample_size": 196205
}
```

The tooltip is based on the meta data the sparkline on the real data. This explains the discrepancy.

**Comment by krivard** [comment]
iirc this was a wontfix -- the "most recently available" comes from metadata, and metadata is only updated daily. The behavior is still visible in the [current dev preview](https://dev--cmu-delphi-covidcast.netlify.app/survey-results/#N4Ig9gTgJgphIC4DaIA2BLAdjA+gVhAF0AaEAZwBcBDCmMxUDbfBkAd3SgoAtEAWUtxjoA5twqIATKQBecMIgoQArjFIQqbRSpgBfXaQDGYTADNR9BIyy4CV8jExlIiEKYBGAWjLKIANxgAT28AWzAwHhgoHDZubhxDEMwKQISMEH1dIA):
![image](https://user-images.githubusercontent.com/1158666/145832051-3acfae25-6fe5-443a-8462-06ec769a8241.png)

**Comment by ryantibs** [comment]
Ok let's leave this issue open so we can schedule a hotfix at some point, but this shouldn't hold up v3 release.

I don't want this to be wontfix indefinitely---we should either disable this hovertip completely or ensure it's showing the right information.

**Comment by sgratzl** [comment]
I wonder how expensive it is that the server computes for a given list of signals what the maximum date it. So far we don't have an simple api to compute that. However, that is essentially the main discrepancy between the meta data and the real data.

**Comment by ryantibs** [comment]
@sgratzl Just a reminder about this for v3.1. Thanks!

**Comment by sgratzl** [comment]
see also https://github.com/cmu-delphi/delphi-epidata/issues/793 for a server side solution to this problem

**Comment by ryantibs** [comment]
Thanks @sgratzl. I'm happy for you and @krivard to decide on what's the best solution for this one.
