### ISSUE TITLE
CHNG CLI signal incorrectly tagged as late

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1029]
The CHNG CLI signal on the website are incorrectly tagged as "late".  It should be "early", in the same way that the doctor-visits CLI signal is early.

![Screen Shot 2021-09-27 at 2 56 29 PM](https://user-images.githubusercontent.com/732541/134969817-623b2a53-4fa3-4e5a-8c0a-502f3ee1da9f.png)

**Rating Scale (1 is minor, 7 is severe):** 2

**Comment by sgratzl** [comment]
see https://github.com/cmu-delphi/delphi-epidata/pull/723
