### ISSUE TITLE
CTIS dashboard: change sparkline aspect ratio

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#1034]
> I would like to change the aspect ratio of the sparkline in the CTIS dashboard so that it matches that of the sparklines in the indicators table on the COVIDcast site (when this table is at full width). I find them too wide on the CTIS dashboard so it obscures the visual interpretation of the trend. Screenshot below on the COVIDcast indicators table:

**Comment by sgratzl** [comment]
current version with three columns:

![image](https://user-images.githubusercontent.com/4129778/143046437-6da6b25b-f5c3-4de0-99df-63e35ca2cdde.png)

**Comment by ryantibs** [comment]
@sgratzl I'm going to close this because I think it looks OK in the current dev version (maybe it was tweaked a bit?) and I just want us to move on at this point.
