### ISSUE TITLE
Line Chart Improvements

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#1051]
- [x] include "show all dates" also in survey dashboard
- [x] remove "show cumulative" button
- [x] zoom into line charts by default and rename to "Include 0 in Y-Axis"
- [x] indicate number of neighboring counties that are used for the aggregated value

**Comment by krivard** [comment]
Did this come from Ryan's notes or from you?

**Comment by sgratzl** [comment]
> Did this come from Ryan's notes or from you?

all the v3 issues are based on the Ryan's google doc
