### ISSUE TITLE
Add doctor-visits data anomaly once deployed

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#1081]
see https://github.com/cmu-delphi/www-covidcast/pull/1080/commits/5b77e4f6cda4660af3a357d36779376d67332891 where the temporary one has been removed again

**Comment by sgratzl** [comment]
I need some text to fill out the doctor-visit uncertainty data anomaly:


* published: TRUE 
* problem: **??**
* explanation: **??**
* source: doctor-visits
* signals: smoothed_adj_cli
* dates: -10
* regions: nation(*);state(*);county(*);hrr(*)

@ryantibs suggestions?

**Comment by RoniRos** [comment]
Sharing Ryan's request for example texts, and what they look like on the screen.

**Comment by sgratzl** [comment]
it will look similar to 
![image](https://user-images.githubusercontent.com/4129778/146108269-a6c88771-db63-418c-8e52-faab775fe5ea.png)

and closer like in the PR:

https://github.com/cmu-delphi/www-covidcast/pull/1080

**Comment by ryantibs** [comment]
Thanks.  It looks like we use "Title Caps" for the problem field so we could change it to that, but other than that I think it should be fine. If you could get us a preview of how it looks for us to see, all put together, before merging, then that would be great.

**Comment by ryantibs** [comment]
@sgratzl Do you need anything more from me on this one? As I said in my last comment, if you have a PR and can show us a preview then that would be great.

**Comment by sgratzl** [comment]
it depends on #1106 and that @krivard is approving my change in https://docs.google.com/spreadsheets/d/1w3jzNizh7rBkl1P-ikXa_GW2m_tRmV97eN7naOIR6jA/edit#gid=0

**Comment by sgratzl** [comment]
current dev version: https://dev--cmu-delphi-covidcast.netlify.app/indicator/?sensor=doctor-visits-smoothed_adj_cli

![image](https://user-images.githubusercontent.com/4129778/148782569-f65c22fb-153a-4e4c-816f-bed748d4d49d.png)
