### ISSUE TITLE
Rename "COVID-19 Admissions"

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1082]
I'd like us to rename the hospital admissions signal, which is currently called "COVID-19 Admissions" everywhere --- in the indicator dropdown menu and in the titles, etc --- to be "COVID Hospital Admissions".  That way it's more aligned with the names "COVID Cases" and "COVID Deaths", which we're using for cases and deaths.

![Screen Shot 2021-12-08 at 11 32 20 AM](https://user-images.githubusercontent.com/732541/145246474-055a19f9-38b1-4ece-870f-621728e83c0d.png)
![Screen Shot 2021-12-08 at 11 32 28 AM](https://user-images.githubusercontent.com/732541/145246478-818bcd88-75f2-42a2-8acd-4256cbd812bf.png)

I thought that would be possible by renaming it in this spreadsheet: https://docs.google.com/spreadsheets/d/1zb7ItJzY5oq1n-2xtvnPBiJu2L3AqmCKubrLkKJZVHs/, but I can't find the name "COVID-19 Admissions" in the signal sheet.  There I see "Confirmed COVID-19 Admissions per day", and "Confirmed and Suspected COVID-19 Admissions per day".

@sgratzl @krivard please help.

**Comment by krivard** [comment]
That spreadsheet contains names and descriptions for every source and signal in the Epidata covidcast endpoint.

The subset that are displayed on the website are encoded here:
https://docs.google.com/document/d/1llv6xh8jMlmVv7WpyDSv4VgUpFAZQ6QjFUeRxxOinmk/edit#heading=h.2d79xl2reurh

with name and description overrides.

**Comment by ryantibs** [comment]
Thanks Katie.  It looks like you (or Sam) already updated it as per my request?
