### ISSUE TITLE
State-level graphics for hospitalizations

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1083]
I'd like us to properly support the state resolution for the HHS hospitalizations signal

1. Currently we don't show anything for the choropleth map on the "Explore an Indicator" page
![Screen Shot 2021-12-08 at 11 32 39 AM](https://user-images.githubusercontent.com/732541/145247091-fa760615-beaf-4e69-9524-5fbd6cc8f0e9.png)

2. Currently the choropleth map on the "Explore a Location" page is also grayed out ....

![Screen Shot 2021-12-08 at 11 37 46 AM](https://user-images.githubusercontent.com/732541/145247253-0c34f371-9a6e-4b81-a4cf-26e64cd6cb38.png)

I'd like us just to default to showing the state-level choropleth map in both 1 & 2.  

(The color scale is also pretty bland, everything looks like it's the same color, but I think that is due to a bug in the way we're computing the hospitalizations signal, which will be my next issue.)

**Comment by sgratzl** [comment]
re color scale: 

the meta data looks like this for this signal:

![image](https://user-images.githubusercontent.com/4129778/145313964-bc2538e9-8042-4df0-accf-d0b966ad4d8d.png)

**Comment by ryantibs** [comment]
Something is very wrong there in the metadata which I think is a reflection of the bug I raised in #1084 (which looks like it has been transferred to a different repo).  This signal is a proportion so the it shouldn't be a max of 13 at the state level and 224 at the national level.
