### ISSUE TITLE
Marcy is not a month

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1087]
Last I checked, at least.  On the Export Data page, for the "Statistical Combination" signal: 

<img width="695" alt="Screen Shot 2021-12-08 at 8 11 03 PM" src="https://user-images.githubusercontent.com/732541/145316154-52c3636f-54f9-4e40-bb93-a91fddef25a3.png">

**Comment by ryantibs** [comment]
This was supposed to be March 17.  (Check by looking at the latest available data.)

**Comment by sgratzl** [comment]
see https://github.com/cmu-delphi/delphi-epidata/pull/783

**Comment by krivard** [comment]
Fixed
![image](https://user-images.githubusercontent.com/1158666/146037212-e33b5144-7d41-4b2d-bca2-f840f321aaa8.png)
