### ISSUE TITLE
Improve clarity on indicators table

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1089]
I would like to add some clarity to the indicators table. Here is a screenshot for reference:

<img width="729" alt="Screen Shot 2021-12-08 at 8 23 19 PM" src="https://user-images.githubusercontent.com/732541/145317752-c3581a88-1f87-46ab-8adb-6fcf429fec84.png">
 

I would like to: 

1. Relabel the "Value" column to be "Latest Value"
2. Relabel the "Relative Change to Last 7 Days" column to "Relative Change to Previous Week"
3. Switch the order of the "Latest Value" and "Relative Change to Previous Week" columns
4. Increase the width of the "Trend" column, since it's currently very squished (look at the dates below, it looks like "11/0912/07"). Perhaps we should decrease the width of the "Indicator" column to accommodate this.

I also just want to confirm with @sgratzl: do we have a rule in place that prints an N/A in the "Latest Value" column (and "Relative Change to Previous Week" column) if there is no data available in the time period being shown in the "Trend" column?

**Comment by sgratzl** [comment]
> I also just want to confirm with @sgratzl: do we have a rule in place that prints an N/A in the "Latest Value" column (and "Relative Change to Previous Week" column) if there is no data available in the time period being shown in the "Trend" column?

take a look at the graph on the right side of each column. the line and the label indicate which values are being shown.

**Comment by ryantibs** [comment]
Yes I understand that, but I was asking about whether we have a rule in place for the "Latest Value" and "Relative Change to Previous Week" columns  if there is no date range being shown in the trend (in the given screenshots that would be 11/09 to 12/07).  I'm asking if that would just render as N/A.

**Comment by sgratzl** [comment]
yes atm the logic is that it only looks for a valid value within the spark line range. So if the whole sparkline is empty, it will be NA
