### ISSUE TITLE
Improve visibility of subpage menu

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1091]
Currently the only way to get the other dashboard subpages: "Explore an Indicator", "Indicator Status Overview", etc, is to click on the small box in the top right.  This is what is looks like on the dev site for me: 

<img width="1097" alt="Screen Shot 2021-12-08 at 8 53 56 PM" src="https://user-images.githubusercontent.com/732541/145320158-26dfda38-9ac2-4880-9abd-b53dd18e2c70.png">

Would it look different when it gets launched?  I want to make sure we have a way of drawing visibility to this submenu.  Otherwise a person might think that "Explore a Location" (which is the landing page for the dashboard) may be the only page they get.

**Comment by sgratzl** [comment]
the hamburger menu you see here is just in the dev environment. 

Once deployed it will be embedded into the delphi.cmu.edu website and its menu will be there to navigate between the different pages:

![image](https://user-images.githubusercontent.com/4129778/145322508-c8eb9453-108b-4c9f-80d5-f915efac70e9.png)

**Comment by ryantibs** [comment]
I see.  So it looks like you can access "Indicator Status" and "Dashboard Builder" from the Tools menu, but we still don't have an option of easily navigating in between "Explore a Location" and "Explore and Indicator" within the dashboard.

Can we add a way of doing so?  Simple idea: next to the "Explore a Location" title on the dashboard main page, we can add something like "Click here to Explore an Indicator" in parentheses, and then vice versa when on the "Explore an Indicator" page?
