### ISSUE TITLE
Tweaks to misc labels

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1098]
I would like to tweak the following misc labels throughout: 

- "Include 0 in Y-axis" --> "Include 0 in Y-Axis" (capitalize the A, this would be the proper usage of title caps style, if I'm not mistaken ... @capnrefsmmat you are my go to guy for this---can you confirm?)
- "Show US States as Beehive Grid" --> "Beehive Grid"
- "Show US Counties as Choropleth Map" --> "Choropleth Map"

Rationale for the latter two: shorter is better. Also, at least in one cases, we don't actually have any counties to show in the choropleth map (the HHS hospital admissions signal is only at the state level).

**Comment by capnrefsmmat** [comment]
> "Include 0 in Y-axis" --> "Include 0 in Y-Axis" (capitalize the A, this would be the proper usage of title caps style, if I'm not mistaken ... @capnrefsmmat you are my go to guy for this---can you confirm?)

I think that's right, yes. Maybe "Y Axis" instead of "Y-Axis"?
