### ISSUE TITLE
Remove "Include 0 in Y Axis" toggle

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1112]
I'd like us to consider removing the "Include 0 in Y Axis" toggle completely, on both the COVIDcast dashboard and the CTIS dashboard. 

I've never personally used it, and I've been using the dashboard a lot over the last 3 weeks. 

My concern is that it's just cluttering the toggle buttons that are already there (especially on mobile), and IMO it's the least important of them. 

Of course I'm only one type of user. And I know there was concern that people would be misinterpret things as trends when there is only tiny variation, without looking at the y-axis. But would simply having the option to include 0 in the y-axis really give them the hint that they should be cautious of this? 

All that taken together---and the fact that we don't really have a particular user we're targeting for the dashboards anyway---I don't think it's worth keeping it. 

Tagging @sgratzl @krivard @capnrefsmmat @RoniRos who are bound to have opinions about this 🙂

**Comment by ryantibs** [comment]
To be clear, this is low priority compared to the other v3.1 items, and I don't feel super strongly. If we can't reach a resolution, then it's fine: we can just move on without it.

**Comment by ryantibs** [comment]
Removing this from consideration for v3.1 in the interest of moving fastest to complete v3.1. (From team leads meeting today, Katie was very opposed, and Roni indifferent.)

**Comment by capnrefsmmat** [comment]
Note that in the [survey dashboard](https://delphi.cmu.edu/covidcast/survey-results/), the signals with "Raw Data" toggles automatically include 0 in the Y axis when the raw data is included, because the raw data is shown as bars. I believe this is also applied to case and death signals in the dashboard.

I would agree that bars need to have 0 in the Y axis, whereas line graphs often don't need to. (A bar that doesn't go to 0 is actively misleading; a line graph that doesn't go to 0 can often be entirely appropriate.) But it's something to think about when removing the toggle, because we do switch the axes sometimes for valid reasons.

**Comment by ryantibs** [comment]
That's a great point Alex. I hadn't thought of that before. 

How about: include 0 for bar graphs (raw data), no 0 for line graphs. (And no separate toggle for including 0.)

@krivard What do you think about my proposal? If you're amenable, I'll retag this v3.1!

Btw here's a couple screenshots from the dashboard showing what Alex is alluding to. Note: the fact that we automatically enforce 0 for raw data is even more reason to remove the include 0 toggle (or at least disable it) because currently it does nothing when in raw data mode ...

<img width="790" alt="Screen Shot 2022-01-07 at 8 23 29 AM" src="https://user-images.githubusercontent.com/732541/148550201-0c998794-f5ba-488e-9ffa-6d8a56d66dc8.png">
<img width="781" alt="Screen Shot 2022-01-07 at 8 23 36 AM" src="https://user-images.githubusercontent.com/732541/148550203-b8c9a327-c111-4ca6-91cf-82711e6f167f.png">

**Comment by RoniRos** [comment]
Whether we end up keeping it or not, "include 0 in Y Axis" may not be immediately parsable to people.  I would prefer "Start Y Axis at 0".
-The terminology czar.

**Comment by krivard** [comment]
> include 0 for bar graphs (raw data), no 0 for line graphs. (And no separate toggle for including 0.)

I approve!

**Comment by ryantibs** [comment]
Great, I'm glad we converged! v3.1 tag is back on. 

@sgratzl Can you ensure your PR #1114 does the following:

- no toggle for including 0
- for line graphs, automatically scale to observed min/max 
- for bar graphs, automatically include 0 
- ensure that this is consistent across all COVIDcast and CTIS dashboards

Then I will approve it.
