### ISSUE TITLE
Remove some sources from export data tool

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1118]
I'd like us to consider removing some sources from the export data tool that are either obsolete or not used very much. In particular, the following ones: 

- Google Health Trends
- Google Symptom Surveys
- Composite COVID Cases & Deaths
- Statistical Combination (NMF)
- Quidel Inc. (Flu)

The rationale is that it's easier to skim through a small list than a big one, and I'd like to highlight the other sources

An alternative can be that we can hide them on initial load, but have a button saying "Show More Sources" that reveals the full list.

Tagging @sgratzl @capnrefsmmat @krivard who might have an opinion.

**Comment by sgratzl** [comment]
we would need to add a flag in the signal meta data indicator which signal should be hidden. I don't want to add the list of hidden sources/signals hard coded in this repository since any signal change will require to also adapt the code manually

**Comment by ryantibs** [comment]
Sure, that makes sense (adding a flag).

**Comment by krivard** [comment]
We're clear to just use the active/inactive flag for this -- only show sources with at least one active signal.

**Comment by ryantibs** [comment]
What Katie says should be the default view (show sources with at least one active signal).

If possible, I'd still like to implement my suggestion that can have a button saying "Show More Sources" that reveals the full list.
