### ISSUE TITLE
Graphs with "Show All Dates" don't show most recent date

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#1123]
**Actual Behavior:**

Currently, the [survey dashboard](https://delphi.cmu.edu/covidcast/survey-results/) shows graphs of data up to January 5th. But if I toggle the "Show All Dates" option on a graph, the graph only shows data up to January 4th.

**Steps to Reproduce the Bug:**

1. go to https://delphi.cmu.edu/covidcast/survey-results/
2. View the first graph on the page and see what the latest date is
3. Toggle "Show All Dates"
4. See what the latest date is now

**Expected behavior**

Both graphs should go up to the same date.

**Rating Scale (1 is minor, 7 is severe):** 2

**Context**

- Browser: Firefox 95

**Comment by sgratzl** [comment]
same reason as #1026 the meta data is reporting a different max date than what is actually available

**Comment by ryantibs** [comment]
I just checked, and this appears to be closed by #1127.
