### ISSUE TITLE
Extend limits of color scale

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1131]
(This should be the last item under v3.1!)

I think we're going to need to extend the limits of the color scale for the beehive & choropleth maps. Looking at cases right now, everything is dark red for the beehive map. Choropleth map is getting saturated in most of the south and southeast as well.

![Screen Shot 2022-01-12 at 8 58 05 AM](https://user-images.githubusercontent.com/732541/149154316-adc7a53b-f5de-4ec1-ac65-8102e8e64f5b.png)
![Screen Shot 2022-01-12 at 8 58 16 AM](https://user-images.githubusercontent.com/732541/149154318-e76fa5bc-1388-4def-a480-2bafc7ed7f1a.png)
 
Can we just add a color to the end of the scale to keep the visualization consistent with what we have for everything below the max value on the color scale? That way the new color would only help distinguish the values about the max. For example, dark purple.

Also while I'm here, can I ask for a reminder of how these scales are computed. Is it manual or data-driven? It appears to be different for state resolution vs county resolution, for the same indicator. But just to double check: it is constant across all views over time and locations, right? Say, as I scroll back arbitrarily far into the past, or zoom into a particular location, the color scale would remain the same?

**Comment by sgratzl** [comment]
its a data driven scale, 
see also https://github.com/cmu-delphi/www-covidcast/blob/709370f1f7de5cf9616d46570f52ab111af62eea/src/data/meta.ts#L58-L82

the basic range is defined as `[max(0, mean - 3 * stdev), min(10000, mean + 3 * stdev)]` e.g. for a per 100k signal like the cases

**Comment by ryantibs** [comment]
Ok, so as I understand it: 

- if I visit the dashboard tomorrow, this will change slightly, since the `mean` and `stddev` will change.
- but any given day I'm looking at the dashboard, it'll remain constant through all views: zooming into a particular location, or scrolling back to previous dates. 

Is that correct?

Separately from checking my understanding, I think we need to do a manual-hack to amend the cases color scale.  As I said, it's a constant dark red in a lot of places.  For example, here is the fix we can try: 

- keep the current color scale, so that the same colors span the "basic range" `[max(0, mean - 3 * stdev), min(100_000, mean + 3 * stdev)]`
- add a new color (try dark purple) to interpolate between the end of the basic range and the "extended range" `[min(100_000, mean + 3 * stdev), min(100_000, mean + 4 * stdev)]`

I chose `4 * stdev` somewhat arbitrarily; we could also try `3.5 * stdev` and see how each looks.  Sam, make sense and can you give it a shot?

**Comment by sgratzl** [comment]
> Ok, so as I understand it:
> 
>     * if I visit the dashboard tomorrow, this will change slightly, since the `mean` and `stddev` will change.
> 
>     * but any given day I'm looking at the dashboard, it'll remain constant through all views: zooming into a particular location, or scrolling back to previous dates.
> 
> 
> Is that correct?

yes and yes. 

re color scale: for signals that have a meaning of "the higher the better", e.g. https://delphi.cmu.edu/covidcast/indicator/?sensor=fb-survey-smoothed_wwearing_mask_7d we use a different color scale

in general, depending on whether high values are, we use one of the following color scales:
good: https://github.com/d3/d3-scale-chromatic#interpolateYlGnBu
bad: https://github.com/d3/d3-scale-chromatic#interpolateYlOrRd
neutral: https://github.com/d3/d3-scale-chromatic#interpolateBuPu

which color scales should we use for your extended areas?

**Comment by ryantibs** [comment]
Thanks for confirming the first part.  Re exception: We don't show any count signals in the dashboard atm, so I guess isn't in use right now.

Re color scale: thanks. Well high values for cases are definitely bad, so I'd like to add a dark purple as the extended color scale, to the right of the bad color scale. For example, we can just use the very right end of the "neutral" color scale for that value. I don't think this would be confusing, since we don't have any signals that we show right now under the "neutral" color scale.

**Comment by sgratzl** [comment]
original:

![image](https://user-images.githubusercontent.com/4129778/149355759-b274db67-1926-451b-8251-ae713c1d7c3e.png)
![image](https://user-images.githubusercontent.com/4129778/149355790-30c58faa-e8b5-4819-bc61-fb64001231b9.png)


4 * stdev version:

![image](https://user-images.githubusercontent.com/4129778/149355312-49550cd4-58bc-4f5f-ad86-02571c70c87f.png)
![image](https://user-images.githubusercontent.com/4129778/149355431-54f1c3ad-439a-46c6-8a7e-1d7ce3f1990a.png)


3.5 * stdev version:

![image](https://user-images.githubusercontent.com/4129778/149355518-7a4c9217-f67e-4326-90ac-885992a5ac54.png)
![image](https://user-images.githubusercontent.com/4129778/149355563-689bd05d-a130-4844-96a8-7ce485a36f7d.png)

**Comment by ryantibs** [comment]
Thank you Sam.  The 4x std error one is certainly an improvement over the original, and the better of the two options, but unfortunately it still very saturated in terms of the coloring, especially for states. 

Can we try 5x?

**Comment by sgratzl** [comment]
mean 5 * stdev:

![image](https://user-images.githubusercontent.com/4129778/149374026-920a3728-e2b9-4751-adbf-0c22b97b0740.png)
![image](https://user-images.githubusercontent.com/4129778/149374070-e5b363f2-e2dd-4fc5-b154-e95c873f1be0.png)

6:

![image](https://user-images.githubusercontent.com/4129778/149374147-6bfa3bec-a32e-4e92-8a9c-3ca981a3289e.png)
![image](https://user-images.githubusercontent.com/4129778/149374215-d9a142e1-64af-47c2-91b5-849546b203b1.png)

**Comment by ryantibs** [comment]
Excellent, thanks.  Let's go with 6x to give us some headroom for the weeks to come.
