### ISSUE TITLE
Quidel raw data availability seems misleading

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1137]
@jingjtang @krivard @RoniRos @sgratzl Check this out:

<img width="871" alt="COVIDcast  COVID Antigen Test Positivity Indicator Details 2" src="https://user-images.githubusercontent.com/732541/149958624-00ae8453-549f-48c0-b01d-3412b14422af.png">
<img width="1180" alt="COVIDcast  COVID Antigen Test Positivity Indicator Details 4" src="https://user-images.githubusercontent.com/732541/149958628-0b8281cb-0429-4083-ad1a-10d540ae706a.png">

There are long stretches of time where we have no raw data and yet there are smooth signal values available.  

I first thought this was a bug but now I think it's an artifact of the fact that we use a threshold of a count of 50 for raw signal availability, and yes for smoothed signals, we do geo-pooling if the count is 25 or higher and borrow from the parent state.

Anyway the result is visually quite confusing/misleading.  Can we add a small disclaimer below each of the Quidel time series graphs when in "Show Raw Data" mode, saying something like (paraphrasing): The way we do smoothing via geo-aggregation can result in a gross mismatch between raw signal availability and smooth signal availability.

**Comment by RoniRos** [comment]
In addition to the caveat/disclaimer, why not use the threshold of 25 for displaying the raw data, too?

**Comment by ryantibs** [comment]
That would require us recomputing and publishing the raw signals based on a new threshold of 25.  Which we could do, but that would not just be a dashboard change.

**Comment by ryantibs** [comment]
Definitely not for national.

For states, @jingjtang do we do geo aggregation for the state signals using national as the parent? If so, it could technically happen there too. Can you look into see how frequently we have a mismatch between state raw and smoothed signal availability?

For counties, it happens frequently. So I would say let's just implement it at the county level only, and wait until Jingjing responds to decide on states.

**Comment by ryantibs** [comment]
@jingjtang Can you confirm you got this?  I want to make sure this doesn't get lost.  Sam has created a PR to implement this, and I want to make sure that leaving the warning from state-level raw signals is not an issue.  Thank you.

**Comment by jingjtang** [comment]
@ryantibs @sgratzl No, we only do geo aggregation for county, hrr and msa. We don't do any geo aggregation for state, hhs, and national level data.
