### ISSUE TITLE
CPR hospital admissions for counties only

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1139]
We will soon have county-level hospital admissions signals in the API from CPR = community profile report.  

While this is technically supposed to be coming from the same data source as that underlying the HHS hospital admissions signals (I've checked this with CDC), for unknown reasons, there are disagreements at this point between the data published by these two sources.  This discrepancy, I'm told by CDC, should be resolvable though, and they're working on that.

Also, it should be noted that by my calculations the CPR signals will be 1 day more latent compared to the HHS signals (available at a 3-day lag, rather than a 2-day lag).

I would like the COVIDcast dashboard to show the CPR signal values for county-level hospital admissions, but still HHS for state-level and national hospital admissions.  This should be seamless and not require the user to change indicators, it would be under the "COVID Hospital Admissions" indicator.  But the data description should indicate clearly that it's actually coming from two different sources, and should warn that---at the moment---there is a discrepancy (sum of county counts do not add up to state counts) for unknown reasons, and we're working with the data stakeholders to fix that.

I believe this should affect the following: 

- When in "indicator mode" with indicator = hospitalizations, region = national, the choropleth map (as a toggle option way from beehive grid) should show CPR county-level signal
- When in "indicator mode" with indicator = hospitalizations, region = any given state or county, the choropleth map should show CPR county-level signal
- When in "indicator mode" with indicator = hospitalizations, region = any given state or county, the data table at the bottom should show CPR county-level signals
- When in "indicator mode" with indicator = hospitalizations, region = any given county, the time series graph should show CPR county-level signals

@sgratzl @RoniRos @krivard Any concerns with this plan?

**Comment by RoniRos** [comment]
What is your plan if/when we find out the source of the discrepancy, but it is not going to be corrected?

**Comment by ryantibs** [comment]
No plan, really. We keep the dashboard as-is, and just remove the line in the data descriptions us working on it with data stakeholders.

Very few graphics that I referred to above would be possibly problematic: only the county-level time series plot (which overlay county curves with warent state and national level curves in faint lines) and the table (which would compare indicator values, relative change, and spark lines across national, parent state, and counties).  

But mostly all the graphics would be coherent, since they would be comparing a signal from a signal data source to itself, either over time or over space.

**Comment by krivard** [comment]
this is probably going to need to be hard-coded, which is awkward and will reduce our ability to make quick or consistent changes in the future, but it seems worth it.

@sgratzl any ideas for how to specify this? do you want to try to extend the signals doc syntax for it, or handle everything within svelte, or some other options?

**Comment by sgratzl** [comment]
question regarding consistency:

> When in "indicator mode" with indicator = hospitalizations, region = national, the choropleth map (as a toggle option way from beehive grid) should show CPR county-level signal

so the map will show a different signal than the summary numbers and time series on top? The map itself doesn't have a separate description that would highlight that

> Very few graphics that I referred to above would be possibly problematic: only the county-level time series plot (which overlay county curves with warent state and national level curves in faint lines) and the table (which would compare indicator values, relative change, and spark lines across national, parent state, and counties).

yes the geo table for e.g. a county will have following entries:
 * national value
 * state value
 * county value
 * neighboring county value
 so national and state rows will have a different signal right?

for geo table of states it will have: 
 * national value
 * state value
 * all contained counties value
 with a similar inconsistencies.

for line chart as you mentioned in case of a county the lines will contain a similar mix:
 * national line
 * state line
 * county line
 * average neighboring county line

How do you wanna handle these inconsistencies? I assume both signals have at least the same unit?

**Comment by ryantibs** [comment]
Re the map and all inconsistencies that you point out: yes that's correct in all instances. These are only technically different signals between county and state/national, they're not fundamentally different signals. Meaning, they are really supposed to be measuring the same thing (so yes, in the same units) from the same data source. 

If we can put an emphasized line (bold or italics) in the data descriptor paragraph with an explanation, as I said, I think that will be sufficient for now.

**Comment by sgratzl** [comment]
blocked till API signal is available.

**Comment by ryantibs** [comment]
@sgratzl @krivard Hi guys! Long time no speak about this issue. 

I don't think this is blocked anymore, right Katie?

Sam, can we start this then? Thanks.

**Comment by krivard** [comment]
Yep:
```
$ curl -sL "https://api.covidcast.cmu.edu/epidata/covidcast_meta" |jq -c '.epidata | map(select(.data_source=="dsew-cpr" and .geo_type=="county"))[]' |head
{"data_source":"dsew-cpr","signal":"confirmed_admissions_covid_1d_7dav","time_type":"day","geo_type":"county","min_time":20210107,"max_time":20220220,"num_locations":3272,"min_value":0,"max_value":825.5714285714286,"mean_value":3.3437084,"stdev_value":12.5475417,"last_update":1645635075,"max_issue":20220223,"min_lag":3,"max_lag":391}
{"data_source":"dsew-cpr","signal":"confirmed_admissions_covid_1d_prop_7dav","time_type":"day","geo_type":"county","min_time":20210107,"max_time":20220220,"num_locations":3219,"min_value":0,"max_value":569.2346462295616,"mean_value":2.6698172,"stdev_value":5.5533145,"last_update":1645635079,"max_issue":20220223,"min_lag":3,"max_lag":391}
```
