### ISSUE TITLE
Weird behavior with Quidel signals

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1147]
I am getting extremely weird behavior when I move back and forth in between counties. E.g., going over to Santa Clara County shows an empty screen:

<img width="729" alt="Screen Shot 2022-01-21 at 11 55 27 AM" src="https://user-images.githubusercontent.com/732541/150568531-9c32958a-1f1b-419c-993a-9054d8a98b38.png">
 
but then toggling on "Raw Data" gives this:

<img width="677" alt="Screen Shot 2022-01-21 at 11 55 36 AM" src="https://user-images.githubusercontent.com/732541/150568621-914b5129-a9f7-43d2-ae44-08052d17ba24.png">

Furthermore, toggling back over to Allegheny County show this:

<img width="680" alt="Screen Shot 2022-01-21 at 11 55 51 AM" src="https://user-images.githubusercontent.com/732541/150568722-2f7cf602-42dd-488f-b84d-392285f717f3.png">

I will note that I've seen this weird behavior with the Quidel signal already before.  I've even seen something extremely eerie, where the dashboard appears to be changing the signal it's plotting right underneath my eyes (without any buttons being pressed!!).  I made a note of this on slack and tagged Brian/Joe several days ago, guessing it was a backend problem.

**Comment by sgratzl** [comment]
the requests have different response times causing that the line chart won't show up but the raw data one shows up

```
the related county query:
https://api.covidcast.cmu.edu/epidata/covidcast/?signal=quidel-covid-ag%3Acovid_ag_smoothed_pct_positive&geo=county%3A06001%2C06047%2C06069%2C06081%2C06087%2C06099&time=day%3A20210920-20220120&format=json&fields=value%2Cstderr%2Cgeo_value%2Ctime_value
is like 33s

while others like https://api.covidcast.cmu.edu/epidata/covidcast/?signal=quidel-covid-ag%3Acovid_ag_smoothed_pct_positive&geo=county%3A*&time=day%3A20220116&format=json&fields=value%2Cstderr%2Cgeo_value
is like 350ms
```

**Comment by ryantibs** [comment]
@krivard @korlaxxalrok Don't know if this escaped your attention but it appears to be more than a frontend issue. Please take a look. Thank you.

**Comment by krivard** [comment]
Though it does seem weird that we'd be querying `county:*` for  the explore-a-county page. @sgratzl is that the actual query for this page or did you pull it from somewhere else?

**Comment by sgratzl** [comment]
> Though it does seem weird that we'd be querying `county:*` for the explore-a-county page. @sgratzl is that the actual query for this page or did you pull it from somewhere else?

actual query, for the map it shows the county data along with its close neighbors. Since there is no easy way to determine the neighbors it loads all counties for a specific date. 

what took the longest was the "neighboring counties" in the line chart, since the direct neighbors are known the fips codes are directly queried.

**Comment by krivard** [comment]
Okay, so it sounds like we have options:

* Leave it as is and wait for faster responses with the upcoming epidata v0.4 release (maybe a month, will know more this afternoon)
* Temporarily disable neighboring counties in the line chart
* Temporarily use direct neighbors (which have known fips) for neighboring counties line chart

@sgratzl any reason to veto any of the above?

**Comment by sgratzl** [comment]
> Temporarily use direct neighbors (which have known fips) for neighboring counties line chart

this one is implemented and that is the slow one at least in my simple test:
```
signal: quidel-covid-ag:covid_ag_smoothed_pct_positive
geo: county:06001,06047,06069,06081,06087,06099 ... all neighobring fips
time: day:20210920-20220120 ... over a time range
```

**Comment by krivard** [comment]
Oh sorry, I totally blew the units interpretation on your description above. So fetching all counties is fast, but fetching 6 specific counties is slow?

Revised options:

- Leave it as is and wait for faster responses with the upcoming epidata v0.4 release (maybe a month, will know more this afternoon)
- Temporarily disable neighboring counties in the line chart
- Temporarily use client-side filtering for neighboring counties line chart (query all counties, but throw away everything except the fips you want)

**Comment by sgratzl** [comment]
> * Temporarily use client-side filtering for neighboring counties line chart (query all counties, but throw away everything except the fips you want)

to clarify for the line chart, I load a time range + multiple fips (neighboring). For the map, I load one date + all fips. So, for this option it would require to load all fips for a time range

**Comment by krivard** [comment]
Thank you. I did a quick check of pulling all fips for the 20210920-20220120 time range, and unfortunately it gives about the same response latency as your 33s result for pulling 6 fips for the 20210920-20220120 time range:

```
for i in 1 2 3 4 5; do time curl -sL "https://api.covidcast.cmu.edu/epidata/covidcast/?signal=quidel-covid-ag%3Acovid_ag_smoothed_pct_positive&geo=county%3A*&time=day%3A20210920-20220120&format=json&fields=value%2Cstderr%2Cgeo_value" >/dev/null; done

real    0m41.362s
user    0m0.095s
sys     0m0.054s

real    0m39.687s
user    0m0.100s
sys     0m0.047s

real    0m25.779s
user    0m0.081s
sys     0m0.067s

real    0m32.739s
user    0m0.095s
sys     0m0.054s

real    0m26.066s
user    0m0.113s
sys     0m0.037s
```

So we're down to 

- Leave it as is and wait for faster responses with the upcoming epidata v0.4 release (maybe a month, will know more this afternoon)
- Temporarily disable neighboring counties in the line chart

**Comment by sgratzl** [comment]
I can also query each country individually which should be fast. It is more of a workaround since it could also be that a country has 20 or more neighbors, resulting in 20 or more extra REST calls instead of just 1

**Comment by ryantibs** [comment]
I vote on trying Sam's workaround and seeing how it does. 

It looks like the max number of neighbors is 14 (according to this: https://www.howderfamily.com/blog/most-county-borders/, though of course who knows if that's authoritative), and the average number of neighbors is going to be much less than this.
