### ISSUE TITLE
Clicking on sparkline or time series lines changes date selection

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1159]
I often find myself wanting to click on the sparkline or time series line on the main dashboard and CTIS dashboard in order to change the current date selection.  I think that this is a relatively common feature I've seen in other dashboards.

@sgratzl Any reason this would be undesirable and/or hard? If not can we try it? Thanks!

**Comment by sgratzl** [comment]
technically possible. However, just by a single click might lead to a lot of wrong navigations. The thing is when you change the date, it won't only changes the selected date but also the window you are observing. That means if you click in the middle of the sparkline or line chart, the spartline and line chart will change and show a different window. 

I can play around with some options. Maybe a button in the tooltip fo the sparkline that allow you to navigate to it. Or we could use double-click to trigger the selection in this way.

**Comment by ryantibs** [comment]
Sure. I think navigating thru double clicking could be essentially as convenient as one click, and safer.
