### ISSUE TITLE
🔥  Surveys dashboard currently down

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#1160]
**Actual Behavior:**

The production, netlify-main, and netlify-dev instances of the survey dashboard are all failing to load. Console errors are variations on `Cannot read properties of undefined`.

Since we haven't had any new releases since Feb 2, I suspect this problem is related to the meta update from yesterday: https://github.com/cmu-delphi/delphi-epidata/pull/855

but I haven't been able to connect the dots so far. If you can help me narrow down which of those changes is causing the problem, it should be fairly straightforward to back it out.

**Steps to Reproduce the Bug:**

1. go to https://delphi.cmu.edu/covidcast/survey-results/
2. or https://dev--cmu-delphi-covidcast.netlify.app/survey-results/
3. or https://main--cmu-delphi-covidcast.netlify.app/survey-results/

**Expected behavior**

Site loads with no errors, or is robust to whatever errors do occur

**Rating Scale (1 is minor, 7 is severe):** 7 - blocking all usage for survey dashboard

**Context**

- Browser: Chrome Version 98.0.4758.80 / MacOSX 12.1; Firefox 97 / macOS

**Comment by sgratzl** [comment]
I have an idea and currently try to fix it
