### ISSUE TITLE
COVID Symptoms --> Symptom Searches

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#1166]
Very small request. I believe there is some google doc where this change gets made but I can't remember where to find it, sorry.

Can we change "COVID Symptoms ... on Google" --> "Symptom Searches ... on Google" for the name of the two google symptom indicators on the dashboard?

I think the latter is more informative/description (and since we have the specific broad categories in parentheses, we don't need to lead with "COVD" in the name).

**Comment by sgratzl** [comment]
see https://docs.google.com/document/d/1llv6xh8jMlmVv7WpyDSv4VgUpFAZQ6QjFUeRxxOinmk/edit#heading=h.ofzaumelgwng

**Comment by sgratzl** [comment]
please update it and then run this workflow:

https://github.com/cmu-delphi/www-covidcast/actions/workflows/update_gdocs_data.yml

![image](https://user-images.githubusercontent.com/4129778/157051199-aed8eb6e-a5ee-4878-8f1f-b4d3fd9f35c1.png)

**Comment by krivard** [comment]
Done! @ryantibs do you want this to go out immediately or wait for the next release?

**Comment by ryantibs** [comment]
If immediately is not a risk, then yes please. If it is a risk, then no problem to wait.
