### ISSUE TITLE
Assorted dashboard cleanup tasks [OKRF23-27]

### ISSUE THREAD

**Issue by carlynvandyke** [cmu-delphi/www-covidcast#1233]
- [ ] Remove top section (7-day averages and comparisons)
- [ ] Move COVID hospital admissions chart to top of page (above beehive map)
- [ ] Remove COVID cases from indicators table
- [ ] Replace JHU deaths (jhu-csse deaths_7dav_incidence_prop) with NCHS deaths (nchs-mortality deaths_covid_incidence_prop)

![covidcast updates 10192023](https://github.com/cmu-delphi/www-covidcast/assets/62626254/6d46cc74-afe6-4190-95d0-775c70487600)

**Comment by rlunde** [comment]
Please consult with @melange396 as you get started (the last item may be particularly tricky)

**Comment by melange396** [comment]
The two "tricky" parts of replacing the deaths signal are that:
* The old one had a daily issue frequency (as with all the other dashboard signals), but the new one is only issued weekly.  I thought graphing and plotting would need adjustments for this, but it appears week-level data is already supported in the dashboard webapp UI. 
* The new deaths signal is not provided at the national level.  Another issue was created to address this: https://github.com/cmu-delphi/covidcast-indicators/issues/1906.
