### ISSUE TITLE
Only color subcounties with a dense population

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#154]
The NYTimes does not color the entire county.  Instead, "Parts of a county with a population density lower than 10 people per square mile are not shaded"
<img width="583" alt="image" src="https://user-images.githubusercontent.com/1194662/83295293-b9b82c80-a1bc-11ea-8638-12ffc494bfd2.png">
This contributes to making the map less overwhelming.  We could consider doing something similar.  

We would need a list of subcounties that meet this density requirement.

**Comment by tildechris** [comment]
Closing this issue as obsolete.
