### ISSUE TITLE
Investigate hierarchical clustering for bubble charts when zooming

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#156]
Bubble charts often cause a lot of include, so @ryantibs suggested hierarchical clustering/zooming may help.

Mapbox appears to offers built-in support for hierarchical clustering: https://blog.mapbox.com/clustering-millions-of-points-on-a-map-with-supercluster-272046ec5c97

**Comment by tildechris** [comment]
Closing this issue as obsolete.
