### ISSUE TITLE
State name (abbreviations?) on Covidcast map

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/www-covidcast#167]
Suggestion that the Covidcast map (at least on the State level) label individual states (right now there are just a few cities labeled).  Comparison of Covidcast to Google maps below:

vv don't read into fact that labels are dark background, just due to a firefox extension
![Screenshot from 2020-06-05 12-00-38](https://user-images.githubusercontent.com/8422804/83898063-6564fd80-a724-11ea-9961-bec399b0086b.png)

![Screenshot from 2020-06-05 12-01-19](https://user-images.githubusercontent.com/8422804/83898068-685fee00-a724-11ea-8248-f81858c5c137.png)

**Comment by tildechris** [comment]
Closing this issue as obsolete.
