### ISSUE TITLE
Improve design of Official Reports tooltip

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#178]
Suggested by @RoniRos on Slack:
"In tooltip text, include all Official Reports statistics: Cases (date), Cases (7dav), Cases per 100,000 (date), Cases per 100,000 (7dav), Death (date), Deaths (7dav), Deaths per 100,000 (date), Deaths per 100,000 (7dav). "

Right now, this would take 6 API calls... so we'll need better API support if we want to do this.

**Comment by tildechris** [comment]
Closing this issue as obsolete.
