### ISSUE TITLE
Consider not showing data for regions with ratios based on less than 5 count

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#179]
@RoniRos says on Slack: 
"In sparse counties, a single death still registers as an extremely high death ratio, even after averaging over 7 days. Example: 1 death in Hamilton County, TX on May 24. As I argued before, I think that ratios based on a count that is <= 5 should simply not be provided, because they are more likely to mislead than to inform.  "     

Right now, the ratio API does not provide count.  This would be need to be supported by @krivard 's team to implement

**Comment by tildechris** [comment]
Closing this issue as obsolete.
