### ISSUE TITLE
Consider a single-location view

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#192]
This view would show all available signals for a single county, state, or metro area (or HRR?). It could show all signals in a single time-series plot, or in several plots (as with [Covid Act Now](https://covidactnow.org/us/pa?s=58173)). It should hide the rest of the map, but make it easy to return to it to select another location for closer study. Users may wish to use this detailed view to compare multiple locations; the simplest approach could be to let them use their browser functionality to open multiple tabs or windows with one location in each.

Challenges:
* Data support; fetching each signal in a separate API call would be slow. Support for a single multi-signal query is being pursued in cmu-delphi/covidcast-indicators#116.
* Y-axis labeling for the "one chart with everything in it" option. Signals measure different quantities with different units. Displaying 2 signals has an established solution of using the left vs right y-axis for labeling, but displaying more than 2 signals may require a more inventive approach. (Maybe no numeric labels by default, and hover a curve to display its labels?)

**Comment by sgratzl** [comment]
closing in favor of the new version
