### ISSUE TITLE
Alaska, Hawaii, Puerto Rico invisible when viewing by metro area

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#229]
This is not super urgent since switching to state mode makes everything clear, but in metro mode, the "floating" states (Alaska, Hawaii, and Puerto Rico) are invisible against the background, making what data they do have appear to be coming out of the middle of nowhere. The effect is worse in bubble mode.

<img width="891" alt="image" src="https://user-images.githubusercontent.com/1158666/88058127-096a0300-cb31-11ea-8300-043753543466.png">

<img width="891" alt="image" src="https://user-images.githubusercontent.com/1158666/88058195-1f77c380-cb31-11ea-867a-c05f687f33b1.png">

**Comment by tildechris** [comment]
Closing this issue as obsolete. Non-contiguous regions currently show in county view.
