### ISSUE TITLE
Design hotspots view

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#253]
Initial interviews suggest public health officials wish to know which locations are hotspots.  The modeling teams are working on this feature ( https://github.com/cmu-delphi/covidcast-indicators/issues/152 )

In the meantime, we could use a simpler metric like what the NYTimes does [NYTIMES Hotspots](https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html#hotspots):

<img width="621" alt="image" src="https://user-images.githubusercontent.com/1194662/88241754-141fb780-cc59-11ea-8bcc-32a09e449e91.png">

**Comment by sgratzl** [comment]
closing for now with the latest top10 view. Once we have a new measure what a "hotspot" defines we should open a new issue
