### ISSUE TITLE
Auto adjusting Y scale in Time graph makes it difficult to interpret absolute severity   

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/www-covidcast#288]
Currently, the Y scale in the time graph is auto-adjusting, so as one clicks on different locations, or even loads more weeks, the scale adjusts to accommodate the data.  This is of course helpful for seeing relative trends over time, but it also makes it difficult to know the absolute severity of the values, e.g. is 15 per 100,000 a lot or a little?  (Answer: for deaths it's a lot, for cases it's quite moderate.  For tests?).  Same for Doctor Visits and Hospital Admissions.  For Google Search it's even more problematic, because the scale is completely arbitrary.

Could we find a way to convey a sense of severity, either absolute or relative to other locations? 

Here are some very raw ideas:

1. Add some horizontal lines/ticks on the chart that correspond to well known levels, like NYC at its peak? (that would be way off the chart in most cases, so will require "lightening" break icon.  Are there any "base levels" we can use?   Like thresholds used for moving from "red" to "Yellow" to "green" state?   For Doctor Visits and Hospital Admissions, we could use historical flu levels.

2. Indicate the ranking of the current location relative to other locations of the same type, based on the currently visible Area Under the Curve, e.g. "In this time period, Ohio ranked 14th highest in Cases per 100,000 people among the 50 states" or "In this time period, Allegheny County, PA ranked in the bottom third in Deaths per 100,000 among 650 urban counties."

3. A simpler variation on (2) above is to indicate the approximate rank by color or some other designation.

None of these sound great to me, perhaps you all will come up with better solutions. 

This problem becomes even more pronounced in the new location-centric view, where multiple indicators are shown at the same time.  Each "Indicator" should have its own indication of severity, either absolute or relative to other locations.

**Comment by dlaliberte** [comment]
We could color the background of each chart with horizontal bands or a color gradient that corresponds to the colors on the map.

**Comment by sgratzl** [comment]
closing with new version which has a toggle to switch between zero based on rescaled version
