### ISSUE TITLE
Optimize bubble sizes for cases/deaths per 100K

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#315]
@ryantibs:  "The bubble sizes for cases and for deaths appear to have been optimized nicely (I like the way the map looks).  I think the bubble sizes for cases per 100k and deaths per 100k should be optimized similarly (made a bit smaller), because the map looks too crowded.  Particularly for cases per 100k. 

Should we set a maximum bubble size and a maximum spike size?   In the same way we set a maximum color for red.  Otherwise we get something like what we see in deaths per 100k: a massive bubble that covers a good part of Texas.  This one is more of a question than a suggestion."

**Comment by tildechris** [comment]
Closing this issue as obsolete.
