### ISSUE TITLE
consider using different color scales for different signals

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#323]
It would be great if there would be different color scales (besides the yellow to red) to better visually separate different signals. 

since we would eventually run out of colors we would need to reuse some color scales, tho. 

https://github.com/d3/d3-scale-chromatic#sequential-single-hue
https://github.com/d3/d3-scale-chromatic#sequential-multi-hue

**Comment by tildechris** [comment]
Closing this issue as obsolete. We currently do two color schemes, up = bad and up = good.  We can consider others in the redesign project.
