### ISSUE TITLE
Consider creating new SWPA mode

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#350]
We need a new mode to support viewing finer levels-of-detail in SWPA for our public health officials.

To do this, we need:

- [ ] A new mode that is a map for HRR 357 (the hospital referral region of Pittsburgh).   This region includes Allegheny County and (parts of) counties nearby.

Helpful links:
- HRR geographic boundaries https://atlasdata.dartmouth.edu/static/supp_research_data#boundaries
- Zip-code crosswalks https://atlasdata.dartmouth.edu/static/supp_research_data#crosswalks

- [x] Shape files for zip5 and neighborhoods/municipalities within Allegheny County

**Comment by tildechris** [comment]
Closing this issue as obsolete.
