### ISSUE TITLE
Consider Alerts and Daily Updates feature

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#360]
**User story**

• An “Alert” system.  We heard from Debra Bogen that she wants to be smacked in the head with the data.  We could imagine building a report system, where users can subscribe to various reports for regions they care about (e.g. if there is a significant change in an indicator, we send an alert).  These reports could be sent by email or even text message.    This would drive traffic to our site and not let people forget about us. 

• A “Daily Update” email.  Similar to the above, we could allow people to subscribe to a daily update for a given location that goes beyond alerts.  The update would contain the latest data about the locations they care about, with tables, visualizations, and small multiples embedded in the email.  This could be a script that runs every morning, generates the emails, and sends them out.  This would also drive traffic to our site.

**Comment by tildechris** [comment]
Closing this issue as obsolete.
