### ISSUE TITLE
Future steps - visualizing COVID prevention measures & enforcement

### ISSUE THREAD

**Issue by tgildengers** [cmu-delphi/www-covidcast#365]
<A clear and concise description of what feature you are missing.>

It would be great if there was a way to visualize how strictly policies are enforced.

**User story**

A lot of the time, my family will go out for a walk after dinner, and maybe stop by a store for ice cream. Even though mask wearing, distancing markers, and customer limits are common, we can't figure out ahead of time how well people are sticking to those limits. Since my mom is immunocompromised, it's not really safe to go somewhere if we don't know what it's going to be like.

**Additional context**

N/A

**Comment by tildechris** [comment]
Closing this issue as obsolete.
