### ISSUE TITLE
link to data supporting masks from surveys and website

### ISSUE THREAD

**Issue by tgildengers** [cmu-delphi/www-covidcast#366]
It would be neat if there was some way to encourage people to follow prevention measures after they interact with the website. This could involve follow-up to surveys recommending the behavior, showing data to persuade for the behavior, or maybe making a comical follow-up like an animated gif that promotes mask wearing/photo of local icon like Dippy wearing a mask.

**User story**

When I see people outside it seems random whether they wear a mask or not, and it would be nice to encourage mask wearing more.

**Additional context**

**Comment by tildechris** [comment]
I considered adding a "learn more about the efficacy of wearing masks", link but I think we should wait until we have published our study on causal impact.

**Comment by sgratzl** [comment]
wontfix
