### ISSUE TITLE
Tracking people who wear masks

### ISSUE THREAD

**Issue by ggoslin** [cmu-delphi/www-covidcast#368]
It would be great if ...

One of the drop down options was the number of people who wear masks in a certain location. This way, if somebody could make a decision on whether to go somewhere based on the likelihood that people were wearing masks. Collecting this information could involve adding a question on platforms such as Facebook. The data could be displayed as one of the drop down options on the map.

Having information about mask wearing will allow people to make decisions with information that impacts them directly, and it may cause some people to avoid certain areas that they otherwise would have visited.

**Comment by sgratzl** [comment]
in the upcoming version there will be a new signal `People Wearing Masks`

https://cmu-delphi-covidcast.netlify.app/?sensor=fb-survey-smoothed_wearing_mask&level=county&date=20201007&signalType=value&encoding=color&mode=overview&region=42003


![image](https://user-images.githubusercontent.com/4129778/95716357-a6899300-0c6b-11eb-82fe-2fb23d56301c.png)

**Comment by ggoslin** [comment]
Wow! That looks fantastic! Thank you for sharing!

**Comment by tildechris** [comment]
This is implemented.
