### ISSUE TITLE
Able to look at similar schools and their outcome

### ISSUE THREAD

**Issue by ggoslin** [cmu-delphi/www-covidcast#369]
It would be great if ...

Each school had certain defining factors about them. For example, whether they were online or not, how many students, the number of cases in the area, etc. Then, when you searched up a school through the search function, the most similar schools would be highlighted along with links to websites that cover what happened at that school. Maybe you would be given a list of schools in their order of relevance, and then they would be marked with a black dot on the map.

Having this kind of information would give both school administrations and students a chance to know what to prepare for and expect in the future.

**Comment by tildechris** [comment]
Unfortunately, I'm not aware of a good data-set that would track this.  NYT does this for some colleges, but I haven't seen any on a primary or secondary level.

If we find a good data source, we can consider reopening.
