### ISSUE TITLE
Chat feature

### ISSUE THREAD

**Issue by ggoslin** [cmu-delphi/www-covidcast#370]
It would be great if ...

There was a public chat feature on the website. Users would have the ability to ask one another questions about exercising, food options, and even mask making during this pandemic. Furthermore, there could even be a public health official on the chat for a certain time frame to answer questions. The chat should be accessible 24/7, but it should not take up permanent space on the screen (users allowed to close the chat).

People can connect with others about questions they have and discover solutions that a YouTube tutorial cannot give. Furthermore, the users would also have access to a professional medical expert to answer any health-related questions.

**Comment by tildechris** [comment]
This is a neat idea, but the resources required to implement and moderate such a system make this infeasible.
