### ISSUE TITLE
Unable to see state/metro area/country border lines

### ISSUE THREAD

**Issue by ggoslin** [cmu-delphi/www-covidcast#392]
**Actual Behavior:**

When I am scrolling around at the map, particularly the data for Hospital Admissions, the border lines for the metro areas can be unidentifiable. If there is no data available for a specific location, then there is no distinguishing color to separate it from a neighboring area. State borders are unclear, unless there is data in the counties on the perimeter of the state. Otherwise, one state can blend right into another. Moreover, the blank color for the areas with not data is the same color as the background, so I cannot tell where the country ends and the background starts.

**Steps to Reproduce the Bug:**

1. Go to: https://dev--cmu-delphi-covidcast.netlify.app/?sensor=hospital-admissions-smoothed_adj_covid19&level=msa&date=20200820&signalType=value&encoding=color&mode=overview&region=42003
2. Scroll around the map, and look at areas where not all of the data is available. Try to identify metro areas and states.
3. Pan over to an area where no data is provided, and the background starts. I cannot _easily_ identify the border.
4. Zoom all of the way out. The state, metro area, and country border lines are unclear in some areas with no data.

**Expected behavior**

I expected all of the metro areas to be outlined in a dark grey. There are already white boarders, so we do not need to take into account for any extra space. Furthermore, I know that when an area is selected, the border becomes bold and black, but it would still stand out compared to the thinner grey outline. The metro area outlines would also provide the outline for the country.  

**Screenshots**

![Screenshot 2020-08-26 at 9 25 17 PM](https://user-images.githubusercontent.com/68612840/91375929-ed214c00-e7e9-11ea-8e4d-1b66ececf176.png)

**Rating Scale (1 is minor, 7 is severe):**

1...Not necessary for the functionality of the map. It is just hard to navigate in some areas.

**Context**

- Browser: Chromebook, Google

**Additional context**

The dark colors used for the metro areas makes it hard to see the light colored border lines.

**Comment by tildechris** [comment]
I believe this issue has been adequately addressed.  Closing.
