### ISSUE TITLE
simplify date change

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#396]
Roni:

> I need a way to change the date more directly than by pulling down the calendar. Can you let me grab any of the red vertical bars on the small multiples and move it right or left? And/or by clicking anywhere on the time line in one of the small multiple?   Also use the left-right arrows? 

**User story**

**Additional context**

**Comment by tildechris** [comment]
I believe this use-case has been presently addressed, and we will make sure that it remains easy to change context dates in the redesign.
