### ISSUE TITLE
Line graphs should be clear when there are missing values

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#402]
**Actual Behavior:**

@RoniRos in #covid-19-visualization:  "Adam Perer as per the discussion earlier today and your request for an example:  Cloud County, KS, DV signal, 7/19 datapoint should be missing ("NA"), as are 4/29 thru 5/1.  Yet both the small multiple and the bigger time plot draw a straight line thru the NA datapoints."
**Steps to Reproduce the Bug:**

1. go to https://dev--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20200824&signalType=value&encoding=color&mode=overview&region=20029

**Expected behavior**

The lines should be "broken" when there is missing data.

**Screenshots**

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/1194662/91595850-311f6880-e932-11ea-805d-7d6fbc95c9c9.png">

**Rating Scale (1 is minor, 7 is severe):**

5

**Context**

- Browser:

**Additional context**

**Comment by dlaliberte** [comment]
If we know that a value is missing for some time, then it could have an explicit null value, which we can use to break the line (in Vega Lite), and also to display separated individual points when they happen to be disconnected on both sides (with null values before and after).

If we don't have these explicit null values already in the data, then we would have to add them, either before starting the chart generation, or possibly as a transformation done by the chart generation, knowing the expected frequency.  There could be some special cases with missing data at the beginning and end of the time range.   Ideally, we would know what the total time range is such that missing values at the beginning or end will therefore be known to be missing.  

Other ways to visualize missing data are possible, besides simply leaving points disconnected.    Here is one paper on the subject:   https://cmci.colorado.edu/visualab/papers/song_VIS_2018.pdf
