### ISSUE TITLE
Latest date available in line graph is not available in calendar pulldown menu 

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/www-covidcast#406]
Aug 29 is currently (as of Aug 30 1:40pm) available for both FB signals and for 'combined', but the calendar pulldown menu is only available till Aug 28 even when any of these signals are selected.

https://deploy-preview-403--cmu-delphi-covidcast.netlify.app/?sensor=fb-survey-smoothed_hh_cmnty_cli&level=county&date=20200828&signalType=value&encoding=color&mode=overview&region=OR

Rating Scale (1 is minor, 7 is severe):  4  (cannot display map of the latest date available)

**Context**

- Browser:

**Additional context**

**Comment by tildechris** [comment]
@RoniRos from a visualization perspective, if there's not a signal available for the current date, it currently will take you to the latest date.  For example, in currently it looks like "Doctors Visits" have data only to Oct 3., but we have more recent signals from most others.

Would it make more sense to default the map from "Doctors Visits" to Cases or Deaths?

**Comment by capnrefsmmat** [comment]
See #279 for context on the default map choice. We wanted to highlight our unique data sources, and Doctor's Visits is a key one, but yes, there are some disadvantages to the choice. We could be convinced to switch.

**Comment by RoniRos** [comment]
What he (capnrefsmmat) said. ;-)

**Comment by tildechris** [comment]
Closing this as obsolete since we'll be changing the default view in the redesign and the "latest-date available" issue shouldn't be an issue anymore.
