### ISSUE TITLE
Coordinate gray line mouseover between small multiple indicators

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#415]
It would be great if when users highlight a date using small multiples, the same date is highlight in all indicators with the gray bar. 

**User story**

 This will make it easier for users to compare indicators for a specific date.

**Additional context**

<img width="467" alt="image" src="https://user-images.githubusercontent.com/1194662/91993105-fab36600-ed02-11ea-94c7-a0ca1ef16b5f.png">

**Comment by dlaliberte** [comment]
I think the line between the small multiples is this coordinated gray hover line :).

I wonder if we might get better performance and less jittery display with one view that may look identical to the separate views, or not.  This is the idea in #192, I suspect.
