### ISSUE TITLE
Automatic way of picking bubble/spike sizes (and colors) for cases and deaths

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#421]
Currently we have a custom size scale for bubble/spike maps for a total of 8 views: {cases, deaths} x {incidence, cumulative} x {counts, rates}.  (The color scale is custom here too, I believe.)  In some cases, it looks good in the default map zoom; in others, it doesn't: I don't find the bubbles or the spikes are very readable. 

Look at, for example: cases, cumulative, rates. The bubbles are too big for me in the default view (I'm viewing on a 13 inch MacBook), and the map is totally crowded (and the color scale is off too: the map is all dark red).

Can we figure out a good way to set sizes (and colors) automatically for these 8 combinations? Otherwise, we have to maintain 8 hand-tuned scales, which is laborious. Tagging @adamperer @sgratzl, but maybe Adam has ideas for others who could work on this (it seems to be a pretty self-contained project). 
 
To throw out an obvious idea, I would start by defining them based on quantiles (over historical data, just like we do mean +/- 3 standard deviations based on historical data, for the color scale in all other indicators).  This seems to be the most natural place to start.

**Comment by tildechris** [comment]
Closing as obsolete.  We're going to revisit showing bubbles or spikelines in the redesign, but my current opinion is that both have limited utility.
