### ISSUE TITLE
Domain-dependent color scales for Cases and Deaths

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#435]
**User story**

In v1.7, Case/Death Counts use a log color scale, Cases/Death Ratios per 100k use a linear color scale.  Our users are used to this (e.g. #434) but it doesn't make sense.   @RoniRos suggests to find a more principled solution that also incorporates some domain-dependent (not just data-dependent) notion of what it means for some value to be ‘high’ or ‘low’, and volunteered to lead this initiative.

**Comment by ryantibs** [comment]
Closing this because I think this is a long gone issue at this point. If I'm wrong, then somebody can tell me and we can reopen it.
