### ISSUE TITLE
fine tune bubble/spike scaling

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#451]
follow up from #416 to find a better scaling logic than:

```js
const SHRINK_FACTOR = 0.75;
const zoom = Math.pow(2, (current - base) * SHRINK_FACTOR);
```

in addition, the zoom factor is limited such that the bubbles have at most a radius of 50px and the spike height is at most 100px. 

> The parameters in ( https://deploy-preview-446--cmu-delphi-covidcast.netlify.app/ ) seem like a big improvement over what we currently have, so I'd love to see this make the next release (demo on Tuesday) and we can perhaps fine tune them further moving forward.

_Originally posted by @adamperer in https://github.com/cmu-delphi/www-covidcast/pull/416#issuecomment-694421283_

**Comment by tildechris** [comment]
@sgratzl do you have a proposal for better scaling logic?

**Comment by sgratzl** [comment]
no, I don't, my latest proposal is the one currently implemented. It is also related to issues like https://github.com/cmu-delphi/www-covidcast/issues/421 and https://github.com/cmu-delphi/www-covidcast/issues/435

**Comment by tildechris** [comment]
Closing as obsolete.  My current opinion is that bubble/spikes have limited utility and we may leave both out of the redesign.
