### ISSUE TITLE
Mobile compare mode

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#456]
atm the compare mode is not tested nor tuned for mobile experience. tho I'm also not sure how to transform the current layout such that it works on mobile

**Comment by sgratzl** [comment]
the current version of the region details tab supports comparing regions and is mobile friendly: https://dev--cmu-delphi-covidcast.netlify.app/?sensor=indicator-combination-deaths_7dav_incidence_num&level=county&date=20201011&signalType=value&encoding=color&mode=single&region=42003&compare=36001

**Comment by Letsgohyde** [comment]
Hey @sgratzl is this work still on-going? Some design feedback on the values. 
<img width="425" alt="Screen Shot 2021-02-03 at 12 32 40 PM" src="https://user-images.githubusercontent.com/7318770/106805959-350b9100-661c-11eb-81a5-0c0fd0078a70.png">

Currently on mobile the values wrap and have a very harsh outline.

**Proposed design**
Single selection:
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1984%3A35121

Multiple selection chips: 
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1984%3A35154

Gif of interaction: 
![REGION DETAILS : COMPARE MODE : INPUT STYLES](https://user-images.githubusercontent.com/7318770/106808501-51f59380-661f-11eb-9805-026113514c0a.gif)

Let me know if you have any questions :)

**Comment by sgratzl** [comment]
> Hey @sgratzl is this work still on-going? Some design feedback on the values.

Haven't worked on it for a while and since we are going to change the overall design, I don't know whether it make sense to start now.

**Comment by Letsgohyde** [comment]
Roger that, let me know when if and when this gets picked up :)

**Comment by sgratzl** [comment]
closing since the single view has been removed
