### ISSUE TITLE
Download CSV: 500 Internal Server Error

### ISSUE THREAD

**Issue by kenneth-lee-ch** [cmu-delphi/www-covidcast#458]
**Actual Behavior:**

When I tried to download a CSV about search trends (google) from [EXPORT DATA](https://dev--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20200914&signalType=value&encoding=color&mode=export&region=42027). It throws a 500 internal server error. Maybe the server is overloaded. 

**Steps to Reproduce the Bug:**

1. I changed the following download settings:

data source: ght
signals: Search Trends (google) 

2. Then, click on "CSV"

**Screenshots**
![Screenshot 2020-09-18 at 8 42 52 AM](https://user-images.githubusercontent.com/24616330/93618303-ed95a880-f98b-11ea-9126-7dbb2917c945.png)

**Context**

- Browser: Chrome

**Comment by sgratzl** [comment]
can we close this issue now?

**Comment by capnrefsmmat** [comment]
I can confirm the fix in https://github.com/cmu-delphi/covidcast-csv-server/pull/15 is deployed, and your code in #468 should prevent users from seeing this problem, so yes.
