### ISSUE TITLE
EPIC: Alerts

### ISSUE THREAD

**Issue by ejfox** [cmu-delphi/www-covidcast#469]
# User story

I am a public health official for Allegheny County in Pennsylvania. I check the dashboard as often as I can, but I don’t want to miss anything important. I am on the lookout for spikes in doctor’s visits related to COVID because I understand that is an early warning sign for the resurgence of an outbreak. 

I want to be alerted if there is a rise in Doctor’s Visits in Allegheny County or any of the surrounding counties (Butler, Armstrong, Westmoreland, Washington, or Beaver counties)

I want my alert to come in the form of a text message at 9AM anytime Doctor’s Visits in the areas I care about increase. 

#### “Subscribe to alert” screen / mode
I am going to go to the map and see a button that says “Subscribe to data alerts” - I click on that and I am taken to a new screen that explains what alerts are and how I might find them useful. 

#### Choosing an alert method 
Below the explanation, there are buttons for me to decide how I would like to receive the alert (Email or Text) and I choose text. 

#### Gaining user trust
I want to know who I am giving my phone number to and that they won’t be texting me too often or about other things I don’t care about, but there is some text explaining this is from CMU and this number won’t be shared and will only be used for COVIDcast alerts, and is easy to unsubscribe from.

#### Choosing an alert
Once I select how to receive my alert, I go to a “choose alert” screen. It gives me some examples of different useful alerts and explains what they are looking for and how they can be used. I choose “Increase in Doctor’s Visits” as my alert. 

#### Alert confirmation
The site confirms that my alert has been created and sends a text message to my number that tells me I have been subscribed. 

I leave the page and forget that I set an alert.

#### Receiving an alert
A few days later I receive a text message. It reminds me that I set an alert using COVIDcast and tells me that doctor’s visits have increased by X count and Y percentage and gives me a link to the COVIDcast site so that I can see it for myself. It also reminds me that I can unsubscribe by saying “STOP” over text or deleting the alert on the website. I click the link in the text and go to the COVIDcast site and begin clicking around at my county and neighboring counties to get more information.

**Comment by ejfox** [comment]
## Tooling
After looking at a few ways to provide notifications, it looks like [notifme-sdk](https://github.com/notifme/notifme-sdk) is the most robust, and provides the most options in terms of delivery from SMS to email. This allows alerts to be sent from a node script as simply as 

```
const NotifmeSdk = require("notifme-sdk").default

const notificationRequest = {
  email: {
    from: 'example@example.com',
    to: 'example@example.com',
    subject: 'COVIDcast alert: threshold crossed',
    html: '<b>Metric: </b> value',
    replyTo: 'replyto@example.com',
  }
}

const notifmeSdk = new NotifmeSdk({
  channels: {
    email: {
      providers: [{
        type: 'sendgrid',
        apiKey: 'SENDGRID-API-KEY'
      }]
    }
  }
}) 
```

## Architecture questions
When a user "creates" an alert, is that "unique" alert tied to that user?

Or does a user simply subscribe to a pre-configured alert? 

I think it makes much more sense, when a user creates an alert, that it is added to a pool of "shared" alerts that any other user can "subscribe" to. This will also make it easier for architecture and caching when multiple users create the same alert. 

One can also imagine a two-tier system, where qualified researchers could create alerts, and the general public could simply subscribe to alerts from a list of those created by other users (and organized by different needs). There could also be "featured alerts" that are designed for a general audience or for specific use cases.

**Comment by adamperer** [comment]
Figma containing the sketches above:  https://www.figma.com/file/QHWVg6ieuyInmsTzWDNYVZ/COVIDcast-Alert-UI?node-id=0%3A1

**Comment by tildechris** [comment]
Closing this as obsolete.  Alerting is hard to do well, and we don't currently have plans for a general alerting system like this in the next few months.  We can revisit need in the future.
