### ISSUE TITLE
Missing Data on Small Multiples

### ISSUE THREAD

**Issue by ggoslin** [cmu-delphi/www-covidcast#470]
**Actual Behavior:**

There seems to be a lack of information within the small multiples graphs. More specifically, the “COVID-19 Test Positivity (Quidel)” graph seems to have an abrupt start to the graph halfway through the chart. Since there is no line to indicate that there was information prior to June 11, it is unclear whether the data is intentionally missing or simply unavailable. Furthermore, “COVID Hospital Admissions” graph appears to have an incomplete set of data. Abbeville County, SC has blank areas along its line, and without a solid line to analyze the charts, the compare function is not useful.

**Steps to Reproduce the Bug:**

1. go to https://dev--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=msa&date=20200625&signalType=value&encoding=bubble&mode=overview&region=42003&compare=45001
2. Within the small multiple graphs, scroll down to “COVID-19 Test Positivity (Quidel)” and “COVID Hospital Admissions.”
3. There seems to be an incomplete set of data for these two charts

**Expected behavior**

I expect there to be a consistent line representing the data for each chart. If for the “COVID-19 Test Positivity (Quidel),” there is no data until June 11, then I think there should be some indication that no data is available for the date, or the graph should be adjusted, so the x-axis starts on June 11. Furthermore, it is very hard and difficult to analyze the “COVID Hospital Admissions” graph, the data abruptly stops for Abbeville County, SC. If this was intentional, then a note should be provided. Otherwise, it appears that the system glitched out for just days at a time.

**Screenshots**
![Screenshot 2020-09-23 at 11 05 32 PM](https://user-images.githubusercontent.com/68612840/94097956-8cd7f700-fdf5-11ea-89c8-18d18ae70809.png)

**Rating Scale (1 is minor, 7 is severe):**

4...the information can still be found on the map, but it is not displayed on the graph

**Context**

- Browser: Chromebook, Google

**Additional context**

If the gaps are intentional, it is unclear what they are supposed to indicate. If data is missing, then the blank data could be filled in with the average percent (this line would be represented in a different color).

**Comment by ggoslin** [comment]
Those are great ideas! You could even just have a small disclaimer at the top of the chart saying that all gaps are intentional.

**Comment by dlaliberte** [comment]
Related problems: 

- There is sometimes missing data such that, when you hover over the gap, tooltips show a 0 value.   
- In the detail view, hovering over missing data shows the nearest point with data.  This is after my change in https://github.com/cmu-delphi/www-covidcast/pull/588.  See https://deploy-preview-588--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201019&signalType=value&encoding=color&mode=overview&region=08065
- Isolated points, with no data on either side to connect to, are invisible unless you can find them by hovering.  Note that isolated points would have gaps on both sides, so if we render them as points not connected on either side, we would want to avoid obscuring them with a background field of gray.
- Some signals have "No data available" which is similar in some sense to signals with partially missing data, so the styles ought to be consistent.

**Comment by dlaliberte** [comment]
I have a way of detecting and drawing isolated points.

Not showing tooltips for missing values seems more difficult than it should be.  Maybe using a tooltip encoding will help, if we can make it conditional.

With more than one series in a chart, they probably have different gaps, so coloring the background won't work so well.

**Comment by dlaliberte** [comment]
Regarding the tooltips in the small multiples that is displayed for missing data, there is some difference between the small multiple charts and the DetailView charts such that the tooltips are not shown for missing data in the DetailView but they are for the small multiples.    I haven't found it yet, but @sgratzl, I bet you know.

**Comment by sgratzl** [comment]
I assume it is related to https://github.com/cmu-delphi/www-covidcast/pull/566

**Comment by dlaliberte** [comment]
The showing of tooltips in small multiples for missing data appears to be unrelated to my changes, since it is happening even in the [candidate release](https://deploy-preview-581--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201019&signalType=value&encoding=color&mode=overview&region=42003&compare=08065).  So it should be possible to fix that separate from my changes (in #588), and then I will be less confused :).

**Comment by dlaliberte** [comment]
I figured out why tooltips were showing with null values displayed as 0.  Fixed by #588. 

To visualize the undefined or unavailable data, we could show a special icon along the x axis in the range of each gap.  This is analogous to the idea of visualizing clipped data on the top of a chart.
