### ISSUE TITLE
inefficient use of space in compare mode

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#472]
the top right corner in compare mode is blank which seems unnecessary. 

![image](https://user-images.githubusercontent.com/4129778/94126486-f7218380-fe57-11ea-8583-b8605d26879b.png)

it makes sense to remove the search bar which was there in non compare mode but right now it is a just a white spot.

**Comment by tildechris** [comment]
Closing as obsolete as compare mode will be changed in the redesign.
