### ISSUE TITLE
use d3-scale + .ticks function to compute legend ticks

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#479]
atm. the ticks are manually set (0,25,50,75,100) percent however that ends up with ugly values. One option might be to use d3-scale .ticks function which has measure for providing "nice" values.

https://github.com/d3/d3-scale#continuous_ticks

**Comment by dlaliberte** [comment]
I'd be happy to work on this.

**Comment by sgratzl** [comment]
note it is not about vega charts but about the color scale ticks of the map:

**Comment by sgratzl** [comment]
closing since there classic map and its legend is outdated
