### ISSUE TITLE
consider adding a design framework

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#481]
to simplify more complex widgets it would be great to have a design framework such as material-ui, bootstrap, ant design, ... that is providing those basic widgets. 

e.g. https://github.com/bestguy/sveltestrap or https://sveltematerialui.com/

However, that would imply a major design change.

**Comment by tildechris** [comment]
@sgratzl how disruptive do you think it would be at the moment to include a framework?  Is it something that we can add piecemeal e.g. one widget at a time, or is it a big overhaul?

If the latter, my opinion is that we should wait until we're undertaking a larger redesign.

**Comment by sgratzl** [comment]
most frameworks these days should be isolated without changing default styles. But I agree that this should be part of some larger redesign in which we choose a framework and adapt it to our needs.

**Comment by tildechris** [comment]
Sounds good. I don't have an opinion on either of the two libraries that you mentioned (Bootstrap vs. Material), but yeah, we'll have to think about the design language that we want to use.  @Letsgohyde - can you start thinking about the overall design language that we should be moving towards?
