### ISSUE TITLE
update default static social media preview image

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#489]
atm it is hard coded to be https://covidcast.cmu.edu/images/covidcast-900x600.png

![image](https://user-images.githubusercontent.com/4129778/94135720-22aa6b00-fe64-11ea-8c0e-790c69029e49.png)

but this screenshot is pretty outdated

**Comment by dfarrow0** [comment]
Thanks for the super-detailed instructions @sgratzl :)

**Comment by sgratzl** [comment]
since covidcast is now embedded in the main website, this repo/covidcast cannot do much about social media previews. Instead it has to be handled in www-main.

**Comment by tildechris** [comment]
Closing in favor of https://github.com/cmu-delphi/www-main/issues/238
