### ISSUE TITLE
update default static preview image description?

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#490]
current text: 

title
> Home - COVIDcast - Delphi Research Group - Carnegie Mellon University

description:
> Carnegie Mellon's Delphi Research Group has partnered with numerous organizations, including Facebook and Google, to track COVID-19 and better forecast its spread at the county level.

**Comment by tildechris** [comment]
I think there's two items here:

1. What should the main HTML title be
2. What should the preview image alt-text be?

I think both should be shorter.  I think the main title could just be "Delphi COVIDcast" and the preview text is "COVIDcast tracks and forcasts the spread of COVID-19. By Carnegie Mellon's Delphi Research Group."  I think we should review with Spencer.  I'll take this up with him and let you know.

**Comment by sgratzl** [comment]
since covidcast is now embedded in the main website, this repo/covidcast cannot do much about social media previews. Instead it has to be handled in www-main.

**Comment by tildechris** [comment]
Closing as per Sam's comments.  Let's launch the redesign and I'll follow-up with the leads on if the description should be updated.
