### ISSUE TITLE
prepare for many more signals

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#491]
AFAIK we get soon many more signals. Thus, we need to discuss what should happen to the side panel; Soon no one will have a large enough screen that would fit all vertically stacked signals. 

options
 * limit to a few selected one
 * add option to add more on demand (however that means we will have two signal selectors on the screen and getting more complex)
 * reconsider #192

**Comment by tildechris** [comment]
Closing as obsolete.  We'll consider a long list of signals in the redesign effort.
