### ISSUE TITLE
discuss: minimum bubble size

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#493]
atm there is a minimum bubble size in place:

![image](https://user-images.githubusercontent.com/4129778/94141643-59d14a00-fe6d-11ea-9801-df8d85be9849.png)

not sure how useful that is. that 0 doesn't mean no bubble.

For spikes, 0 = no height

**Comment by tildechris** [comment]
Yes, I agree that there should be no-bubble if there is no data.  0 = no bubble, but you're still able to hover and see stats.
