### ISSUE TITLE
Top-10 mode shows "error occurred" for many indicators

### ISSUE THREAD

**Issue by benjaminysmith** [cmu-delphi/www-covidcast#499]
**Actual Behavior:**

"error occurred" shows where mini graphs should be in top 10 mode

When I...

- go to https://dev--cmu-delphi-covidcast.netlify.app/
- Click on Top 10
- Change the indicator type to e.g., "covid indicator combination"

Link with errors: https://dev--cmu-delphi-covidcast.netlify.app/?sensor=indicator-combination-nmf_day_doc_fbc_fbs_ght&level=county&date=20200918&signalType=value&encoding=color&mode=top10&region=42003

**Expected behavior**

Graphs are shown (or nice error message hidden)

**Screenshots**
![3vEUzjftrN3uKz8](https://user-images.githubusercontent.com/71528245/94284522-81351f00-ff20-11ea-861b-96970b8882e4.png)

**Rating Scale (1 is minor, 7 is severe):**

3 (nice to see graphs but raw values are shown so still usable)

**Context**

- Browser: Chrome.

**Additional context**

**Comment by philmcguinn** [comment]
I saw this as well particularly with added indicators, like the 3 hours away from home or 6 hours away from home. These usual don't populate on the main map, so my best guess is that we just don't have the data. A better user experience would be to adjust the messaging for this error to make it more clear why this is happening. 

Here's my screenshot in case it's helpful
![Screen Shot 2020-09-25 at 8 06 22 AM](https://user-images.githubusercontent.com/71901127/94315905-450db880-ff38-11ea-9349-6844b6dbca19.png)

**Comment by adamperer** [comment]
@sgratzl can you check if this is an API issue or a UI issue?
