### ISSUE TITLE
Map titles hard to read against map background

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#512]
**Actual Behavior:**

When I select a county and the map zooms me in to that county, the map title can be hard to read against the background, depending on the map colors behind it.

**Steps to Reproduce the Bug:**

1. go to https://cms-staging.andrew.cmu.edu/covid/?sensor=fb-survey-smoothed_hh_cmnty_cli&level=county&date=20200925&signalType=value&encoding=color&mode=overview&region=49049
2. look at the map title

**Expected behavior**

Some way to make it visible against the background. I'm not sure what would work; putting the title in another bubble/block may feel cluttered.

Also, it appears the title is forced to be 12px font, while the other navigation links on the top of the page are 16px, and the graph titles on the right are 1em/14px, so the map title is nearly the smallest text on the entire page.

**Screenshots**
![Screen Shot 2020-09-29 at 2 27 20 PM](https://user-images.githubusercontent.com/711629/94600481-ee69ec80-025f-11eb-9d01-894652ac1778.png)

**Rating Scale (1 is minor, 7 is severe):**

3

**Context**

- Browser: Firefox 81

**Comment by adamperer** [comment]
An easy fix might be to make the text black and increase the font size to be consistent with the other elements?  Thoughts, @sgratzl?

**Comment by sgratzl** [comment]
in v1.8 it looked like: 

![image](https://user-images.githubusercontent.com/4129778/94696833-c8b01680-0337-11eb-8756-43556b631af7.png)

on mobile:
![image](https://user-images.githubusercontent.com/4129778/94697048-044ae080-0338-11eb-8b0a-27d5e4012279.png)
