### ISSUE TITLE
question: side panel not longer togglable

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#517]
**Actual Behavior:**

when I take a look at v1.8. there was the option to hide the side panel: 

https://cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20200926&signalType=value&encoding=color&mode=overview&region=42003

![image](https://user-images.githubusercontent.com/4129778/94668157-fed9a000-030f-11eb-822c-5158a6fb7e1f.png)

this option has been removed in v1.9. if this was on purpose, please close this issue again

**Comment by adamperer** [comment]
I think it makes sense to re-insert this option, if not too painful.  Will this also fix #518 ?
