### ISSUE TITLE
small multiples are not longer accessible on mobile

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#518]
**Actual Behavior:**

When I take a look at v1.8

https://cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20200926&signalType=value&encoding=color&mode=overview&region=42003

I was able to toggle between map and line charts in the overview:

![image](https://user-images.githubusercontent.com/4129778/94668325-2fb9d500-0310-11eb-9f58-4bff54061f88.png)

This is not longer possible in v1.9

![image](https://user-images.githubusercontent.com/4129778/94668363-3b0d0080-0310-11eb-9d1c-ac1a58707bd7.png)

was this intentional?

**Comment by adamperer** [comment]
This was not intentional.  Thanks for catching this.
