### ISSUE TITLE
consider switching to different mode nav only in narrow settings

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#520]
It would be great if the mode nav mobile version just appears in narrower settings, atm. it switched around 760px

e.g. 

https://dev--cmu-delphi-covidcast.netlify.app/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20200926&signalType=value&encoding=color&mode=overview&region=42003

![image](https://user-images.githubusercontent.com/4129778/94670523-f6369900-0312-11eb-8827-11fbd2d6d058.png)

even tho just a few pixels wider it indicates that the tab pane would still easily fit:

![image](https://user-images.githubusercontent.com/4129778/94670596-0ea6b380-0313-11eb-991f-d14099be9c9c.png)

**User story**

**Additional context**

**Comment by kateharwood** [comment]
Just to be clear, the "mode nav" is the tabs at the top that say "Map Overview" "Timelapse" "Top 10" "Export Data"?

**Comment by sgratzl** [comment]
yes, in the code, there is the notion of different `modes` the app has. In the current version they are shown as tabs in previous version we had a different way to let the user navigate between modes.

**Comment by kateharwood** [comment]
Got it, thanks. As I'm looking at it, it seems like mobile mode in general starts pretty early (aka other elements could still fit reasonably well at 765px too), do we want to just make mobile mode start at a bit smaller width in general?

**Comment by sgratzl** [comment]
when I created this issue I just noticed the mode navigation, if you have additional suggestions how to tune the layout feel free to create an PR for it.

**Comment by kateharwood** [comment]
Cool sounds good
