### ISSUE TITLE
Improved method to automatically import strings document into code

### ISSUE THREAD

**Issue by adamperer** [cmu-delphi/www-covidcast#522]
It would be great if there could be an automated way to import all of the text of the indicators.  Previously, [this document](https://docs.google.com/document/d/13naRh47E6OjiHwV2z-VyU7o9vE6MlSj_cF6x2u9pdbc/edit) was copy and pasted directly into the code and was a less painful way to import the text.

However, some of the text migrated [here](https://docs.google.com/document/d/1kDqRg8EaI4WQXMaUUbbCGPlsUqEql8kgXCNt6AvMA9I/edit#) and this process broke.

@sgratzl, could you suggest a better way to allow collaborate edits outside the code (with similar ease to Google Docs), but make it less painful to import in the code base.

Some possibilities may include google sheets (where you can download a CSV), a structured markdown document, or go back to the JSON format we had previous?  Open to any ideas you may have to make your life easier.

Tagging @RoniRos and @capnrefsmmat to follow the discussion.

**Comment by sgratzl** [comment]
when should the syncing happen?
 * run time - when you visit the page
 * build time - when we deploy it or build it locally
 * on demand - when someone starts a script

**Comment by adamperer** [comment]
IMO, syncing should happen at 'build time' and all fields from both documents should be imported.   I believe the signals document only contains signals that should be shown, so if they are present in the document, they should be shown.

Any thoughts or corrections, @krivard?

**Comment by sgratzl** [comment]
this is an example of a current signal description, for cases/deaths it is more complex since once signal in the menu actually is four with the different combinations (ratio, cumulative):

```js
{
    type: 'late',
    name: 'COVID Antigen Test Positivity (Quidel)',
    longDescription:  `When a patient (whether at a doctor’s office, clinic, or hospital) has COVID-like symptoms, doctors may order an antigen test, which can detect parts of the virus that are present during an active infection. Quidel, a national provider of networked lab testing devices, provides us with data from every COVID antigen test that they conduct. We report the percentage of COVID antigen tests that are positive. Note that this signal only includes Quidel’s antigen tests, not those run by other test providers.`,
    links: [
      {
        alt: 'Technical description',
        href: 'https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/quidel.html#covid-19-tests',
      },
    ],
    id: 'quidel',
    signal: 'covid_ag_smoothed_pct_positive',
    levels: ['state', 'msa', 'hrr'],
    tooltipText:  'Positivity rate of COVID-19 antigen tests, based on data provided by Quidel, Inc.',
    mapTitleText:  'Positivity rate of COVID-19 antigen tests',
    yAxis: 'Percentage',
    format: 'percent',
    hasStdErr: true,
  },
```

what fields should be hosted externally?

**Comment by RoniRos** [comment]
Ideally, it would be convenient to keep them all together externally.  But if this makes it more difficult to incorporate them, it's okay to restrict it to only the ones that have natural language content, including 'name'.   So that would be:  name, longDescription, tooltipText, mapTitleText, yAxis.  I assume we would 'signal' to anchor on.  And it might make sense to keep 'format' with 'yAxis'.

**Comment by tildechris** [comment]
In #570 we came up with the idea of generating an actual markdown (or text really) file in addition to generating the constants information.  This would give us the ability to more easily compare changes between version without needing to take apart the JSON file, as well as it being easier to recreate the doc if that ever needs to happen.

This satisfies my concerns about brittleness in the build process.
