### ISSUE TITLE
"Select from Top for" Menu is Compare Mode - Current Category Style 

### ISSUE THREAD

**Issue by cgg-cmu** [cmu-delphi/www-covidcast#529]
**Actual Behavior:**

The bold and underlined font style for the current category text in the "Select from Top for" Menu indicates that it's probably a link.  If it is supposed to be a link it's not working, and if it's not the styling could be confusing to a visitor. Consider another font treatment or layout to differentiate from the label and category.
![image](https://user-images.githubusercontent.com/60197405/94748707-eab59300-034f-11eb-924a-890cf5661a92.png)

**Rating Scale (1 is minor, 7 is severe):**

1

**Context**

- Browser: Observed on Chrome Mac OS, Chrome PC

**Comment by tildechris** [comment]
Closing as obsolete since this will change in the upcoming redesign.
