### ISSUE TITLE
consider switching to showing 'ratios per 100,000' per default

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#536]
we should consider showing the ratio version for cases/deaths per default.

**User story**

while the count version is the default one in most maps, it inherits the problem of showing a population density map. The ratio version is normalized thus you can more easily see what are the current (normalized) trends. 

e.g.

http://localhost:8080/?sensor=indicator-combination-confirmed_7dav_incidence_num&level=county&date=20200930&signalType=value&encoding=color&mode=timelapse&region=42003

![image](https://user-images.githubusercontent.com/4129778/95086775-2c17bb00-0721-11eb-8e3e-83e70998248a.png)

http://localhost:8080/?sensor=indicator-combination-confirmed_7dav_incidence_num&level=county&date=20200930&signalType=value&encoding=color&mode=timelapse&region=42003&signalR=true

![image](https://user-images.githubusercontent.com/4129778/95086809-346ff600-0721-11eb-9ac5-9d4a8f8cee4b.png)

Both pictures tell a very different story. However, one might consider this change a breaking change, since users who will go to the map will see a very different result. 

**Additional context**

**Comment by capnrefsmmat** [comment]
Poking this issue. I think that for cases and deaths, making ratios the default is essential: showing raw counts just makes the map a map of population density, and is not useful to make geographic comparisons.

In fact, if it were up to me, I'd make ratios of incidents the *only* view of cases and deaths, and remove the cumulative/incidence and counts/ratios selectors. (We can still show counts in the tooltips and on views for specific geographic areas.) I just don't know of any specific use cases for the other map views. But that's just me -- maybe our UX research has uncovered some specific cases where people need raw counts or cumulative counts.

**Comment by tildechris** [comment]
I agree that the choropleth enables geographic comparisons, and cumulative counts don't specifically have much value there.

For now, yes, let's default to incident rates per pop, and in the redesign we'll be more opinionated.
