### ISSUE TITLE
Enable COVID antigen test signals at the county level

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#539]
@jingjtang says the COVID antigen test signal is now available at 700 or more counties, meaning it could be useful to allow it to be mapped.

Currently the map is inconsistent. We do not allow the user to select the antigen tests to map at the county level, but since county data is in the API,  viewing the county data for another signal will show the antigen tests in the list of graphs on the right. So you can view county data easily, you just can't see a map of it.

I propose including county maps in the next release.

**Comment by sgratzl** [comment]
see https://github.com/cmu-delphi/www-covidcast/pull/460

**Comment by capnrefsmmat** [comment]
Ah yes; I forgot we already discussed this. Thanks.
