### ISSUE TITLE
Double Clicking on Map To Zoom In on Desktop

### ISSUE THREAD

**Issue by kateharwood** [cmu-delphi/www-covidcast#549]
It would be great if, on desktop, you could zoom in on the map by double clicking where you want to zoom in.

**User story**

 Currently, when you use the "plus" button on the side to zoom in, it zooms in to the middle of your screen, so if the spot you want to zoom in on is off center, you have to click the plus button, then readjust the map, then click the plus button, then readjust, etc.

**Additional context**

**Comment by dlaliberte** [comment]
Another way to zoom at a point is to scroll with the mousewheel, or some less-obvious equivalent (like ctrl-drag starting at a point).   Using the mousewheel doesn't work so well if it is being used to scroll the page itself, unless there is something like a mode change to first select the map, then scroll in the map to zoom.

**Comment by kateharwood** [comment]
@sgratzl is there some reason I should know for why we don't have this currently?

**Comment by sgratzl** [comment]
I think I disabled it:

https://github.com/cmu-delphi/www-covidcast/blob/82d232a1986a4275f0959d7f0d18382919c00d9e/src/components/MapBox/AMapBoxWrapper.js#L87

cause pinch-zoom and zooming by mouse wheel is enabled which is used by most users and I sometimes had issues that it conflicted with selecting a region. But you can re-enable it again.

**Comment by kateharwood** [comment]
@Letsgohyde @philmcguinn what do you guys think about re-introducing double click to zoom (if we can make sure it doesn't interfere with selecting a region)

**Comment by kateharwood** [comment]
@jennyxxdance do you have any thoughts on this?

**Comment by philmcguinn** [comment]
Sorry! still learning the ropes of github. This seems like a good change to me if it's just a net positive as proposed. 

Though I just played around with the map a bit to see if it might interfere with any existing double click behavior, and it looks like double clicking on a region while already zoomed in (with the trackpad in this case) will _sometimes_ zoom the map back out to the initial view. Other times it stays zoomed and just reselects the new region. This feels a bit buggy to me. Could that be related to the issue Sam described above?

**Comment by kateharwood** [comment]
Seems like if you click again on the region you just selected, while zoomed in, the map zooms back out. This behavior seems like it could be WAI to me, but could also see the argument for disabling this. We should be consistent on whether you can click to zoom at all.

**Comment by philmcguinn** [comment]
Agreed, especially if double click zooms in now, that would be odd for it
to zoom out sometimes! I would lean towards the more traditional behavior
of double click always zooming in.

**Comment by tildechris** [comment]
Closing this as obsolete since we're going to fundamentally change how users interact with maps in the redesign effort.
