### ISSUE TITLE
Propagate updated population figures from indicators into www-covidcast

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#553]
**Actual Behavior:**

Population in NYC boroughs is set to 1 in the map due to an old exception in JHU handling. We now use the combo source for cases & deaths, which uses USAFacts for NYC, and does not require this exception; JHU has additionally updated their geo policies and doesn't need the exception either.

**Steps to Reproduce the Bug:**

1. go to https://covidcast.cmu.edu/index.html?sensor=indicator-combination-confirmed_7dav_incidence_num&level=county&date=20201006&signalType=value&encoding=color&mode=overview&region=36081
2. Mouse over Queens County

**Expected behavior**

Population: 2253858

**Screenshots**

![image](https://user-images.githubusercontent.com/1158666/95475887-b136e600-0954-11eb-9720-73bcbe3b8c40.png)
![image](https://user-images.githubusercontent.com/1158666/95475915-b72cc700-0954-11eb-88af-71ecef01424a.png)

**Rating Scale (1 is minor, 7 is severe):** 2? it's wrong, but the only place it shows up is the mouseover -- the prop figures come from the API, so they aren't affected.

**Additional context**

(used by combo cases/deaths for most locations) Population file used by USAFacts: https://github.com/cmu-delphi/covidcast-indicators/blob/main/usafacts/static/fips_population.csv

(used by combo cases/deaths for Puerto Rico) Population file used by JHU:https://github.com/cmu-delphi/covidcast-indicators/commit/6fda1b21a227dcda773f43b448da6060ba161bf7

Population file used by map (counties): https://github.com/cmu-delphi/www-covidcast/blob/main/src/maps/processed/county.csv

**Comment by dshemetov** [comment]
The [geoutility contains a function](https://github.com/cmu-delphi/covidcast-indicators/blob/8867c14ae440c38f6a40971338859b6172f0eb53/_delphi_utils_python/delphi_utils/geomap.py#L395) that will add a population column to a dataframe with a FIPS or ZIP code. The population data there is built from the [2019 US Census Estimates](https://www.census.gov/data/tables/time-series/demo/popest/2010s-counties-total.html) (excel file under Datasets).

**Comment by dshemetov** [comment]
The existing static file in JHU was generated by this [script](https://github.com/cmu-delphi/covid-19/blob/main/jhu-cases/notebooks/create-census-population.ipynb). It contains modifications for NYC and some others that seem unnecessary now, so I think we can just rely on the raw data from the Census.

**Comment by dshemetov** [comment]
Ah, I think I'm thinking of a related issue in JHU internals, which is separate from where the viz derives its population file. If viz needs a population file to pull from, [this](https://github.com/cmu-delphi/covidcast-indicators/blob/8867c14ae440c38f6a40971338859b6172f0eb53/_delphi_utils_python/delphi_utils/data/fips_pop.csv) is what the geocode utility uses.
