### ISSUE TITLE
Consider adding a GapMinder mode

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-covidcast#565]
It would be great if there is a way to correlate two or more signals with each other, creating a scatterplot, scatterplot matrix, or even a Parallel Coordinates Plot. 

**User story**

I wanna compare two signals with each other for multiple regions. One simple approach is to implement something like GapMinder (https://www.gapminder.org/tools) which is essentially
 * a scatterplot where the user can select the axes
 * a time lapse player where the plot shows the change over time
 * sizing the bubbles e.g., according to population
 * coloring the bubbles e.g., according to categorical one (e..g states in the mid-west, north-east, ...)
 * upon selecting a node it will generate or show its trace over time

https://www.gapminder.org/tools/

vega gapminder example: https://vega.github.io/vega-lite/examples/circle_bubble_health_income.html

**Comment by dlaliberte** [comment]
I'd love to work on this.  

Partly, I need to create a replacement for the Google Charts MotionChart, which was also modeled after the gapminder tool.  The MotionChart was unfortunately written in Flash years ago, and is now a flash in the pan.

**Comment by tildechris** [comment]
Let's slate this for the desktop version of the redesign.  I've been thinking about this topic as adding "correlogram" charts.  We will have to experiment with the best ways to visualize.
