### ISSUE TITLE
Consider moving signal descriptions to a project markdown file

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#570]
Re:#522, #530 implements a method of authoring signal descriptions using a Google Doc with markdown-like content.

We should investigate using a local project markdown file so this content can be properly versioned and remove a network call from the build process.  It'd be a bummer if we couldn't build a release if we couldn't pull down the doc for whatever reason.

We'll just have to consider the authoring experience, but GitHub already has a good support for previewing markdown.

**Comment by sgratzl** [comment]
we we merge this with https://github.com/cmu-delphi/www-covidcast/issues/522?

**Comment by tildechris** [comment]
My thought was that we could close #522 out with #530 since it's an improvement, and discuss enhancements from that here.

**Comment by capnrefsmmat** [comment]
As context, the main motivation with using a Google Doc is to facilitate commenting and discussion. Often we argue about the best wording to describe an indicator, or the wording that most accurately reflects the source, and do so in comments on the doc.

Any replacement should facilitate discussion, and do so with a fairly low barrier to entry. (For example, I don't think @RoniRos wants to have to clone the repo and open a PR just to suggest a wording change, even if review comments on PRs do allow for discussion.)

So I agree with the desire for a better solution, but it has to fit with the needs of the stakeholders in these signal descriptions.

**Comment by krivard** [comment]
@RoniRos has a strong preference for group-edited documents like this to be in Docs, so that we can use the suggest changes & comment threading features there to reach consensus asynchronously. Using the comment/suggest changes PR mechanism on a project asset is substantially more restrictive and difficult to read, particularly if you have multiple suggested changes pending, which Docs handles seamlessly. GitHub markdown previews are great, but aiui they don't support previews of suggested changes.

**Comment by tildechris** [comment]
Once consensus is made, how often are changes made?  If there are few changes after a signal goes live, an alternative would be to collaborate on the signal description in a design document until consensus, at which point it's pulled into the markdown file when the signal is enabled.

At first glance such a workflow may not seem like much of an improvement over having the signal descriptions in the constants.js file, but it would still be much easier to read and edit than the previous JSON file.

**Comment by tildechris** [comment]
Thanks for the background.  Since my concerns with the #530 approach as hypothetical (brittleness, etc), it seems prudent to stick with this approach if it's a better user experience for collaborating on descriptions.

One, idea: can we "compile" the doc into a markdown file that is then saved as an asset that is version controlled?  

That would protect against the failure scenario of losing the master doc for some reason; we'd be able to easily re-create it from the last release.  This also has the by-product of seeing for sure what the content differences were between versions as opposed to doing some possibly-out-of-sync versioning in the doc as well.

**Comment by krivard** [comment]
> can we "compile" the doc into a markdown file that is then saved as an asset that is version controlled?

ooooh yes, we absolutely should!

**Comment by tildechris** [comment]
Great! Let's merge this with #522 and add this as part of #530.

**Comment by tildechris** [comment]
Duplicate of #522
