### ISSUE TITLE
Change github link to point to www-covidcast repo and add "related repos" to readme

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#576]
As @ryantibs pointed out, when people click on the "github" link on the main site, they probably expect to find the visualization repository, instead of trying to parse through all of the public repos at the cmu-dephi level.

We can also add a "related repos" section to the readme outlining the other major repositories, like Ryan did in [covidcast/README.md](https://github.com/cmu-delphi/covidcast/blob/main/README.md):

**Related repos**
* covidcast: Public-facing tools supporting Delphi's COVIDcast effort.
* delphi-epidata: Back end for Delphi's Epidata API
* covidcast-indicators: Back end for Delphi's COVID indicators
* covid-19-forecast: Public repo for Delphi's COVID forecasters

**Comment by sgratzl** [comment]
the main toolbar has to be changed in multiple locations atm: 
 * in the blog main menu: https://github.com/cmu-delphi/delphi-blog/blob/main/config.toml#L32
 * in this repo: https://github.com/cmu-delphi/www-covidcast/blob/main/src/index.html#L140
 * in the CMS itself (as used in the survey page)

**Comment by sgratzl** [comment]
is this still valid with the website redesign?

**Comment by tildechris** [comment]
Good question.  I think we can close this out, due to the fact we now have pinned repositories on the cmu-delphi org page.
