### ISSUE TITLE
Compare mode tooltips should show data for all locations at the hovered date.

### ISSUE THREAD

**Issue by dlaliberte** [cmu-delphi/www-covidcast#592]
**Actual Behavior:**

When in "Compare mode" with more than one location selected, hovering over a date where more than one location has data shows the tooltip with only one location's data.  It's not clear which location is picked.

**Steps to Reproduce the Bug:**

Go to Map Overview, click "Open Compare mode", add a(nother) location, hover over the graph at various dates and note which data is displayed in the tooltip.

Region Details, and DetailView pages demonstrate the same problem.

**Expected behavior**

Should show data for all the locations in the tooltip, or at least make it easy to select one location or another, but that is difficult when lines are close.

**Screenshots**

![image](https://user-images.githubusercontent.com/570125/97247561-4ef43700-17d6-11eb-9657-59992fc73ee2.png)

**Rating Scale (1 is minor, 7 is severe):**

4

**Comment by dlaliberte** [comment]
This is similar to what is shown on the Region Details tab, in the table for each indicator.

![image](https://user-images.githubusercontent.com/570125/97768549-28960a80-1afa-11eb-814c-c72a65cbca83.png)

So if we add the info to the tooltip, we wouldn't need it displayed separately in this table. 

Any objections to me working on this?

**Comment by philmcguinn** [comment]
This is a great catch, I think finding a way to show all of this data for the comparison should definitely happen. Of the solutions you mentioned, I think squeezing all the data into one tooltip is the most clear from a user perspective. 

The alternative you mentioned "_the tooltip would initially show the key data value (the one value being drawn with the line chart) for each of the regions, and then the user could (somehow) select one region to see more data for_" seems a bit more challenging, and is not an interaction pattern I'm familiar with.

**Comment by dlaliberte** [comment]
By the way, I think this problem used to be much less of a problem when the tooltip found the "nearest" data point, if you could get the mouse pointer close enough to your desired data point.    But we turned of the "nearest" selection mode because it was very time consuming.  I think it was also problematic because crowded noisy data made it hard to point at the data point you were interested in, although users might be more interested in outliers that are easier to point at.

**Comment by dlaliberte** [comment]
Everything I tried ended up being very convoluted and not entirely successful, for reasons that ultimately appear to be bugs in vega-lite.  But it is easy to limit the tooltip to only show data for the first location, the gray line.

**Comment by tildechris** [comment]
Let's close this for now since we will have major changes coming to compare mode in the redesign.
