### ISSUE TITLE
Switching region level leaves old outline

### ISSUE THREAD

**Issue by cabreraalex** [cmu-delphi/www-covidcast#594]
**Actual Behavior:**

When I switch levels, e.g. from "county" to "state", it leaves the old outline of the county overlayed.

**Steps to Reproduce the Bug:**

1. go to https://cms-staging.andrew.cmu.edu/covid/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201023&signalType=value&encoding=color&mode=overview&region=42003
2. Switch to metro area or state

**Expected behavior**

Ideal - selects the nearest area in the new view, e.g. the metro area or state that contains the county. Not sure though, lots of options

**Screenshots**

<img width="1215" alt="Screen Shot 2020-10-27 at 1 27 26 PM" src="https://user-images.githubusercontent.com/4563691/97338785-2a40a380-1858-11eb-8412-428ff88085fa.png">

**Rating Scale (1 is minor, 7 is severe):**

3

**Context**

- Browser: Firefox

**Comment by sgratzl** [comment]
see also https://github.com/cmu-delphi/www-covidcast/issues/441

**Comment by cabreraalex** [comment]
+1 I knew it had to be tracked somewhere. IDK, for me having an outline of a nonexistent region is much more confusing than removing it or unselecting, but there is definitely a better solution than both of those.

**Comment by tildechris** [comment]
Closing as obsolete since we are going to overhaul location changes in the redesign.
