### ISSUE TITLE
County dropdown improvement

### ISSUE THREAD

**Issue by kateharwood** [cmu-delphi/www-covidcast#595]
I think it would make more sense if the county dropdown menu looked something more like this (without the states being selectable though).
<img width="258" alt="Screen Shot 2020-10-28 at 10 51 42 AM" src="https://user-images.githubusercontent.com/14190352/97453365-08a0f400-190c-11eb-97d5-133529ae3a38.png">

**User story**

It seems odd when you click on the county selection box to be presented with a random county in Texas first - we aren't used to looking at a list of US counties alphabetically. We are used to looking at the states alphabetically. Also, it might be confusing for some users to have to type something in to select it. I might also be someone who wants to explore counties in my state (or throughout the US), but might not know the name of all of them.

Open to pushback on this, but the current county selection has always seemed odd to me.

**Comment by kateharwood** [comment]
@philmcguinn @Letsgohyde @jennyxxdance @sgratzl @tildechris @dlaliberte (tagging you all because not sure of the process to get this in front of people for feedback)

**Comment by philmcguinn** [comment]
Hey Kate, where does this reside? I was just poking around for a few minutes but don't see a county dropdown anywhere. Is this proposing the addition of a dropdown box, or adjusting an existing one?

I would agree that people are used to looking at a list of states, so the expansion approach you mentioned above seems more intuitive than the current experience. I would not be in favor of replacing search, which is a great experience for anyone just trying to find their own county or area. The journey of trying to find counties in an area is more easily achieved by zooming on the map than by looking through an alphabetical list.

**Comment by dlaliberte** [comment]
Clicking in the county text box on the top right expands to show a list of counties that can be selected.

![image](https://user-images.githubusercontent.com/570125/97473752-b965be00-1921-11eb-8ecd-a47c41aa7eae.png)

Also in "compare mode", clicking in the "Add another" text box shows the same list, I believe.

**Comment by sgratzl** [comment]
without a widget framework this is going to be a lot of work. 

One example how it could look like: https://yacobo.vercel.app/ -> top right search region box

**Comment by kateharwood** [comment]
Yes @sgratzl that example is exactly what I was thinking! Yeah, I was thinking we probably would need to import a tool do this.

**Comment by tildechris** [comment]
This is a good suggestion, we should consider this.  I'd be interested to hear what the effort estimates are for the different options here:

1. Invest in a widget framework.  Would we need to make wholesale changes or can we introduce this only in one place.
2. Write our own component from scratch.

**Comment by sgratzl** [comment]
note: the search box allows you to select all type of regions:
 * states
 * counties
 * MSA regions
 * at some point HRR (hospital) regions

so a plain tree might not work.

**Comment by tildechris** [comment]
Good point Sam.  Sounds like there would be three top level nodes in that case.

* States (and then counties, which never span states)
* MSA regions (which often span states)
* HRR regions (which often span counties)

We could set up a directed acyclic graph, and then tree-ify it by duplicating MSA and HRR under counties that they cover.  For example, `New York City-Newark-Jersey City, NY-NJ-PA MSA` points to three states and a number of counties.  That might not be very good UX wise, since just typing for New York City would show that MSA under a bunch of counties in NJ and PA, but it'd be one way to solve it.

**Comment by tildechris** [comment]
Closing this as obsolete.  We should have a better way to browse geo in the redesign.
