### ISSUE TITLE
Start user off on their own county rather than Allegheny

### ISSUE THREAD

**Issue by kateharwood** [cmu-delphi/www-covidcast#596]
Right now the default county that the user starts off with when they first enter the site is Allegheny. If we know our primary users are in the Allegheny Health Department and other local departments, and we want to keep it the way it is, feel free to ignore. But I think it would be better if we defaulted to the current location of the user. Several sites do this (rt.live being one example, when they give a link saying "See details about the spread in __") although at the state level. It might be harder to be precise at the county level. 

**User story**

I am someone in a state other than PA, curious about what the virus looks like in my county. I have never heard of Allegheny county (and I do not know that is where CMU is located). I am confused why that is the first thing shown to me, and I need to do some work to find my county either on the map or in the dropdown each time I visit the site.

**Comment by kateharwood** [comment]
@krivard @tildechris @sgratzl

**Comment by krivard** [comment]
We're planning to have support for national on all indicators relatively soon (probably not 1.11 but not long after that); would that be a superior choice? Not everybody is favorably inclined to the "this website wants to know your location" popup.

**Comment by kateharwood** [comment]
That sounds good! That wouldn't solve the issue for the forecast view (unless we get national forecasts soon!), but since forecasts would be a secondary view rather than the main map view it doesn't seem as pressing.

**Comment by tildechris** [comment]
+1 to not showing the location popup unless the user asks for it.  We could have a "my location" item whereby it prompts and then gets course location data and maps it to the most granular geo_type for that signal.

This is probably a better approach than doing something like an IP address geo match since that isn't terrible accurate.

**Comment by tildechris** [comment]
Closing as obsolete since we will change the default geo level in the redesign.
