### ISSUE TITLE
Document the meanings of columns in the exported CSV files

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#599]
It would be great if somewhere in the Export Data interface, perhaps when you click the CSV button, it would provide a summary of the column names and what they mean.

**User story**

A non-technical user decides to download our data to make a spreadsheet or graph. They press the CSV button and get a file with columns like "geo_value", "time_value", "value", "lag", etc., and don't know what these mean.

**Additional context**

We have documentation in several places that could be used here:

* [API docs](https://cmu-delphi.github.io/delphi-epidata/api/covidcast.html#response)
* [R package return value docs](https://cmu-delphi.github.io/covidcast/covidcastR/reference/covidcast_signal.html#value)
* [Python package return value docs](https://cmu-delphi.github.io/covidcast/covidcast-py/html/signals.html#covidcast.signal)

**Comment by capnrefsmmat** [comment]
This may also require a way of pointing to the API docs defining what a particular signal means.

**Comment by sgratzl** [comment]
the current version has links to the aforementioned api docs and signal descriptions, e.g. for python:

![image](https://user-images.githubusercontent.com/4129778/101172467-382fd400-360f-11eb-9846-afe5e55b93d6.png)
