### ISSUE TITLE
Consider supporting an explainer popup to provide additional details on exceptional phenomena

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#601]
All of humanity's technology systems are learning how to handle a global pandemic at the same time, and we should expect a commensurate number of errors and weird edge cases. If we could provide users with greater context for interpreting these scenarios, it would both increase trust in our tool and help elevate the public's understanding of the scientific process.

**User story**

The health department of Wyoming has been including probable (but untested) cases in their case count for months. When they decide to switch to only including tested confirmed cases, the apparent case incidence plummets to huge negative numbers. This shows up in the map as Wyoming being a sole buttercup in a field of dark red. A visual cue lets the user know that yes, this is the correct display, and it is indeed weird. When clicked, it brings up a card that explains the additional context, and links to the relevant announcement on the Wyoming DoH website.

Screenshot lifted from @tildechris's outages report:

![image](https://user-images.githubusercontent.com/1158666/97581029-76135a00-19ca-11eb-8edd-d7e88536da13.png)

**Additional context:**

In addition to the bulk updates and negative incidence events that happen from time to time, this feature could also be used to explain things like:
* Why some counties are grouped together (they share public health resources and don't report separately)
* Why the daily count in NYC counties is sometimes fractional

**Comment by sgratzl** [comment]
so generalized some kind of annotation database would be useful with fields:
 * time_value: when should the annotation be shown: all the time (*), specific date(s), specific date range(s)
 * geo_value: where should the annotation be shown: all (*), specific geo id(s), [all counties in a state?]
 * signal: which signal is affected: all (*), specific signal(s)

 * type: some annotation type enum, like whether it is about data, documentation, outtakes,. ...
 * text: the annotation text
 * links: list of links with details

a possible approach:
 * create a google sheet that acts as a "database"
 * load the CSV version of it at the beginning in the app
 * show the annotations on demand.

**Comment by RoniRos** [comment]
I love this enhancement.  It could and should be tied to the anomaly/alerting system.  Namely, an alert is issued due to some anomaly that was automatically (or manually) detected.  A Delpher investigates it, and decides whether it should be corrected, not corrected but explained. or ignored.  If explained, they issue the explanation with all the fields as @sgratzl suggests above, either by calling a function or by manually adding to a Google Sheet.

**Comment by tildechris** [comment]
This should be rolled into the signal dashboard effort.  Perhaps when there are anomalous conditions we can link to the dashboard.

**Comment by Letsgohyde** [comment]
This looks great @sgratzl - question, Would this display on hover? Would it display below the current detail on:hover card? I suggest they're merged into the same card, while the "what's going on here" comment has 12px padding below the dynamic metrics. Text treatment italics prepended by an alert triangle icon. 

Thanks for putting this together :)
