### ISSUE TITLE
Safegraph mobility descriptions misleading

### ISSUE THREAD

**Issue by huisaddison** [cmu-delphi/www-covidcast#606]
**Actual Behavior:**

Dropdown for Safegraph indicators are:

"Away from Home 6hr+ a Day"
"Away from Home 3-6hr a Day"

Hover descriptions are:
"Fraction of people spending 6 hours or more away from home that day, based on Safegraph mobility data"

**Steps to Reproduce the Bug:**

1. go to covidcast.cmu.edu
2. Drop down: "Displaying" and hover over Safegraph indicators

**Expected behavior**

6hr+ and 3-6hr should have the important qualifier "6hr+ away from home _in a single location" and perhaps the minor qualifier "between the hours of 8am and 6pm local time".  This is the definition for full time work behavior by Safegraph, which is what we use to compute this indicator.  Our COVIDcast documentation is correct and does include these qualifiers. https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html

The omission of these qualifiers has confused at least one public user of our data.

**Screenshots**

![Screenshot from 2020-10-29 14-55-14](https://user-images.githubusercontent.com/8422804/97620180-8ee63480-19f7-11eb-9415-d2f4080b632c.png)

**Rating Scale (1 is minor, 7 is severe):**

5

**Context**

- Browser: Firefox

**Additional context**

Signals that actually compute what is suggested by the current public-facing descriptions are suggested here: https://github.com/cmu-delphi/covidcast-indicators/issues/405

**Comment by sgratzl** [comment]
please suggest your changes in https://docs.google.com/document/d/1RLy4O-gtACVjLEVD_vxyPqvp9nWVhqEjoWAKi68RKpg/edit#heading=h.oxebzdy7nl8w

**Comment by RoniRos** [comment]
@sgratzl I just made my suggestions there.

**Comment by sgratzl** [comment]
> @sgratzl I just made my suggestions there.

thx. is the renamed signal already available through the api?

**Comment by RoniRos** [comment]
Yes, it is.  However, before you fold it into the app, I'd like to get feedback from at least @huisaddison , @krivard and @capnrefsmmat .  Can you three please review the [changes ](https://docs.google.com/document/d/1RLy4O-gtACVjLEVD_vxyPqvp9nWVhqEjoWAKi68RKpg/edit#heading=h.oxebzdy7nl8w)and note your concurrence or your preferred alternatives?

**Comment by huisaddison** [comment]
@RoniRos the updated MapTitleText looks good (i.e., the addition of 'in one location away from their home').  

I do wonder whether we should change the overall indicator name from "Away from home 6hr+ day" ["Away from home 3-6hr a day"] back to "Full-time work behavior" ["Part-time work behavior"].  It's simply a matter of which compression of the "Fraction of people spending 6 hours or more [3-6 hours] between 8am-6pm, in one location away from their home," is more informative.  I could fall on either side (and regardless, the updated MapTitleText eliminates any doubt).

@sgratzl Yes, they are - the underlying API signals did not change nor were they renamed; this is merely an update to the website descriptors to more accurately reflect what the signals are.

**Comment by krivard** [comment]
I approve the pop-up text modifications, and propagated "one location" into the long descriptions as well.

I am not in favor of language involving full-time or part-time work, except to mention that that's what Safegraph calls these signals. There are loads of reasons someone might be spending time in a single location away from where they sleep at night, and while work may be a very common reason, naming the signal that way tells people that we know for certain that everyone measured is (1) employed, and (2) at their place of work. We have no such knowledge. Safegraph claims to have no such knowledge. We can afford to be more precise in our descriptors.

**Comment by RoniRos** [comment]
Indeed.
One common reason which is not work:  school.
And, lots of jobs do not involve staying in one census block for 6 hours.

**Comment by sgratzl** [comment]
closing see google doc
