### ISSUE TITLE
tooltip text needs tiny edit

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/www-covidcast#611]
On the map view, the small calendar icon near the date menu:
"Go to the latest date for which [signal name] is defined"
should be
"Go to the latest date for which [signal name] is available".

**Comment by dlaliberte** [comment]
How about "...for which _data_ is available", if that is what it is supposed to mean.

**Comment by RoniRos** [comment]
@dlaliberte sorry, my original comment had text in angled brackets which the markdown expunged.  I edited it now to square brackets.

**Comment by sgratzl** [comment]
should have been fixed with #613
