### ISSUE TITLE
Clarify (and possibly expand) the "coverage" information on the map

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/www-covidcast#612]
The current "82% coverage" at the bottom right of the map is a bit cryptic.  What is 82% of what?
Is the signal available for 82% of the locations (e.g. 82% of the counties), or 82% of the U.S. population?

I think both measures are important.  One suggestion:
 On the map, say:
 "Coverage: 724 counties, 82% of pop."
 and add a tooltip that says:
 "Signal is available for 724 of the 3,217 U.S. counties, covering 82% of the U.S. population"

And similarly for states, MSAs, etc.

**Comment by tildechris** [comment]
Current state:

![image](https://user-images.githubusercontent.com/46794497/106522449-c3add000-64ad-11eb-9745-e1f546e85518.png)

Let's consider additional improvements when we deploy the signal dashboard.
