### ISSUE TITLE
Top 10 list refreshes multiple times, occasionally resulting in incorrect clipping

### ISSUE THREAD

**Issue by dlaliberte** [cmu-delphi/www-covidcast#615]
**Actual Behavior:**

The top 10 list refreshes the display of the charts multiple times, partly due to dynamic loading of data but also resize events and clipping recalculations.  This is visible in origin/dev versions, especially after #575.  See https://deploy-preview-575--cmu-delphi-covidcast.netlify.app

The problem is that, occasionally and inconsistently, the resulting display clips the lines incorrectly.  

**Steps to Reproduce the Bug:**

Go to the Top 10 list, and keep switching the indicator that is 'Displaying' by using the drop-down selector until you notice that the clipping is incorrect.

The 7-day average charts for 'Cases' and 'Deaths' are always clipping incorrectly, but for a different reason.

**Expected behavior**

Refreshes should be minimized.
Clipping should be consistently correct.

**Rating Scale (1 is minor, 7 is severe):**

5

**Comment by dlaliberte** [comment]
Sam says:

> it is difficult to say what triggers all the refreshes, I assume there is a "loading refresh" and "have single data" and "have all data = define clipping area" one

> in order to reduce the refreshes one could synchronize the loading of all data such that the (clipped) spec and data is resolved/computed at the same time.  then you should just have: loading and ready

**Comment by dlaliberte** [comment]
The multiple refreshes are still occuring, though reduced in number, and the final state seems to be consistently correct now.  So this problem is not quite resolved, but much less severe.

**Comment by sgratzl** [comment]
@dlaliberte anything I can help with in this issue?

**Comment by dlaliberte** [comment]
I believe your changes that refactored the resize updates fixed the remaining extra refreshes.
