### ISSUE TITLE
Several comments on improving compare mode

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#619]
I've been playing around with compare mode to try to answer the following question: "Is New York in April is like XYZ in mid July?", where XYZ is a southern state.  I've been looking at incidence cases and deaths.  I have the big time series plot open along with the multiple time series panel.  It's been fun to play around with the tool!  But I landed up on several suggestions for things to improve or at least discuss/investigate:

1. Every time I add a new location to compare, the x-range I selected in the big time series plot gets reset.  This is very annoying.  I first selected New York, expanded it to include April, and then added Texas.  But had to reset the x-range.  Then added Florida.  But had to reset the x-range.  Etc.  I think it should remember my selection here: I don't see the downside of making this the default.

2. While in map overview mode, I was on "state" mode for the geo type pull down menu, and then in compare mode, when I search for things to add, under "ADD ANOTHER", I get counties popping up.  This is confusing.  Actually, even when I entered compare mode, I already got "Allegheny County, PA" as the location I'm beginning with, for the comparisons.  (This must be because it detected this as my home location, based on IP address?). Which is also confusing.  

3. I will note however that the suggestions under "Select from Top for COVID Cases" are all states, which is good.

4. Once I click a state from the suggestions under "Select from Top for COVID Cases" (e.g., Texas) it remains there in the list.  (Though I'm disabled from clicking it again.)  It should probably disappear?

5. When I toggle between incidence/cumulative and counts/ratios (per 100,000) the y-label on the big time series plot remains the same.  It should change.  Certainly when you toggle between counts/ratios, it's no longer correct to label the y-axis "Cases" or "Deaths" for example, it should say "Cases per 100,000" or "Deaths per 100,000".  

cc @tildechris, and @sgratzl who I think worked on compare mode

**Comment by ryantibs** [comment]
Also, I'm sorry to mention something that's only vaguely related (and probably has been discussed in other issues) but it's on my mind: I don't like the fact that the map detects my local region (Allegheny County) and chooses to zoom in there when I toggle to another mode, and go back to map overview.  

It's also annoying that it appears in the map query string automatically, via `region=42003`, so that when I copy-paste my URL, somebody else will end up on Allegheny County (which is not my intention usually).  Have we discussed this elsewhere in another issue?

**Comment by sgratzl** [comment]
> Also, I'm sorry to mention something that's only vaguely related (and probably has been discussed in other issues) but it's on my mind: I don't like the fact that the map detects my local region (Allegheny County) and chooses to zoom in there when I toggle to another mode, and go back to map overview.
> 
> It's also annoying that it appears in the map query string automatically, via `region=42003`, so that when I copy-paste my URL, somebody else will end up on Allegheny County (which is not my intention usually). Have we discussed this elsewhere in another issue?

related issue also https://github.com/cmu-delphi/www-covidcast/issues/596. 

Moreover, it doesn't actually detect your location but uses `Allegheny County` as default. Once we have a nation geo type, we can rethink this behavior.

**Comment by tildechris** [comment]
Thanks for the note @ryantibs, I've opened several related issues.  I don't have a strong opinion on 4, but we should fix the 1,2 and 5.

**Comment by tildechris** [comment]
Let's close this.  We're going to revamp how comparisons are made in the redesign.
