### ISSUE TITLE
Y axis of "Top 10" mini-plot is way off for Case ratios & Death ratios

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/www-covidcast#620]
Y axis of "Top 10" mini-plot is way off for Case ratios & Death ratios.

**Steps to Reproduce the Bug:**

https://covidcast.cmu.edu/?sensor=indicator-combination-confirmed_7dav_incidence_num&level=state&date=20201104&signalType=value&encoding=color&mode=top10&region=42003&signalR=true  

1. go to **PASTE BROWSER URL HERE**

**Expected behavior**

**Screenshots**

![scrnli_11_6_2020_8-06-12 PM](https://user-images.githubusercontent.com/23179630/98427621-e590e580-206b-11eb-813a-fe7670100421.png)
 
**Rating Scale (1 is minor, 7 is severe):**

5  (I'm not not sure how severity is defined)

**Context**

- Browser:  Chrome

**Additional context**

**Comment by dlaliberte** [comment]
Already fixed with #617.

**Comment by RoniRos** [comment]
Thanks!

**Comment by RoniRos** [comment]
Already fixed with #617.
