### ISSUE TITLE
"Displaying" selector misleading when viewing Details chart

### ISSUE THREAD

**Issue by bweaver-work** [cmu-delphi/www-covidcast#622]
From a conversation with @dlaliberte, it is misleading that changing the Displaying selector doesn't change the a Details chart being displayed.

suggestion: changing the Displaying selector to also change the Details chart

**Comment by dlaliberte** [comment]
One problem/conflict with this idea is we should also update the Displaying selector to show whatever is showing in the Details chart.  So when the user clicks the magnifier icon for one of the small multiples, this would not only show that indicator in the Details chart but also change the Displaying selector, and maybe unexpected side effect is that this will then change what is shown on the map.

**Comment by tildechris** [comment]
@bweaver-work can you take a screenshot and point out what should change?  I'm have trouble envisioning this issue.

**Comment by dlaliberte** [comment]
There are three displays of the indicator that should remain in sync, which you can see in this screenshot.

![image](https://user-images.githubusercontent.com/570125/98863789-df698300-2436-11eb-812c-8110a28cdb80.png)

1. The "Displaying" selector in the upper left corner can be changed to (currently) change what is displayed on the map.
2. The small multiple for the same indicator shows a magnifying glass icon.  You can mouseover other small multiple charts to see the magnifying glass icon for each one.
3. The Detail View displays the details of the small multiple that you clicked on.  

Changing the selected indicator with the "Displaying" selector should update the small multiple and the Detail View, if it is displayed.  Clicking one of the small multiple magnifiers should update both the "Displaying" selector and the Detail View.

**Comment by bweaver-work** [comment]
Another solution could be to make it more obvious that the Detail View is floating above the map, rather than replacing the map. That could make it more clear that the Displaying selector is changing the Map below, rather than the Detail View above.

**Comment by tildechris** [comment]
Let's close this as obsolete since we're going to change how this works in the redesign.
