### ISSUE TITLE
Add another geo area should be constrained to the current geo-type

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#624]
Re: #619 

"While in map overview mode, I was on "state" mode for the geo type pull down menu, and then in compare mode, when I search for things to add, under "ADD ANOTHER", I get counties popping up. This is confusing. Actually, even when I entered compare mode, I already got "Allegheny County, PA" as the location I'm beginning with, for the comparisons. (This must be because it detected this as my home location, based on IP address?). Which is also confusing."

We should constrain the comparisons to only geo-types for the currently selected area (only show states for states etc.)

I'm not sure if I can think of a good use-case to heterogeneously compare across geo types.

**Comment by sgratzl** [comment]
what about, my county vs my state on wearing masks?

**Comment by tildechris** [comment]
That's a reasonable use-case, but I think we are going to have to revisit how comparisons work in a more wholistic fashion to enable that use-case.

As a user, I'm more surprised that the list doesn't filter than I would be to see that I can't compare across geo-types.  So principle of least-surprise suggests that filtering would be a net improvement.  We can keep this in mind as a consideration when we talk about visualization redesigns.
