### ISSUE TITLE
Population not shown for "rest of [state]" when not enough county-level data available

### ISSUE THREAD

**Issue by philmcguinn** [cmu-delphi/www-covidcast#632]
**Actual Behavior:**

When we show data for "rest of [state]" the population of that area is listed as unknown

When I...

Click on any state in the default Doctor Visits view, outside of an individual county

1. go to https://covidcast.cmu.edu/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201108&signalType=value&encoding=color&mode=overview&region=38000
2. Click on North Dakota, anywhere but the four county borders

**Expected behavior**

I propose that we do the math to determine the population of the "rest of [state]" area by subtracting the population of the delineated counties from the total population for the state.  

**Screenshots**

![Screen Shot 2020-11-13 at 8 20 42 AM](https://user-images.githubusercontent.com/71901127/99094786-236c9d00-2589-11eb-9cd3-80ef903c25ec.png)

**Rating Scale (1 is minor, 7 is severe):**

1

**Context**

- Browser: Chrome

**Additional context**

**Comment by krivard** [comment]
This one seems to be back:

![image](https://user-images.githubusercontent.com/1158666/102228882-355b9b80-3eb9-11eb-8a43-2548d00ed4bb.png)

**Comment by sgratzl** [comment]
which version are you referring to? latest dev? cause it is not part of v1.11.1

**Comment by krivard** [comment]
that's the live site

**Comment by sgratzl** [comment]
> that's the live site

the live version (v1.11.1) was just a patch release without any new features. This feature is going to be released soon.
