### ISSUE TITLE
Support 'as-of' in COVIDcast's "Export Data" tab

### ISSUE THREAD

**Issue by RoniRos** [cmu-delphi/www-covidcast#639]
Support 'as-of' in COVIDcast's "Export Data" tab.   This will improve its usefulness with very little effort.

**Comment by sgratzl** [comment]
does the CSV server supports this feature?

**Comment by RoniRos** [comment]
@capnrefsmmat , I think you put it together, no?

**Comment by capnrefsmmat** [comment]
I did. It doesn't currently support it, but adding the feature to the CSV server would be trivial, and would then just require Brian to redeploy it.

Specifically, this block just needs to also look for an `as_of` argument, defaulting to `None`, and then we just pass it to `covidcast.signal`: https://github.com/cmu-delphi/covidcast-csv-server/blob/1486db29b3e336ea3abd7269ecc10bc2cdaf0bc8/src/app.py#L44-L50

Then on the viz side, we have to figure out how to show it in the UI in a non-confusing way.

**Comment by capnrefsmmat** [comment]
See https://github.com/cmu-delphi/covidcast-csv-server/pull/18 for CSV server support.
