### ISSUE TITLE
Comprehensive, consistent labeling of Cases and Deaths re incidence/ratios/cumulative

### ISSUE THREAD

**Issue by dlaliberte** [cmu-delphi/www-covidcast#642]
(From https://github.com/cmu-delphi/www-covidcast/pull/633#issuecomment-728928669)
We should apply a similar strategy for labeling the Cases and Deaths indicator, regarding incidence/cumulative and counts/ratios (per 100,000), as described in #625, to all other places it is being used for mapTitleText in the description. So, that in the google doc it is actually an object with the four combinations which will be converted in code into a function based on the signal options object. This would extract the text constants similar to the other parts and also avoid that have a specific logic in the detailview

**Comment by tildechris** [comment]
@dlaliberte, can this issue be closed since the two referenced issues are done?

**Comment by dlaliberte** [comment]
Yes, it is done.  Thanks.
