### ISSUE TITLE
Add AS-IS disclaimer to map page

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#649]
As per updated guidance, we need to include this text some where on the maps page:

"The COVIDcast site content and Epidata API are provided on an AS-IS, AS-AVAILABLE basis and are not intended for diagnostic or treatment purposes, or for guidance on any type of travel.  Please refer to the Terms of Use."

**Comment by tildechris** [comment]
@Letsgohyde let's figure out where this should go from a UX perspective first.

**Comment by RoniRos** [comment]
4 point DingBats font?

**Comment by tildechris** [comment]
Let's go with option 1 here:

![image](https://user-images.githubusercontent.com/46794497/99970218-891b0f00-2d69-11eb-9b78-eedd5d616f85.png)

If it's not too much trouble, we'll add a method to dismiss it and set a cookie to remember that acknolegdement.

**Comment by sgratzl** [comment]
> If it's not too much trouble, we'll add a method to dismiss it and set a cookie to remember that acknolegdement.

should this be part of covidcast or the website?

**Comment by tildechris** [comment]
Covidcast.

Also the updated text is:

"The content of the COVIDcast site and Epidata API are subject to an AS-IS, AS-AVAILABLE basis and are not intended for diagnostic or treatment purposes, or for guidance on any type of travel. Please refer to the Terms of Use."
