### ISSUE TITLE
Support simple query strings

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-covidcast#651]
Right now, it appears that I have to use: 

https://covidcast.cmu.edu/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201120&signalType=value&encoding=color&mode=export

if I were to provide somebody a link, and want them to land on the "Export Data" tab.  A lot of this info in the query string seems unnecessary for this tab, and conceptually it seems like all that should be needed is: 

https://covidcast.cmu.edu/?mode=export

This brings me to the "Export Data" tab but then it hangs for me (nothing loads).  FWIW, seems like it attempts to bring up this page: https://covidcast.cmu.edu/?mode=export&sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201120&signalType=value&encoding=color

Can we support simple query strings like this one?  It would be great to do something similar for all the tabs: for each one, figure out the minimal amount of info that's needed to load this tab, and allow those query strings (rather than the full ones).

**Comment by tildechris** [comment]
Yeah, this has bothered me a bit also.  We can work on simplifying the query string scheme after this release.
