### ISSUE TITLE
Wide windows create excessive whitespace between columns in top10

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#657]
**Actual Behavior:**

In a wide window, the space between the Name and Population text in the Top-10 view is sufficiently greater than the space between two entries that it becomes difficult to identify rows.

**Steps to Reproduce the Bug:**

1. go to https://dev--cmu-delphi-main.netlify.app/covidcast/?sensor=doctor-visits-smoothed_adj_cli&level=county&date=20201126&signalType=value&encoding=color&mode=top10&region=42003
2. make window wider

**Expected behavior**

Columns should have a maximum width to preserve legibility of rows.

**Screenshots**

![image](https://user-images.githubusercontent.com/1158666/100626304-aa44a800-32f3-11eb-8ffb-56d4faa19399.png)

**Rating Scale (1 is minor, 7 is severe):** 1

**Context**

- Browser: Chrome 87.0.4280.67 on a Mac

**Comment by tildechris** [comment]
Closing this as obsolete since we're going to change how the top-10/compare modes work in the redesign.
