### ISSUE TITLE
1.11 Changelog should list new map signals

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#662]
**Actual Behavior:**

The release notes for 1.11 should describe the following signal changes:

* New Google Symptoms signal replaces old Google Health Trends signal
* New signal on bar visits from Safegraph added to map
* New signal on restaurant visits from Safegraph added to map
* "Away" signals from Safegraph replaced by smoothed versions to remove weekend effect

**Steps to Reproduce the Bug:**

1. go to https://github.com/cmu-delphi/www-covidcast/blob/release/v1.11.0/CHANGELOG.md

**Rating Scale (1 is minor, 7 is severe):** blocking; release should not go live with silent changes to how data is sourced

**Comment by tildechris** [comment]
I thought we needed an additional config change to enable new signals pulled from the metadata doc, but according to @sgratzl, any changes to the doc are reflected in the next build automatically.

This makes it a bit tougher to detect changes since we don't currently have a specific commit that tracks changes.  We could improve this in the next version.  Let's work on the actual release notes.

**Comment by tildechris** [comment]
## Signal Changes

* "COVID Searches on Google" is now "COVID Symptom Searches on Google".  For more details see: [`google-symptoms` `sum_anosmia_ageusia_smoothed_search`](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/google-symptoms.html) signal.
* New "Bar Visits" signal from Safegraph.  For more details see: [`safegraph` `bars_visit_num` and `bars_visit_prop`](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html#safegraph-weekly-patterns).
* New "Restaurant Visits" signal from Safegraph.  For more details see: [`safegraph` `restaurants_visit_num` and `restaurants_visit_prop`](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html#safegraph-weekly-patterns)
* "Away from home" signals replaced by smoothed versions to remove the weekend effect.  For more details see: [`safegraph` `full_time_work_prop_7dav` and `part_time_work_prop_7dav`](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html#safegraph-social-distancing-metrics)

**Comment by krivard** [comment]
👍
