### ISSUE TITLE
Population for HRRs shows as Unknown

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#664]
**Actual Behavior:**

In the main map display, when you hover HRRs, the tooltip says "Population: Unknown"

**Steps to Reproduce the Bug:**

1. go to https://dev--cmu-delphi-main.netlify.app/covidcast/?sensor=hospital-admissions-smoothed_adj_covid19_from_claims&level=hrr&date=20201118&signalType=value&encoding=color&mode=overview&region=42003
2. hover over an HRR
3. examine Population annotation

**Expected behavior**

We're probably missing a population file?

**Screenshots**

![image](https://user-images.githubusercontent.com/1158666/100760425-bf870880-33bf-11eb-8aef-167fdc938365.png)

**Rating Scale (1 is minor, 7 is severe):** 2, missing information handled reasonably is not a dealbreaker

**Context**

- Browser:Chrome 87.0.4280.67 on a Mac

**Comment by sgratzl** [comment]
is there a direct mapping of HRR to population? or does it need to be derived? I cannot find a mapping file here: https://github.com/cmu-delphi/covidcast-indicators/tree/main/_delphi_utils_python/delphi_utils/data
