### ISSUE TITLE
Top 10 mode second column y axis limits are wrong for cases

### ISSUE THREAD

**Issue by ggoslin** [cmu-delphi/www-covidcast#667]
**Steps to Reproduce the Bug:**

1. go to https://covidcast.cmu.edu/?sensor=hospital-admissions-smoothed_adj_covid19_from_claims&level=state&date=20201114&signalType=value&encoding=color&mode=top10&region=PA
2. add indicator: COVID cases
3. examine second column of graphs
4. select a new state
5. examine second column as they load

**Actual Behavior:**

* The y-axis is too large, much larger than the maximum value of the top 10 regions shown
* There are two numbers on the left and it's not clear which one is being shown in the graph
* while the new column is loading, the graphs show the correct y axis limits, but they immediately refresh to something huge and the lines get squashed
* if you select a new state, you can re-trigger the same bug

**Expected behavior**

Use y-axis limits that show the graphs for the regions on the screen.

It should be obvious what number is being plotted in the graph: incidence or cumulative

**Screenshots**

![image](https://user-images.githubusercontent.com/1158666/99597960-cf1d4f00-29c6-11eb-9aea-61401af2e183.png)

While loading:
![image](https://user-images.githubusercontent.com/1158666/99598409-79957200-29c7-11eb-8ac5-9336777fa157.png)

**Rating Scale (1 is minor, 7 is severe):** 3-4. It's not on the front page, and you have dig a bit to trigger it... but this does show up for cases, which seems like something we should display reliably.

**Context**

- Browser: Chrome

**Comment by dlaliberte** [comment]
This bug has been fixed in development, which will be pushed to release in the next day or so.
https://dev--cmu-delphi-covidcast.netlify.app/

**Comment by tildechris** [comment]
@dlaliberte which commit or PR fixed this?  It may not have made it into prod with this release if it came into dev after the cutoff.

**Comment by dlaliberte** [comment]
> @dlaliberte which commit or PR fixed this? It may not have made it into prod with this release if it came into dev after the cutoff.

It was part of fix for somewhat unrelated issues:  #617
