### ISSUE TITLE
Date range slider in the Detail view doesn't support touch or touch-dragging of the range

### ISSUE THREAD

**Issue by dlaliberte** [cmu-delphi/www-covidcast#675]
**Actual Behavior:**

When using a mobile device (or simulated with Chrome debugger), the touch event is ignored in the date range selector of the Detail view for indicators.

1. Open the Detail view for an indicator (by clicking the magnifier icon in the small multiples of the Map overview).
2. Touch around in the date range selector at the bottom of the Detail view and notice that nothing changes.
3. Try to touch and drag the gray region to move the date range.

**Expected behavior**

Touch events should work like click events here, as they (often) do elsewhere.
Some way to zoom in or out, as it does with the mousewheel, would be convenient as well.  E.g. dragging up or down.

**Rating Scale (1 is minor, 7 is severe):**

3. 
For mobile users, this inability to adjust the date range means the date range can not be modified at all.

**Context**

mobile devices, or anything with touch support and no mouse, such as a tablet.

**Additional context**

How many mobile or tablet users do we have?

**Comment by sgratzl** [comment]
note: the detail view is not available in mobile environments

**Comment by dlaliberte** [comment]
This might be not-too-difficult.  See https://github.com/vega/vega-lite/issues/4208

**Comment by sgratzl** [comment]
closing since the classic covidcast is outdated and thus not important anymore
