### ISSUE TITLE
Consider alternatives to line charts

### ISSUE THREAD

**Issue by dlaliberte** [cmu-delphi/www-covidcast#679]
The line charts used in the small multiples and Detail View are well known, but might not be the easiest to use for all users. Here (and in subsequent comments) are a few examples of some alternatives that we might consider.

**Colored vertical lines in the background, corresponding to each data value.**  

The line is drawn on top so you can see the correspondence with each value.

![image](https://user-images.githubusercontent.com/570125/101717310-0da9a500-3a6d-11eb-88a9-18e37244d505.png)

- This only works with one location per chart.  Multiple locations would have to be plotted in separate charts.  
- The color range for each indicator might be different, and it should correspond to the same range used in the map for that indicator.
- Showing the error band around the data point (see Covid-like symptoms) has no correspondence in the background color.
- Technical problem: there is no automatic way to set the width of each vertical line so that it fills the background.  The pixel width has to be computed from the total screen width divided by the number of values.

**Comment by dlaliberte** [comment]
Points colored by the same values.  When the adjacent values are close enough, this looks like a relatively solid line.  This could be used to create a colored "sparkline".

![image](https://user-images.githubusercontent.com/570125/101721269-8ca2db80-3a75-11eb-8dbc-7b9541e1b549.png)

- It is difficult to see the weekly cycles without the line.
- Creating a line that varies continuously in color doesn't seem possible.  It may be possible with discrete colors (I'll try that next), but should the color of the line before each point be based on the point, or the line after, or something else?

**Comment by dlaliberte** [comment]
**Colored bars**

This is kind of a hybrid of the colored background and colored points.


![image](https://user-images.githubusercontent.com/570125/101721828-d93ae680-3a76-11eb-98aa-18dd7d8360b4.png)

**Comment by dlaliberte** [comment]
In all these examples, I used the same color scheme, and let the colors scale automatically based on the values in this particular time range.  So the "People Wearing Masks" color varies more than it would if it were scaled to the baseline value of 0.  So this is a similar issue as auto-scaling the vertical axis to show more of the variance of the data.

**Comment by dlaliberte** [comment]
Here is a recent blog post about [alternatives to line charts for time series data](https://adroitinsight.com/6-alternative-visuals-to-line-charts-for-time-series-data/) which happens to use covid-19 cases as data.

**Comment by krivard** [comment]
Nice work. For "Colored vertical lines in the background," we probably don't need the y axis or the line overlay, which will save some vertical space and cognitive load. We'll also want to iterate on the color scheme, since darker values (in the HSV sense) tend to recede into the background, and that seems inappropriate for indicating larger/more-alarming quantities.

For "Points colored by the same values", have you tried (1) making the points rectangular, and (2) using stderr to calculate the height of the points, instead of adding error bars as an additional graphical feature? That might help simplify things visually.

**Comment by dlaliberte** [comment]
Here it is with **Rectangular points, with height based on error bars**, or square points for non-error bar data.


![image](https://user-images.githubusercontent.com/570125/101817582-90277880-3af0-11eb-86a5-98f7b415f3a8.png)

- For small error bars, it is difficult to tell the difference with no error bars.  In fact, I hadn't noticed that some of the indicators had error bars.

**Comment by dlaliberte** [comment]
> Nice work. For "Colored vertical lines in the background," we probably don't need the y axis or the line overlay, which will save some vertical space and cognitive load. We'll also want to iterate on the color scheme, since darker values (in the HSV sense) tend to recede into the background, and that seems inappropriate for indicating larger/more-alarming quantities.

Thanks.

Yes, we definitely would need to iterate on the colors.  And regarding saving some vertical space, if we truncated the vertical size to just where there is data, and then rescaled so that all charts had the same height, then we would effectively be zooming in on the data, and relying on the color to give the scale.  This suggests we would need to be careful about making the color scheme consistent across charts.   E.g. we would want to effectively invert the "People Wearing Masks" to be about "People NOT Wearing Masks", so dangerous values (whether high or low) are mapped to the dangerous end of the color spectrum.

Another variation that would be interesting to try is to rely on computing a moving average or trendline but not showing it directly. What we would draw is bars with a baseline on the trendline and extended to each data point, whether above or below, and colored as it is here based on the data values (rather than whether it is above or below the trendline).  Maybe this would alleviate some of the controversy over exactly which trendline we choose, since the dominant feature of the chart would still be the data values themselves.  And it would then make the weekly cycles more apparent.

**Comment by dlaliberte** [comment]
And here is the bars with baseline on a simple 7-day moving average:

![image](https://user-images.githubusercontent.com/570125/101823050-388d0b00-3af8-11eb-9fc3-b778afa3984b.png)

- Easy to see the weekly cycles
- Sometimes hard to tell which end of a bar is the data vs moving average.
- I neglected to show the error bars, but the gray area could be added easily.

**Comment by tildechris** [comment]
Can you prototype a one-dimensional plot like the nytimes viz:

![image](https://user-images.githubusercontent.com/46794497/101826840-8b1cf600-3afd-11eb-89af-23e6ab253b1e.png)

The advantage to a 1D approach is three fold:

* It fits neatly into a table
* Missing data is more cleanly visualized as missing bars
* It doesn't require a y-axis so clipping and ranging is less of an issue.  Sure an outlier could wash out everything else, but I think the mitigation strategies become simpler

Controversial opinion: if we are comparing more than two things, we should do so in a tabular format with a 1D plot.

**Comment by dlaliberte** [comment]
The first example is the 1D plot, but with the addition of the line overlay and axes, and taller than needed.  So you just want to see it without those additions?   Here it is, though I can't get rid of the vertical axis so easily (there are other parts of the chart spec that effectively add it back in - I'm sure we could hide if we take stronger measures).

![image](https://user-images.githubusercontent.com/570125/101834651-a0e3e880-3b08-11eb-8ae8-014923c6e207.png)

**Comment by dlaliberte** [comment]
At Raph's request, here is the closest I can come to filling the area under the line with a vertical gradient.

![image](https://user-images.githubusercontent.com/570125/101849912-b10ac080-3b26-11eb-8744-273a2b14d8f6.png)

- Technical problem: I don't think Vega or VegaLite supports more than 2 stops in the gradient definition.  This uses yellow-red.
- I could create my own gradient from the data and color scheme, but only by generating data points that correspond to each vertical position.

**Comment by Letsgohyde** [comment]
Thanks for putting this together, the bottom 4 charts really leverage the gradients, however when the line is less dramatic "People wearing masks" it's a bit distracting. Let's adjust the color that starts at the bottom to be almost white to reduce the color density on the page, but as we reach the top of the chart we can display the orange, I think that will reduce the cognitive load and guide users to the peaks :) 

![image](https://user-images.githubusercontent.com/7318770/101851317-29b25280-3b10-11eb-9c51-d1e3bd105d88.png)

**Comment by dlaliberte** [comment]
It turns out we *can* draw a gradient line, by using the area fill instead.

![image](https://user-images.githubusercontent.com/570125/101851318-5161e480-3b29-11eb-8568-29ec0631ce88.png)

- Note the few charts with only a thin gray line.  These have no error bar, and there is no easy way to specify a default pixel height of this gap, so I left it this way for now.

But we can fill the area between the moving average and the data value:

![image](https://user-images.githubusercontent.com/570125/101851619-e49b1a00-3b29-11eb-9de5-7084fd85336a.png)

**Comment by dlaliberte** [comment]
> Let's adjust the color that starts at the bottom to be almost white to reduce the color density on the page, but as we reach the top of the chart we can display the orange, I think that will reduce the cognitive load and guide users to the peaks :)

There is a technical limitation in Vega/VegaLite that only supports gradients (used for area fills) between 2 colors, so we can't go from white to yellow to red.   Ironically, they support color schemes with more stops, but they just don't let us define gradients for the area fill, as far as I can tell.  I'll keep looking though.

**Comment by philmcguinn** [comment]
This is awesome exploratory work! I like how it's developing, with my favorite so far being the gradient quoted below. (I hope that's not a massive quote but I'm new to GitHub so forgive me if it is). Other notes:

- In the most recent example, I think the different widths of the line when doing the gradient line is a bit confusing. This same comment from me goes for the others with 7 day moving averages
- I initially liked the dots, but they're kind of a mess when they're not near each other looking like a line
- The full colored background from the initial comment is a bit overwhelming for me.

Thank you Daniel for kicking this off, it's great to see the different possibilities.


> At Raph's request, here is the closest I can come to filling the area under the line with a vertical gradient.
> 
> ![image](https://user-images.githubusercontent.com/570125/101849912-b10ac080-3b26-11eb-8744-273a2b14d8f6.png)
> 
> * Technical problem: I don't think Vega or VegaLite supports more than 2 stops in the gradient definition.  This uses yellow-red.
> * I could create my own gradient from the data and color scheme, but only by generating data points that correspond to each vertical position.

**Comment by dlaliberte** [comment]
It turns out there is an easy way to get a gradient filled line of uniform thickness.  Not sure this is documented - I basically made it up and it worked.  

![image](https://user-images.githubusercontent.com/570125/101960348-3b116280-3bd5-11eb-8ce1-c24aa9ba2f1d.png)

- The color here happen to be what I as using in the multi-stop gradient.  Computing any gradient to correspond with any color scheme is possible, but it may require many stops to get a close enough approximation.

**Comment by Letsgohyde** [comment]
Wow, that's pretty cool looking, however i'd worry that the lower values become quite low contrast. For example: "COVID Indicator combo" is really hard to read when the line drops below .5

For "Restaurant Visits" it's must more readable. 

For "At away location 6hrs+" Almost looks like a mistake. 

Thanks for sharing these options, it's nice to know the limitations the gradients have when the data is variable.

**Comment by sgratzl** [comment]
closing for now, might reopen later if we decide to explore more in this direction
