### ISSUE TITLE
Survey Dashboard: Make question text smaller on mobile

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#697]
![cmu-delphi-main netlify app_covidcast_survey-results__date=20201222(Pixel 2)](https://user-images.githubusercontent.com/46794497/103220016-321ad380-48ed-11eb-9096-b9d28b7601b5.png)

The question text dominates the screen and the line length feels too short.  We should investigate making this a bit smaller.

**Comment by sgratzl** [comment]
closed via #700
