### ISSUE TITLE
Survey Dashboard: Add survey navigation on mobile

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#699]
Since we lose the page nav in mobile view can we give some way to move to the next question?  Perhaps something with the question number ( 2 / 13) and an up and down arrow.  Maybe even show the outline section?  

Like: "Social distancing. 5/17   ⇑   ⇓"

**Comment by sgratzl** [comment]
see also https://github.com/cmu-delphi/www-covidcast/pull/724

**Comment by sgratzl** [comment]
closing since the survey question area already exists

![image](https://user-images.githubusercontent.com/4129778/110782239-2ccff280-8267-11eb-9ad7-c622aea91433.png)

already exists
