### ISSUE TITLE
Date range cannot be changed

### ISSUE THREAD

**Issue by kenneth-lee-ch** [cmu-delphi/www-covidcast#720]
**Actual Behavior:**

I tried to change the data range for downloading bar visit data on a county-level here: https://delphi.cmu.edu/covidcast/export/, but it doesn't let me

**Steps to Reproduce the Bug:**

1. go to **https://delphi.cmu.edu/covidcast/export/**
2. Select Safegraph mobility data -> Bar Visits
3. Then try to change the date range

**Expected behavior**

I thought I could change the date range, but the date range doesn't change even I selected a different date. It is always fixed on 2020-12-13 to 2021-01-13

**Screenshots**

![Screenshot 2021-01-14 at 8 44 39 AM](https://user-images.githubusercontent.com/24616330/104621250-be92f900-5644-11eb-8d4f-1541b22e11d7.png)

**Rating Scale (1 is minor, 7 is severe):**

**Context**

- Browser: Chrome

**Additional context**

**Comment by sgratzl** [comment]
can you try with https://dev--cmu-delphi-covidcast.netlify.app/export/, please

**Comment by kenneth-lee-ch** [comment]
It works!

**Comment by sgratzl** [comment]
closing since already fixed in dev
