### ISSUE TITLE
Select counties under a specific state for data export

### ISSUE THREAD

**Issue by kenneth-lee-ch** [cmu-delphi/www-covidcast#721]
It would be great if I can select all the counties under a specific state without typing each one of the county names for exporting data.

**User story**

I tried to download all county-level data for California, but I had to manually type each county name...which was not a fond experience for me.

**Additional context**

**Comment by sgratzl** [comment]
related issue: https://github.com/cmu-delphi/delphi-epidata/issues/380

**Comment by krivard** [comment]
Hi Kenneth -- we have some plans in motion in the backend that will make it easier to support that kind of query, but they won't be completed for several weeks. In the meantime, if you are able to use the R or Python clients, there is a (terrible, but less terrible than typing in all the county ids by hand) workaround: fetch the data on all counties, then filter for the state prefix once you have all the data. County FIPS codes use the format XXYYY, where XX is the FIPS code for the state. You can see all state FIPS codes here: https://www.nrcs.usda.gov/wps/portal/nrcs/detail/?cid=nrcs143_013696

In R, that would be something like:

```
library(covidcast)
library(dplyr)
df <- covidcast_signal("fb-survey", "smoothed_wcli")
df_california <- filter(df, startsWith(geo_value, "06"))
```

the one major downside being that querying all counties for a large timespan will take ages for dense signals like cases/deaths and safegraph... but at least that's your _computer_ taking ages, and not requiring your attention.

**Comment by kenneth-lee-ch** [comment]
Hi Katie, I have been doing that since August last year. I write the data frame to a .csv. I didn't realize I can actually open an issue here until a week ago...

**Comment by tildechris** [comment]
> Hi Kenneth -- we have some plans in motion in the backend that will make it easier to support that kind of query, but they won't be completed for several weeks.

@krivard, is there an existing issue that we can link here to track that backend improvement?

**Comment by krivard** [comment]
https://github.com/cmu-delphi/delphi-epidata/issues/178
