### ISSUE TITLE
New release notification

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#733]
"As a user, it would be nice to know when a new release is made and what changes were included in the release without having to navigate to the release notes page."

Yesterday there was a discussion in deprecating signals and removing them from the map.  Currently there's no affordance given to the user on when and why that might happen.  This made me think we could show some sort of notification when there's a new release so that users could more easily discover changes.

We'd just need to ensure that this isn't too obtrusive; we're making releases weekly recently so I don't want users to get alert fatigue.

**Comment by sgratzl** [comment]
another thing to consider: release updates are only interesting for users that visited covidcast before. 

One possible approach: 
 * we use the localstorage to store which version of COVIDcast they are currently viewing
 * when the visit it again, we check whether it is showing a newer version, if so, we show some alert (https://getuikit.com/docs/alert) or notification (https://getuikit.com/docs/notification)

**Comment by tildechris** [comment]
I like this approach.  So we have the following cases:

1. If it's a new view, localstorage is empty so no version prompt is shown
2. If localstorage version = current version, no version prompt is shown
3. If localstorage version != current version, update and show prompt

This seems to prevent over-prompting.

**Comment by sgratzl** [comment]
wontfix?

**Comment by tildechris** [comment]
Let's close this as won't fix since this never had priority.
