### ISSUE TITLE
Make Automated Description downloads a manual process

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#735]
The Automated Description and Survey Dashboard files are hosted on Google docs so that they can be easily updated.  Currently these are pulled whenever a build is started.

To remove the dependency of a network call during the build and considering that these files will not receive a high-volume of edits in the future, let's move this generation process to a manual one.

Make a build script target that pulls the files and check in the text such that they can be merged in PRs like other code.

If it's straightforward, we could also generate a build warning saying that the local files are out-of-date with respect to the canonical versions, but this isn't strictly required since we can just add instructions to the documents themselves.

**Comment by sgratzl** [comment]
see #734
