### ISSUE TITLE
tooltips flicker when moving mouse off the chart to the right, and back again.

### ISSUE THREAD

**Issue by dlaliberte** [cmu-delphi/www-covidcast#739]
**Actual Behavior:**

Tooltips for the small multiples (also in top-10 and region details) flicker and remain partly obscured after moving the mouse off to the right of the chart and back over the chart.  Also happens when moving vertically off chart near the right end of the chart, followed by moving back onto the chart.

**Expected behavior**

Avoid flickering of tooltips.  Ensure they end up visibly placed without multiple redraws.

**Screenshots**

**Rating Scale (1 is minor, 7 is severe):**

3

**Comment by sgratzl** [comment]
can you add a screencast to illustrate the bug, please

**Comment by dlaliberte** [comment]
Here is a screencast of the bug, if I did it right:

http://somup.com/crnVoso7HD
