### ISSUE TITLE
Implement mobile layout for signals table

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#740]
Design spec in Figma: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1891%3A35617

In the mock you'll notice a placeholder for the intro summary, this is still being defined. 

Link to the WIP intro section: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1915%3A33950

**Comment by Letsgohyde** [comment]
Interactions for signals chart: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2032%3A44249

**Comment by sgratzl** [comment]
closing for now, since in staging
