### ISSUE TITLE
Mobile design: Overview summary v1

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#743]
The overview section is intended to inform the user quickly and concisely. Here is the v2 design for this section. https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=1936%3A7

Please leave feedback in Figma.

**Comment by Letsgohyde** [comment]
Here's the updated mock :) 
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2246%3A973
Zero state on page load:
![image](https://user-images.githubusercontent.com/7318770/108388272-509d9c80-71c3-11eb-8dbe-74965bc332e6.png)

on scroll. 
![image](https://user-images.githubusercontent.com/7318770/108388335-64490300-71c3-11eb-9617-0df7df4dd43a.png)

**Comment by sgratzl** [comment]
closing since http://dev--cmu-delphi-covidcast.netlify.app/summary is implemented
