### ISSUE TITLE
Location overview page - Design

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#744]
As a sophisticated data consumer, for any geography that I am interested in, I want to see:

- A short overview giving context to signal metrics at the current date
- Details listing all signals, and how they've changed over time
- A map & table listing all sub-geography, so that I can browse to finer-grained geography

**Comment by sgratzl** [comment]
closing since http://dev--cmu-delphi-covidcast.netlify.app/summary is there
