### ISSUE TITLE
Redesign: Single mobile view

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#750]
The [redesign](https://docs.google.com/presentation/d/1n7U0js9h5dslT-uD9t5A_oaF9Ljaztl939lVIbdbkAA/edit#slide=id.gba581b15bd_1_4) specifies a single layout as opposed to the tabbed layout (Map overview, Timelapse, Top 10, Region Details, Survey Results, Export Data, Release Log, Terms of Use).

We still need to expose links to the Survey Results, export data, release log and terms of use pages, but they can be logically separate and be linked in the hamburger menu.

Remove map overview, timelapse, top 10 and region details items in favor of a single mobile view.

**Comment by sgratzl** [comment]
closing since merged, for further changes we can open a new issue
