### ISSUE TITLE
Redesign: Intro click-through pop-up

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#751]
The [redesign ](https://docs.google.com/presentation/d/1n7U0js9h5dslT-uD9t5A_oaF9Ljaztl939lVIbdbkAA/edit#slide=id.gbba56e0776_0_216) specifies an initial full-screen pop-up that introduces the platform to the user.  We should only show this dialog to users one time.

![image](https://user-images.githubusercontent.com/46794497/108218747-f806ca80-7102-11eb-913d-b984c8b4d931.png)

The click-through consists of the following elements:

* The heading: "Explore COVIDcast Indicators"
* A geo search box
* Chips for previously searched for state and county locations a la covidactnow.
* A button for "Go to the national overview"

Then an introduction paragraph:

"COVIDcast provides real-time county-level indicators in the United States.  Our indicators include our national COVID survey, public experience, attitude, behavior, doctor's visits, hospital admissions, tests, cases and deaths."

Then some high-level metrics on our indicators:

* Z Survey Indicators
* X Public Behavior Indicators
* Y Early Indicators
* W Late Indicators

Finally, "In collaboration with Facebook, Google, Change Healthcare, and Quidel."

**Comment by tildechris** [comment]
@Letsgohyde, any additional design work should be attached to this issue.

**Comment by sgratzl** [comment]
see also https://deploy-preview-731--cmu-delphi-covidcast.netlify.app/landing/?date=20210213

**Comment by sgratzl** [comment]
should it be a popup or a landing page (as I designed it right now) which is forwarding to the actual content?

**Comment by tildechris** [comment]
> should it be a popup or a landing page (as I designed it right now) which is forwarding to the actual content?

I'll defer to you on the implementation details, but since we want it only to appear once for people, wouldn't it be easier to structure it as a pop-over?

**Comment by Letsgohyde** [comment]
![image](https://user-images.githubusercontent.com/7318770/108306657-7e51f980-7161-11eb-8fe8-66857c6e3eb4.png)
Hey @sgratzl - here's the figma mock: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2226%3A173

**Comment by Letsgohyde** [comment]
I've adjusted the layout to accommodate the density of content and chips :)

**Comment by Letsgohyde** [comment]
My thinking is that if we display "USA", "CA" and a county name we can drop the "NATIONAL OVERVIEW" button. thoughts?

**Comment by Letsgohyde** [comment]
@sgratzl let me know if you want me to export the band of color for the top of the pop over

**Comment by sgratzl** [comment]
> I'll defer to you on the implementation details, but since we want it only to appear once for people, wouldn't it be easier to structure it as a pop-over?

IMO we should keep it as two separate pages with two separate urls and don't restrict how often people see what. The landing page will be the official starting point whereas the overview will be the one what people will share/link/bookmark. The landing page has the advantage of a nice introduction + a clear search box. The overview page shows you the data. Moreover, I can imagine that we want to add more text to the landing page sooner or later. 

In addition, if the popup is only showing once to a user on his/her initial view, how can be there previously selected counties/states to show?

> My thinking is that if we display "USA", "CA" and a county name we can drop the "NATIONAL OVERVIEW" button. thoughts?

aren't USA, CA and the county based in the previous input by a user. So in the first view it won't have any chips. Therefore, I would keep the second button.

**Comment by sgratzl** [comment]
> @sgratzl let me know if you want me to export the band of color for the top of the pop over

yes please, please make sure that it will also look ok on non-mobile devices

**Comment by Letsgohyde** [comment]
![image](https://user-images.githubusercontent.com/7318770/108395090-4632d100-71ca-11eb-8656-c9684e9fb6ca.png)
updated buttons changes

**Comment by Letsgohyde** [comment]
Hey @sgratzl here's a side by side with some feedback on the current implementation, great work so far, thanks a lot :) 
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2280%3A59772
![image](https://user-images.githubusercontent.com/7318770/108435344-1a314300-71fe-11eb-9d90-61d106a8cade.png)

**Comment by Letsgohyde** [comment]
mobile color stripe above intro page. 
![image](https://user-images.githubusercontent.com/7318770/108566711-b705e600-72bb-11eb-8e3a-281f6907fc94.png)

Full screen / desktop: 834px
![image](https://user-images.githubusercontent.com/7318770/108567994-241a7b00-72be-11eb-8410-74f9107268c1.png)

**Comment by sgratzl** [comment]
closing since merged, for further changes we can open a new issue
