### ISSUE TITLE
Redesign: Indicator Overview Page

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#752]
As per the [redesign](https://docs.google.com/presentation/d/1n7U0js9h5dslT-uD9t5A_oaF9Ljaztl939lVIbdbkAA/edit#slide=id.gba581b15bd_1_4), at the national level and for each geographical region, we should have an overview page which contains an overview section and the indicators table.

The header of this page should contain the geo and date selector widgets.

## Overview

[TODO design screenshot]

* We should display cases and deaths per capita rates, and their change in the past 7 days
* A small map showing cases rates
* An indicator summary paragraph, "Across all top-level indicators, X are trending worse (-Z% in the past 7 days) and Y are trending better (+W% in the past 7 days)

## Indicators Section

[TODO design screenshot]
![image](https://user-images.githubusercontent.com/46794497/108225299-ce9d6d00-7109-11eb-998b-e63654227b88.png)

At the top of the indicators section, there should be a indicator filter, which will filter indicators by type (Behavior, Early, Late, National COVID Survey)

Next is the indicator table, containing columns:

* Indicator name: Name and an arrow which affords to the user that more details can be shown
* Change last 7 days
* Per 100K
* Trend: a sparkline with a red line indicating the selected data

## Indicator summary

This will be broken out into a separate issue.

**Comment by tildechris** [comment]
@Letsgohyde additional design assets should be attached to this issue.

**Comment by sgratzl** [comment]
>     * Per 100K

for most indicators we have percentages not `per 100k` values

**Comment by sgratzl** [comment]
see also https://deploy-preview-731--cmu-delphi-covidcast.netlify.app/mobile/?date=20210213

**Comment by Letsgohyde** [comment]
Hey @sgratzl here's the updated indicators table with the right arrow added to the row. 
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2158%3A52915
![image](https://user-images.githubusercontent.com/7318770/108389252-58aa0c00-71c4-11eb-8e5e-60b7269190ca.png)

and when the dropdown filter is selected display the different sources. 
![image](https://user-images.githubusercontent.com/7318770/108389313-68295500-71c4-11eb-9311-c1c6a7f4818f.png)

**Comment by Letsgohyde** [comment]
Hey @sgratzl - I'm going to screenshot the current implementation and leave feedback in Figma so we can keep a dialog going. I've copied the current design next to the current implementation so we can see them side by side. 

Follow this link and turn on comments : https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2280%3A59198

great work so far, hope this feedback helps.

**Comment by Letsgohyde** [comment]
Screenshot of the side by side :) 
![image](https://user-images.githubusercontent.com/7318770/108435397-3208c700-71fe-11eb-9236-ef2bf0e928da.png)
