### ISSUE TITLE
Redesign Spec: Indicator Detail Page Design

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#753]
After the use click on an indicator in the indicator table, they will be shown the indicator detail page, which has three parts:

* A drop down selection similar to geo and date pickers, that allows easy navigation between indicators
* Combo map/timeseries
* Trend details section
* Geo tables
** Comparison table: contextualize this region vs. other nearby and national numbers
** Sub-geo table: e.g. for states list counties so that people can drill down

**Comment by sgratzl** [comment]
closing since https://dev--cmu-delphi-covidcast.netlify.app/indicator/? is implemented
