### ISSUE TITLE
Redesign: Metric context format

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#754]
When presenting a metric, e.g. case incidence per 100K, we should present it with the following data points.

* Metric itself e.g.: Cases 
* A general indication of the recent trend: better, worse, stable
  * Here we apply the "normalized trend algorithm" (defined below) to classify the trend.
* A percent difference from the last 7 days
  * `(value/lag(value,y))-1`
* A percentage difference from the worst value (max or min depending on indicator)
  * `(value/max(value,y))-1` 
  * Including the max

For example:

On 2021-02-20 Cases were 30.2 per 100K, trending better, -31% past 7 days, -65% from the worst value of 83.1 per 100k on 2020-12-16

**Note**: This is just a spec of the data points, and the order that flows nicely, not necessarily how it should be laid out on the page design wise.

## Unit conventions

Always use "per 100" and "per 100K" units, only using "%" when we are specifically talking about relative change.

### Motivation

All units in the front-end are expressed in terms of % of population, either per 100 or per 100,000.  Using percentages for per 100 is problematic when we also want to show relative percentage change.  For example, if an indicator moves from 75 to 85 per 100, it is a 11% change or a 10 percentage point change.  It would be confusing to say 75% up 11% to 85%.

If absolute change is expressed, use the same unit since there is no word for "percentage point" when the base unit is per 100K.  For example, 25 per 100K up *5 per 100K* from 20 per 100K or up 20%.

## Normalized Trend algorithm

What is significant is different on a per-indicator basis.  For example, a 5% change in cases isn't changing very much, but in mask wearing %, going from 85% to 90% indicates a big social change.

If we first normalize the indicator between 0 and 1 over a period of 4 month, we get an idea of the domain that the signal is moving in.  We can then apply a simple 7 day % diff classification.  If `value` is our original metric and `value_norm` is the normalized metric, we can classify via:

```
one_week_diff = (value_norm/lag(value_norm, 7 days))-1
If 
  one_week_diff is greater than 10%, then "Better"
  one_week_diff is worse than 10%, then "Worse"
Otherwise 
  "Steady"
```

If we apply this algorithm, we can do better than the simple 7 day percentage difference classification:

![image](https://user-images.githubusercontent.com/46794497/109068835-64169f00-76be-11eb-8afb-47a2f4c3f36d.png)

Note: we don't actually surface the normalize value, or the normalized % diff anywhere in the UI, we just use it in order to classify the movement trend.

**Comment by tildechris** [comment]
We considered smoothing the normalized trend series, but for non-smoothed signals like bars and restaurants, the result is significantly worse because the 7 day trend can disagree with the trend classification.

**Comment by tildechris** [comment]
@Letsgohyde once implication of this is that there is both a trend indicator (Better/Worse/Steady) _and_ a sign indicator on the 7 day trend e.g. better by -10%.  Can we make the trend visually distinct from the 7 day trend sign?

**Comment by tildechris** [comment]
We can apply this to the metric card, and not necessarily to the indicator table, which trend classification, 7 day percentage change, and the sparkline.  E.g. without the max value.

**Comment by sgratzl** [comment]
> A percent difference from the last 7 days
> 
>     * `(value/lag(value,y))-1`

what is the percentage difference of two percentage values? or how make we clear which one is which.

**Comment by sgratzl** [comment]
what is missing for this issue to be closed?

**Comment by tildechris** [comment]
I added the context from our %-change conversation.  Capturing that and your work in #802 this can be closed as complete.
