### ISSUE TITLE
Design warning for depreciated questions / signals  

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#756]
- [x] Add a warning to the chart that will be depreciated

**Comment by Letsgohyde** [comment]
Hey @sgratzl and @tildechris what do you guys think about this kind of warning message for the indicators that are scheduled for removal? 
![image](https://user-images.githubusercontent.com/7318770/109891619-3b525480-7c3e-11eb-9f2a-9d73e0fa1b64.png)

Link to figma mock: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2013%3A2136

**Comment by capnrefsmmat** [comment]
Hmm. We need some way to indicate that the indicator is being replaced with another one, not just removed, and some way for people to see old and new data together. So I think the label is good, but how do you want to show users which indicator replaces this one?

Here's a concrete example. The "In the past 5 days, did you wear a mask most or all of the time in public?" indicator is being replaced with "In the past **7** days, did you wear a mask most or all of the time in public?" It's a minor difference and the values will be similar. We can direct them to the updated chart. Maybe the text could say "Indicator replaced, March X, 2021" and give a link to the other one.

Another example: "In the past 24 hours, did you go to a bar, restaurant, or cafe?" will be replaced with, "In the past 24 hours, did you have a drink or meal indoors at a bar, restaurant, or cafe?" Now it's indoors specifically. Maybe the text can say "Removed from the survey, March 2, 2021", and it can be displayed near (or below, or something) the newer signal, so people can see what it was replaced with.

**Comment by tildechris** [comment]
I like the visual style, but to Alex's point, yes, let's add an anchor link to the new signal.  How about `This indicator was replaced in [revision x](link to revisions page) with a [new indicator](link to new indicator on page)`

**Comment by Letsgohyde** [comment]
Thanks guys, these details really help me understand the context. 

Chris, I like the string you proposed. here's a mock
![image](https://user-images.githubusercontent.com/7318770/111005217-3d539c00-833f-11eb-9ab4-e1e72b4da511.png)

**Content spec:** 
1. Icon: Alert triangle
2. Header: UPDATE!
3. Copy: This indicator was replaced in [revision x] link to revisions page with a [new indicator] link to new indicator on page.

Version for indicators that will be removed and NOT replaced: 
![image](https://user-images.githubusercontent.com/7318770/111005140-1b5a1980-833f-11eb-9507-70129ecc2e27.png)

**Content spec:** 
1. Icon: Alert triangle
2. Header: UPDATE!
3. Copy: This indicator will be deprecated in ‘x’ days/weeks”. We will stop asking this question on [date]. Link to revision page

Figma mock: 
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2650%3A0

**Comment by tildechris** [comment]
This still feels a little disjoint.  Can we show the new and old question in the same card?  To Alex's point, we're mostly asking the same thing with different wording.

Perhaps hide the old question data by default, and expand it open if the user wants to look at it?

**Comment by sgratzl** [comment]
current proposal:
![image](https://user-images.githubusercontent.com/4129778/111358996-5cb13880-8661-11eb-834f-e38297ef2a09.png)
