### ISSUE TITLE
N/A Sorting in tables

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#761]
When displaying sortable tabular data, there may be rows whose values are "N/A".  When these values are sorted, they should always sort to the bottom of the table.  That is to say, "N/A" is always less than any other value when sorting descending, and always greater than any other value when sorting ascending.

**Comment by sgratzl** [comment]
isn't that what is already doing?:

e.g. go to https://dev--cmu-delphi-covidcast.netlify.app/indicator/?date=20210224&region=CA&sensor=fb-survey-smoothed_cli and sort by value

**Comment by tildechris** [comment]
I would expect never to see a "N/A" when sorting at the top of the table unless we're doing the table's "natural" sort which I would guess is alphabetical?  E.g. Yuba county shouldn't be at the top:

![image](https://user-images.githubusercontent.com/46794497/109525681-c6d1b700-7a7f-11eb-8865-2e434bd20b49.png)
