### ISSUE TITLE
Add special case for max value days

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#764]
![image](https://user-images.githubusercontent.com/46794497/109660867-55553f80-7b37-11eb-8375-b5b72f143502.png)

We should detect "worst" value dates, and instead say something like: "On Thu Feb 25th, COVID-Related Doctor Visits 61.39% was the 4 month worst value, compared to the best value of XX.XX% on Y date."

**Comment by sgratzl** [comment]
can you post the URL (geo) that you used for easier testing, please

**Comment by tildechris** [comment]
I was looking at https://deploy-preview-765--cmu-delphi-covidcast.netlify.app/indicator/?region=42003&date=2021022, which shows a bug in the CHGN smoother.

But you can also use cases: https://delphi.cmu.edu/covidcast/?date=20201216&region=42003
