### ISSUE TITLE
Survey dashboard consistently defaults to several weeks ago

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#788]
**Actual Behavior:**

When I open https://delphi.cmu.edu/covidcast/survey-results/, without having viewed any other COVIDcast page first, the dashboard currently defaults to 2021-02-21, despite the survey data being available (for nearly every signal) up to a few days ago.

This is particularly odd because I can't see any other signal on the dashboard that has an end date of 2021-02-21, so I don't know where the date came from.

**Expected behavior**

The dashboard should show the date as the most recent date the survey data is available.

**Comment by sgratzl** [comment]
taking a look at https://api.covidcast.cmu.edu/epidata/api.php?source=covidcast_meta&signals=fb-survey%3Asmoothed_wearing_mask that is what the meta data is reporting

![image](https://user-images.githubusercontent.com/4129778/110350573-260d6980-8034-11eb-82c9-2e2bac290e27.png)
