### ISSUE TITLE
Table headers are not hyperlinks, but use hyperlink coloring

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#789]
On page: https://staging.delphi.cmu.edu/covidcast/indicator/?date=20210221&region=VA&sensor=safegraph-bars_visit_prop

The table headers:

```
COUNTY | CHANGE LAST 7 DAYS | PER100K | HISTORICAL TREND
```

Are colored blue, but don't seem to be hyperlinks.

![image](https://user-images.githubusercontent.com/1158666/110346931-0f4c2000-7ffe-11eb-99af-792a7d8300be.png)

**Comment by sgratzl** [comment]
closing, I changed it back to black like the other table headers:

![image](https://user-images.githubusercontent.com/4129778/110782504-81736d80-8267-11eb-85c6-1e14f5cdd986.png)
