### ISSUE TITLE
Handling of N/As in sentence templates

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#790]
When data is unavailable, the automatically-constructed sentences behave oddly. Using "?" instead of numbers is better than crashing, but it would be clearer to use a different sentence construction.

When no data at all are available over the 4-month period, such as the following, something like "We don't have data on the historical context for this signal" might be appropriate.

https://staging.delphi.cmu.edu/covidcast/indicator/?date=20210221&region=51001&sensor=safegraph-bars_visit_prop

![image](https://user-images.githubusercontent.com/1158666/110347276-71a52080-7ffe-11eb-937e-ba2b374c35df.png)

When historical context is available but we don't have data for the currently selected date, such as the following, some options are:
- use the most-recently-known value in all constructions 
- add a second set of constructions using the most-recently-known value
- reuse "We don't have data on the historical context for this signal" from the no-data-at-all case

https://staging.delphi.cmu.edu/covidcast/indicator/?date=20210221&region=42019&sensor=fb-survey-smoothed_wearing_mask

![image](https://user-images.githubusercontent.com/1158666/110347899-13c50880-7fff-11eb-95b7-a09b2cf3b60d.png)

**Comment by sgratzl** [comment]
current state: 
e.g. https://dev--cmu-delphi-covidcast.netlify.app/indicator/?date=20210303&sensor=safegraph-bars_visit_prop

![image](https://user-images.githubusercontent.com/4129778/110806582-7f6ad800-8282-11eb-97a5-a80933398f63.png)

what do we wanna change besides that?

**Comment by sgratzl** [comment]
closing for now, let's keep this "We don't have data on ..."
