### ISSUE TITLE
Error Occurred when selecting "Show US Counties as Choropleth Map"

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-covidcast#801]
https://dev--cmu-delphi-covidcast.netlify.app/overview/?date=20210305

![image](https://user-images.githubusercontent.com/46794497/110646475-eb671680-8184-11eb-8c02-06035363041b.png)

From the network traffic it looks like a 404 to shape files:

![image](https://user-images.githubusercontent.com/46794497/110646560-fe79e680-8184-11eb-8620-9ce96e5607db.png)

**Comment by sgratzl** [comment]
/overview doesn't exist anymore. Can you try again?

**Comment by tildechris** [comment]
I can't reproduce now.  Perhaps it was because of a stale resource.  Closing.
