### ISSUE TITLE
Calendar widget appears hidden on mobile

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#816]
Current implementation: 

When opening the cal on mobile: 
<img width="384" alt="Screen Shot 2021-03-11 at 1 19 55 PM" src="https://user-images.githubusercontent.com/7318770/110856505-94d50780-826c-11eb-9f84-a8712b55cd94.png">

when scrolling down with cal open:
<img width="382" alt="Screen Shot 2021-03-11 at 1 20 02 PM" src="https://user-images.githubusercontent.com/7318770/110856565-a6b6aa80-826c-11eb-9c4a-fee8217eb3d2.png">

Proposed fix: 
1. Calendar should display entire widget, sticky to the top bar. 
2. Calendar sticks to top bar till date is selected or closed. 

Mock coming soon.

**Comment by Letsgohyde** [comment]
**Proposed design:** 

1. Display calendar widget below the input fields. 
2. Apply 1px border between inputs and calendar widget.  
2. Apply background overlay when calendar widget is active. 

<img width="477" alt="Screen Shot 2021-03-12 at 12 51 27 AM" src="https://user-images.githubusercontent.com/7318770/110916195-650a1c00-82cd-11eb-9a09-ea1bc0c63aee.png">

**Comment by sgratzl** [comment]
part of #820
