### ISSUE TITLE
SafeGraph bar/restaurant signals claim to be 7-day averages but aren't

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#825]
**Actual Behavior:**

The SafeGraph bar and restaurant signals provided by the API [are daily signals](https://cmu-delphi.github.io/delphi-epidata/api/covidcast-signals/safegraph.html#safegraph-weekly-patterns); AFAIK there are no 7-day smoothed versions. But the interface says this:

<img width="819" alt="Screen Shot 2021-03-16 at 9 47 58 PM" src="https://user-images.githubusercontent.com/711629/111402258-475bfe80-86a1-11eb-97be-0646b9e3fc54.png">

It's easy to spot that it's not true, because there's a 7-day pattern with spikes on Saturday. That wouldn't happen in 7-day average data.

**Steps to Reproduce the Bug:**

1. https://dev--cmu-delphi-covidcast.netlify.app/indicator/?date=20210307&sensor=safegraph-bars_visit_prop

**Expected behavior**

Either it doesn't say 7-day average or we get engineering to make an averaged signal.

**Comment by capnrefsmmat** [comment]
I guess I'm actually in favor of replacing these signals with the ones from the survey, which are more interpretable (% of population, instead of counts out of a SafeGraph panel of unknown size) and easier to explain. I can propose the changes to the signal doc if people agree.

(We'd keep the SafeGraph At Away Location signals, just replace the bar & restaurant ones)

**Comment by tildechris** [comment]
> (We'd keep the SafeGraph At Away Location signals, just replace the bar & restaurant ones)

Agree.
