### ISSUE TITLE
Consider some structure, text updates in "Indicator Summary"

### ISSUE THREAD

**Issue by philmcguinn** [cmu-delphi/www-covidcast#852]
Right now the indicator summary is one long paragraph, but has three statements that I propose would be better off separated, like in a bulleted list. For example, this summary:
![Screen Shot 2021-03-22 at 1 23 38 PM](https://user-images.githubusercontent.com/71901127/112053804-0c7b2000-8b12-11eb-8676-a9b7e07ec9ba.png)

I suggest something like this:

- 4 out of 14 indicators are getting better ("Indicator 1", "Indicator 2", "Indicator 3", "Indicator 4")
- 6 out of 14 indicators are getting worse ("Indicator 1", "Indicator 2", "Indicator 3", "Indicator 4", "Indicator 5", "Indicator 6")
- 4 out of 14 indicators are not available for [date] ("Indicator 1", "Indicator 2", "Indicator 3", "Indicator 4")

**Comment by sgratzl** [comment]
@Letsgohyde opinions?

**Comment by sgratzl** [comment]
wontfix, since removed in v3
