### ISSUE TITLE
Communicate data freshness on COVIDcast pages

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#858]
**Problem**
Data is always a few days behind for a variety of reasons. Note the image, our most recent data is from 4 days ago.
<img width="856" alt="Screen Shot 2021-03-24 at 11 55 32 AM" src="https://user-images.githubusercontent.com/7318770/112368064-ea130f00-8c97-11eb-8c87-5e66c7330894.png">

**Solution**
1. Add a dismissible banner on the "COVIDcast Overview" page 
<img width="1097" alt="Screen Shot 2021-03-24 at 11 54 10 AM" src="https://user-images.githubusercontent.com/7318770/112368270-20508e80-8c98-11eb-8452-3d32ada12ab0.png">

Copy: 
Header: "Data freshness" 
"We aim to update our data daily at [time]. Due to lag and delays from our sources, some data may be a few days behind." [Dismss] 

2. Add copy within the calendar picker
<img width="975" alt="Screen Shot 2021-03-24 at 11 46 28 AM" src="https://user-images.githubusercontent.com/7318770/112368774-abca1f80-8c98-11eb-9300-232f18b2aa3b.png">

3. Add a note below time series charts. 
<img width="669" alt="Screen Shot 2021-03-24 at 11 48 47 AM" src="https://user-images.githubusercontent.com/7318770/112368883-cb614800-8c98-11eb-99da-89441e7b5160.png">

Example from CovidActNow.org:
<img width="919" alt="Screen Shot 2021-03-24 at 11 50 06 AM" src="https://user-images.githubusercontent.com/7318770/112368974-e59b2600-8c98-11eb-9802-a2b651e4c1f6.png">
<img width="333" alt="Screen Shot 2021-03-24 at 11 58 23 AM" src="https://user-images.githubusercontent.com/7318770/112369017-f77cc900-8c98-11eb-8b59-d045f39dbd0a.png">

**Comment by Letsgohyde** [comment]
@sgratzl What do you think of CovidActNow's approach to this issue?

**Comment by sgratzl** [comment]
I would put a generic text (the time is not the same for different indicators) under the calendar as suggested and similar to 

![image](https://user-images.githubusercontent.com/4129778/112373066-ee025980-8cb6-11eb-8eed-f29d8512fcad.png)

inline when the date is mentioned the first time: `On Sat, Mar 20th 2021 (i) the 7 day averages were:`

I wouldn't add it to the line chart since I don't see much gain of adding another disclaimer text
