### ISSUE TITLE
Signals Dashboard UI

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#859]
**v2 design for dashboard**
Overview tab
![delphi-covidcast_signal-dash_3 3 21_v2](https://user-images.githubusercontent.com/7318770/112379895-f0a88300-8ca5-11eb-81a3-3b211b80d91c.png)

Signal status tab/ zero-state: Select a signal to load data
![delphi-covidcast_signal-dash_3 3 21_v2](https://user-images.githubusercontent.com/7318770/112379998-0f0e7e80-8ca6-11eb-9d95-47b20293fc1a.png)

Signal status tab / signal selected w/ charts loaded
![delphi-covidcast_signal-dash_3 3 21_v2-1](https://user-images.githubusercontent.com/7318770/112380079-2f3e3d80-8ca6-11eb-8622-e125e1d9f7b5.png)

**Comment by Letsgohyde** [comment]
**Link to figma designs**
https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2700%3A0

**Link to proto**
https://www.figma.com/proto/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2700%3A0&scaling=min-zoom

**Comment by Letsgohyde** [comment]
Link to signals dash deck: https://docs.google.com/presentation/d/1k61NFrHFzd91t1L8CZapwqzcG1iX4ir3lp-UqS6kVMo/edit#slide=id.p

**Comment by sgratzl** [comment]
closing since released
