### ISSUE TITLE
Expanded timescale timeseries view

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#897]
Request from @RoniRos: 

> It would be great if it were possible to see a time series from the beginning of the pandemic till now.

**User story**

* As a data power user, 
* I want to see a time series with expandable or expanded x-axis limits, 
* so that I can answer simple research questions about how an indicator has progressed over the full course of the pandemic, without having to write my own custom code

**Additional context**

One way to do this would be to bring up an overlay which full-screens the timeseries, a la the classic map. 
* Is it easy to lift that code?
* How do we wanna activate this view -- click the timeseries? add an icon/link?
* Should this work on mobile (using landscape probably), or just desktop?

Some other approaches, though these all seem more complicated:
* let the user expand backwards/forwards in time directly from the main time series display
* let the user set a global viewing start date or time range in addition to setting the selected date

**Comment by Letsgohyde** [comment]
Hey Kate, per the expand the chart behavior, here are a few patterns that transition the time series from smaller to larger. 
Google Finance: change the duration with chips 
<img width="831" alt="Screen Shot 2021-04-09 at 2 45 15 PM" src="https://user-images.githubusercontent.com/7318770/114233246-a4666f80-9942-11eb-98a8-13d303ccd8b6.png">

Fidelity trading platform
<img width="548" alt="Screen Shot 2021-04-09 at 2 46 25 PM" src="https://user-images.githubusercontent.com/7318770/114233276-adefd780-9942-11eb-8385-ddb6b5d59ad1.png">

Enlarged view "Advanced chart" 
<img width="1792" alt="Screen Shot 2021-04-09 at 2 48 58 PM" src="https://user-images.githubusercontent.com/7318770/114233347-c2cc6b00-9942-11eb-808d-15a246ac5316.png">

Robinhood trading platform
<img width="783" alt="Screen Shot 2021-04-09 at 2 47 12 PM" src="https://user-images.githubusercontent.com/7318770/114233367-ce1f9680-9942-11eb-817b-0c66f8587245.png">

Enlarged view
<img width="1792" alt="Screen Shot 2021-04-09 at 2 47 27 PM" src="https://user-images.githubusercontent.com/7318770/114233379-d37ce100-9942-11eb-8096-821380972408.png">

How do you guys feel about these patterns?

**Comment by krivard** [comment]
I like the Google Finance chips, but I don't think we need that yet -- for now let's go with the straight-up show all dates slider and we can revisit later if we need more options.
