### ISSUE TITLE
Support neutrality in the survey dashboard

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#902]
For some survey indicators, it's not clear whether increases are good or bad, or that involves a value judgment we don't want to make. For instance, if a measure of in-person schooling increases, that's good (more kids in school) but also bad (more opportunities for transmission, although evidence suggests transmission may be limited). Similarly, once people become vaccinated, an increase in mobility may not be bad, since it's done safely.

**User story**

I view an indicator and for each of these items, it shows the trend but doesn't render judgment on whether it's good or bad:

* color coding - easy
* trend indication (red/green) -> neutral color
* trend text: this is XXX better than the worst value on ... we start to rephrase that such that is the "lowest" and "highest" value without a classification

**Comment by sgratzl** [comment]
should we use a third color scheme in case we show this signal in a map?

**Comment by capnrefsmmat** [comment]
I guess so; maybe a gradient of blue or some other neutral color?

**Comment by sgratzl** [comment]
looking at https://github.com/d3/d3-scale-chromatic#sequential-single-hue

we could use:

![image](https://user-images.githubusercontent.com/4129778/115028673-24389080-9e93-11eb-8c28-ec75fe71658c.png)

we don't have these colors yet

**Comment by capnrefsmmat** [comment]
That looks fine to me
