### ISSUE TITLE
COVIDcast 2.3.0 release design feedback

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#912]
Design is looking great, left a few spacing and label change requests in Figma. https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2838%3A71260

1. Open figma file: https://www.figma.com/file/IiYu74VmEi4GVS4bnYaTd6/Delphi-Site-Redesign?node-id=2838%3A71260
2. press "C" to turn on comments
3. Review all Comments CC'd to Sam. 

Please leave any comments in the Figma file to keep the convo in context, thanks a lot :)

**Comment by Letsgohyde** [comment]
Spacing improvements: 
<img width="1646" alt="Screen Shot 2021-04-16 at 12 54 34 PM" src="https://user-images.githubusercontent.com/7318770/115077567-23175b80-9eb3-11eb-93cc-e541f394b1da.png">
<img width="1795" alt="Screen Shot 2021-04-16 at 12 54 43 PM" src="https://user-images.githubusercontent.com/7318770/115077570-24488880-9eb3-11eb-998b-98c85abbfd9f.png">
<img width="979" alt="Screen Shot 2021-04-16 at 12 54 59 PM" src="https://user-images.githubusercontent.com/7318770/115077574-2579b580-9eb3-11eb-8e99-19bba6b88fdd.png">
<img width="996" alt="Screen Shot 2021-04-16 at 12 55 03 PM" src="https://user-images.githubusercontent.com/7318770/115077578-27437900-9eb3-11eb-817e-bfd8283848de.png">
<img width="687" alt="Screen Shot 2021-04-16 at 12 55 10 PM" src="https://user-images.githubusercontent.com/7318770/115077580-27dc0f80-9eb3-11eb-805e-ff71d5fbb0fe.png">

**Comment by sgratzl** [comment]
@Letsgohyde you mentioned that you wanna take a look at it yourselves?

**Comment by sgratzl** [comment]
> @Letsgohyde you mentioned that you wanna take a look at it yourselves?

ping

**Comment by sgratzl** [comment]
wontfix
