### ISSUE TITLE
Backfill page design feedback

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-covidcast#932]
- [ ] 1. Apply even margin between inputs
- [ ] 2. Update inputs to be equal width 
- [ ] 3. Left align region input with location input at the top of the page. 
<img width="1592" alt="Screen Shot 2021-05-07 at 1 21 15 PM" src="https://user-images.githubusercontent.com/7318770/117504394-390ac000-af37-11eb-8fce-4871779d57d9.png">

- [ ] 4. Spacing improvements 
- [ ] 5. Center "Change Value Completeness per Lag by weekday" chart on page
<img width="1659" alt="Screen Shot 2021-05-07 at 1 24 57 PM" src="https://user-images.githubusercontent.com/7318770/117504638-a3236500-af37-11eb-85b2-c1eb68ffd8d1.png">

@sgratzl Is it possible to make the "Change Value Completeness per Lag by weekday" chart the same width as the "CHANGE COUNTY COVERAGE" chart above?

**Comment by sgratzl** [comment]
closing for now since the overall layout of the page has changed
