### ISSUE TITLE
Track viz dashboard usage in google analytics

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#939]
It would be great if we could use google analytics to track:
* [P0] which indicators are most & least used
* [P1] which widgets are most & least used
* [P1] which time range types (4-month/configured/specify) are most & least used
* [P1] (for "specify") how far back in time users frequently view (this might be hard -- I'm not sure what is possible here, but I can easily envision a distinction between users interested in long-range patterns and users interested only in the most recent data)

**User story**

Tracking this information will help Delphi continuously evaluate which indicators and visualizations are most useful to our users, which will in turn help us prioritize maintenance effort. 

**Additional Context**

Proposed event category/action/labels TBD

**Comment by sgratzl** [comment]
#940 is tracking all the picked options (widgets, sensor, ...) in google analytics. Once it is deployed at the live site we can see whether we can add the mentioned questions

**Comment by sgratzl** [comment]
wontfix
