### ISSUE TITLE
Changes in survey dashboard and map for survey Wave 11

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/www-covidcast#942]
### Survey Dashboard

- Mask Use "In the past 7 days, when you were in public places where social distancing is not possible, did most or all other people wear masks?" to switch from using `smoothed_wothers_masked` to `smoothed_wothers_masked_public`. Meaning is the same.
- Vaccines "Have you already received a COVID vaccine, or if a vaccine were offered to you today, would you definitely or probably choose to get vaccinated?" to switch from `smoothed_wvaccinated_or_accept` to `smoothed_wvaccinated_appointment_or_accept`. This now includes people who are vaccinated, who have an appointment to be vaccinated, or who say they would get vaccinated if offered today.
- Mental Health "In the past 7 days, did you feel isolated most or all of the time?": `smoothed_wfelt_isolated_7d` discontinued, no replacement
- Mental Health "Do you feel very or somewhat worried about becoming seriously ill from COVID-19?": `smoothed_wworried_become_ill` discontinued, no replacement
- Testing "In the past 14 days, did you want a COVID-19 test but not receive one?": `smoothed_wwanted_test_14d` discontinued, no replacement

### COVIDcast Map

- Vaccine Acceptance "Percentage of people who either have already received a COVID vaccine or would definitely or probably choose to receive one if it were offered to them today, based on surveys of Facebook users" to switch from `smoothed_wvaccinated_or_accept` to `smoothed_wvaccinated_appointment_or_accept`. This now includes people who are vaccinated, who have an appointment to be vaccinated, or who say they would get vaccinated if offered today. Technical description link is still valid.

**Comment by nmdefries** [comment]
@sgratzl I'm not able to assign anyone, but I believe you're the correct person for this. Let me know otherwise/if you need more info for any of these changes.

**Comment by sgratzl** [comment]
can you suggest the changes in the google docs describing those aspects: https://docs.google.com/document/d/1llv6xh8jMlmVv7WpyDSv4VgUpFAZQ6QjFUeRxxOinmk/edit and https://docs.google.com/document/d/1J36nedP6eufeRE3TbyT_BK-ofE5d18kLif2UmORkYDU/edit#heading=h.oxebzdy7nl8w

**Comment by nmdefries** [comment]
Suggestions are added.

**Comment by sgratzl** [comment]
@capnrefsmmat can you take a look at the changes, please and accept them if they are ok.

**Comment by capnrefsmmat** [comment]
@nmdefries `smoothed_covid_vaccinated_appointment_or_accept` will have no history before Wave 11, correct? So the public map will show vaccine acceptance data as only starting today, which seems unfortunate.

I tweaked the wording and accepted the changes in the survey dashboard. I also took the opportunity to change all survey signals to use the weighted versions.

**Comment by nmdefries** [comment]
> smoothed_covid_vaccinated_appointment_or_accept will have no history before Wave 11, correct? So the public map will show vaccine acceptance data as only starting today, which seems unfortunate.

That's correct. Is it possible to display the signals together on the map? Or keep the old `smoothed_covid_vaccinated_or_accept` map up in an archive location and have an alert pop up that links to it when people look at the new `smoothed_covid_vaccinated_appointment_or_accept`?
