### ISSUE TITLE
Data export tool should show date ranges for survey signals that changed, allow downloads of old versions

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-covidcast#949]
Some of the survey signals changed names, and the dashboard can now accommodate revisions and show old versions. But the [data export tool](https://delphi.cmu.edu/covidcast/export/) does not make the old versions accessible. It should

* List the old signal versions (maybe with a "Wave 4-8" label indicating their range)
* Show the revision description when a different version is selected, and indicate the date range available for the revision
* Allow download of the old data

Also, the "Advanced Data Export" button under each graph in the dashboard should link to the correct revision.

**User story**

A user hears that we have mask data available since September and clicks the Export Data button. They select September - December and it tells them no data is available.

**Comment by sgratzl** [comment]
related to the new ongoing approach of a unified meta data which then can be used for a better export data feature, see also https://docs.google.com/spreadsheets/d/1zb7ItJzY5oq1n-2xtvnPBiJu2L3AqmCKubrLkKJZVHs/edit#gid=0

**Comment by sgratzl** [comment]
closing since export data allows to download all signals
