### ISSUE TITLE
No data shown in indicator graph on mobile with certain toggle selections

### ISSUE THREAD

**Issue by kateharwood** [cmu-delphi/www-covidcast#968]
**Actual Behavior:**

Steps to repro:
1. On mobile browser, choose indicator cases or deaths
2. Select "raw data" "cumulative data" and "show all dates"

Observed: no data shown in graph

**Expected behavior**
 Data shown

**Context**

- iPhone 12 mini, Safari

**Additional context**

**Comment by sgratzl** [comment]
I think we just have a resolution problem that one bar is smaller than 1px

**Comment by sgratzl** [comment]
![image](https://user-images.githubusercontent.com/4129778/123454557-fd0fe500-d5e0-11eb-8d74-f7b639060e89.png)

![image](https://user-images.githubusercontent.com/4129778/123454614-0d27c480-d5e1-11eb-801b-158c8f312a66.png)

we could hide the "Show All Dates" on mobile
