### ISSUE TITLE
Export Data available sources don't match expected set(s)

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#983]
**Actual Behavior:**

Export Data is showing a weird subset of covidcast sources which leaves out some sources included in the Explore pages (as encoded in the signal description doc) and includes several inactive sources (as encoded in the meta sheet).

| All sources | Export Data | Active | Explore |
| ----------- | ------------ | ------ | ------- |
| chng | | x | 
| covid-act-now | x | x | 
| doctor-visits | x | x | x
| fb-survey | x | x | x
| ght | x | |
| google-survey | x | |
| google-symptoms | x | x | x
| hhs | x | x |
| hospital-admissions | x | x | x
| indicator-combination | | x | x
| jhu-csse | x | x |
| quidel | | x | x
| safegraph |  | x | x
| usa-facts | x | x |

**Steps to Reproduce the Bug:**

1. go to https://delphi.cmu.edu/covidcast/export/
2. Observe list of sources

**Expected behavior**

Any of the following would be preferable to the current set:
* All sources
* All active sources
* All sources shown on Explore pages

**Screenshots**

![image](https://user-images.githubusercontent.com/1158666/126227571-63d4e444-9ee3-47dd-8981-e7d7c018b12b.png)

**Rating Scale (1 is minor, 7 is severe):** 5 -- confusing; blocking for users looking for excluded sources; nonblocking for everyone else

**Context**

- Browser: Chrome

**Comment by sgratzl** [comment]
should be fixed with the latest meta data
