### ISSUE TITLE
Export Data variant selection is confusing

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-covidcast#984]
**Actual Behavior:**

Variant selection does not clearly present the available options. The user is presented with two select boxes: the first uses the prose name for one of the base signals available from this source, and the second uses the API name for the variants available for the selected base signal.

API names are used nowhere else on the website, so this is likely to confuse users for whom the Export Data page is their only access to the data. Additionally, some signals in the meta sheet use prose names which are specific to the variant, making the text insufficiently general to use as a label for a collection of variants.

The fix will likely require work across both www-covidcast and the meta sheet.

**Steps to Reproduce the Bug:**

1. Go to https://delphi.cmu.edu/covidcast/export/
2. Select any of the cases/deaths signals
3. Observe SELECT SIGNAL

**Expected behavior**

The names in the first select box should be general enough to cover all variants.

Individual variants should be legible to users unfamiliar with the API.

The intended variant-specificity of names and descriptions in the meta sheet should be treated uniformly across all signals, and documented in the Note on the column header in the sheet.

A few implementation possibilities:

1. Make the signal name column suitable for all variants. Make the Short Description specific to the variation and suitable for use in the second select box.
2. Add a new column to the signals meta sheet that stores a prose name to use for all variants of a base signal. Make the signal names of all variations specific to the variation and suitable for use in the second select box. 
3. Use the "source subdivision" meta sheet functionality to store the prose name to use for all variants of a base signal. Make the signal names of all variations specific to the variation and suitable for use in the second select box. 
4. Add a new sheet for collections of variants, and use this instead of the current "base signal" approach

also open to others. I do notice the category chips and the description text for each variant shows up below the select boxes, but that doesn't help defray the initial confusion, only helps soothe it after the user has clicked around experimentally, and only if that part of the interface is visible while they do so.

**Screenshots**
![image](https://user-images.githubusercontent.com/1158666/126232287-4161a60f-f252-4650-a903-9f83ed85cb95.png)

**Rating Scale (1 is minor, 7 is severe):** 4 -- confusing; ultimately nonblocking, but will reduce our conversion rate

**Context**

- Browser:Chrome

**Comment by sgratzl** [comment]
an alternative is to make each signal name specific enough and then we don't provide the variant selector but go back to a full list of signals in this data source

**Comment by krivard** [comment]
meta is now unique signal name -compliant.
